### ISSUE TITLE
Test with PhantomJS 1.9 and 2.0

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#123]
I assumed that pa11y worked with PhantomJS 1.9 and 2.0 but I may be wrong. We should investigate this and clarify the versions of PhantomJS that we support in the README.

As an extra, it may even be possible to test with multiple versions of PhantomJS on Travis. If we can then we should.

**Comment by petetnt** [comment]
FWIW the reason why I didn't get `pa11y` to run on 1.9. might have been due to the Windows binaries, not Phantom@v1 itself. But I didn't test much around it due to `v2` immediately working as expected.

**Comment by kranthi10** [comment]
How do I locally install all pa11y dependencies with npm install. I have tried npm install and it is showing timeout error. Am I missing something please advice. Thanks

**Comment by rowanmanning** [comment]
Hi @kranthi10, this isn't relevant to the issue with testing PhantomJS. Could you [open a new issue](https://github.com/springernature/pa11y/issues/new) with details about your operating system and Node.js version, please?

**Comment by hollsk** [comment]
I've run some local testing on this and can confirm everything works as expected on Mac OS with the following versions of PhantomJS:
- 1.8.2
- 1.9.2
- 1.9.8
- 2.1.1

Phantom 1.7 fails, but that is the oldest version that it's possible to install with Homebrew, so we definitely shouldn't worry about that. I haven't tested on Phantom 2.0 but as noted in my list, Phantom 2.1 works fine. I don't believe it's possible to install Phantom 2.0 anymore (Phantom don't provide old release binaries that I know of) so in the absence of being able to confirm with the earlier version perhaps we should recommend the latest stable version?

I don't have a Windows machine to test on so this is dancing around the issue a bit. I'm more than willing to believe that the problem might ultimately be down to Windows binaries, though!
