### ISSUE TITLE
Has anyone used pa11y on AWS Lambda?

### ISSUE THREAD

**Issue by adelevie** [pa11y/pa11y#140]
For scanning many pages, it can be advantageous to outsource the work to something like AWS Lambda.

Has anyone tried that? I'm going to be investigating this myself, and it would be nice to know of any successful techniques or pitfalls.

**Comment by rowanmanning** [comment]
Hey @adelevie, are we OK to close this issue now?

For anybody interested in running Pa11y in AWS Lambda, 18F have open sourced their solution here: https://github.com/18F/pa11y-lambda

@hollsk, @joseluisbolos, or @nickcall: do you fancy adding a link to the [examples part of the README](https://github.com/springernature/pa11y#examples)?
