### ISSUE TITLE
Document that `make build-htmlcs` won’t run with npm 3.x

### ISSUE THREAD

**Issue by joseluisbolos** [pa11y/pa11y#144]
The command `make build-htmlcs` that is used to manually pull the latest version of HTML codesniffer  won’t run with npm 3.x at the moment, only with npm 2.x.

We need to document that, at least until it can be fixed.

**Comment by rowanmanning** [comment]
I'm pretty sure this has magically fixed itself, because I can run with npm `3.10.10` fine. Let's close, as it's only ever one of the core maintainers who would do this work anyway.
