### ISSUE TITLE
Contributing to Pa11y

### ISSUE THREAD

**Issue by JordanGS** [pa11y/pa11y#150]
Hi Guys,

I've been using pa11y for accessibility testing and I wrote a couple shell scripts that solve the following two issues for me. There is also another script which generates a different type of report, bootstrap enhanced.

The issues I had were 98 which was resolved and then 91 which you are working on.
Allow running of additional PhantomJS code before pa11y runs #98
Ability to test multiple URLs in a single invocation of the CLI #91 

I was wondering if you'd be interested in me sharing them? I'm not really sure how to go about contributing. They don't change any of the current functionality of pa11y. They simply augment an already great system and enhance it a little bit.

Cheers, Jordan.

---

Example:

**data** file

```
USERNAME_VAR:username
USERNAME:testuser
PASSWORD_VAR:password
PASSWORD:password1
SUBMIT:login
AUTH_METHOD:CAS
AUTH:click
DEFAULT:https://website.ca/app/
URL:https://website.ca/app/index.html
FILE:INDEX
URL:https://website.ca/app/business.html
FILE:BUSINESSES
```

The script uses the above **data** file for example to inject the specified values into a **template** config file and then invokes pa11y for each URL and saves the report as FILE.txt

**Comment by rowanmanning** [comment]
Hi @JordanGS. Thanks a lot for sharing, it's always great to hear from Pa11y users!

As you point out we've addressed #91, but if you have any feedback on our implementation then it'd be good to get your opinion. Currently it's very bare-bones, and there's no reason why we couldn't add "recipes" in future which make tasks like logging in a little simpler.

With your enhanced reporter, it's actually possible to [publish and use Pa11y reporters as separate modules](https://github.com/springernature/pa11y#reporters) – if you're interested in doing this, I'd be happy to lend a hand or answer any questions you have. It'd also be good to link to your module in the README if you publish one. There's an [example reporter here](https://github.com/springernature/pa11y-reporter-1.0-json) which gives you an idea of how to structure it.

We're currently writing a contributor guide as part of the new Pa11y website which will attempt to make it clearer how you can give back to the project.

**Comment by JordanGS** [comment]
@rowanmanning let me finish up a couple things and i'll show you what i have done so far and the justification behind it. Then you can recommend the best way to proceed. I'll be ready to upload early next week. I'm just testing several sites right now via Jenkins to make sure it's working as intended :)

**Comment by qaDream77** [comment]
@rowanmanning Sorry i haven't update this in two weeks, i've struck a road block that i'm not sure how to resolve.

**Comment by Rayraegah** [comment]
@JordanGS do you have a fork of this feature? I've built something similar, using the UI testing script to change the state of a page and then execute pa11y on it (repeated for each page or module in a webapp). We simply piggyback on our existing scripts which powers our Selenium UI tests and [Wraith](https://github.com/BBC-News/wraith)

**Comment by JordanGS** [comment]
@Rayraegah Not currently, it's all in pieces. I am still working on integration since I’ve been busy with other projects. I am hoping to have something to show by next week.

Your configuration might be better than mine since you use selenium UI tests to launch pa11y, I couldn't figure out how to do that myself when I was trying to get pa11y to scan the current page.

Let's talk again next week and we can compare and contrast, maybe help each other improve both our tests :)

**Comment by Rayraegah** [comment]
I'll give you a fork of this code. I have it in an enterprise git; but I'll move this feature out like I did last time :)

**Comment by hollsk** [comment]
Gonna close this issue as it's been around for a while with no current open question 😁 

We're definitely always interested in things like recipes and examples, though! We've been meaning to create a cookbook of sorts for a while.
