### ISSUE TITLE
How to get HTML/Other reports when running node?

### ISSUE THREAD

**Issue by joviano-dias-springernature** [pa11y/pa11y#156]
Finding pa11y great. Was able to build a decent multi-url script and also build a docker image to run pa11y on cli. One thing still remains to be resolved though. How do I get HTML reports when running using node?
I know that running it via pa11y, the reporter can be specified. E.g.
 ```
pa11y --reporter csv nature.com > report.csv
```
How do I do the same with node?
```
node pa11y-tests/all/
```

Right now, I just get the results printed onto the console as 

```
[
    {
        code: 'WCAG2AA.Principle1.Guideline1_1.1_1_1.H30.2',
        context: '<a href="http://example.com/"><img src="example.jpg" alt=""/></a>',
        message: 'Img element is the only content of the link, but is missing alt text. The alt text should describe the purpose of the link.',
        selector: 'html > body > p:nth-child(1) > a',
        type: 'error',
        typeCode: 1
    },
    {
        code: 'WCAG2AA.Principle1.Guideline1_3.1_3_1.H49.B',
        context: '<b>Hello World!</b>',
        message: 'Semantic markup should be used to mark emphasised or special text so that it can be programmatically determined.',
        selector: '#content > b:nth-child(4)',
        type: 'warning',
        typeCode: 2
    },
    {
        code: 'WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81',
        context: '<a href="http://example.com/">Hello World!</a>',
        message: 'Check that the link text combined with programmatically determined link context identifies the purpose of the link.',
        selector: 'html > body > ul > li:nth-child(2) > a',
        type: 'notice',
        typeCode: 3
    }
]
```

**Comment by rowanmanning** [comment]
Hi @joviano-dias-springernature, I _think_ this might be a duplicate issue #137. Does that look like it might be the same? I'm hopefully going to look into making reporters usable to the JavaScript interface soon.

I'm going to close but happy to reopen if you're looking for something different :)

**Comment by joviano-dias-springernature** [comment]
@rowanmanning yep, this seems to be the same issue. I just performed an untidy workaround. Will update it on the original one. Thanks!
