### ISSUE TITLE
spidering support

### ISSUE THREAD

**Issue by stephenmathieson** [pa11y/pa11y#16]
i know it's a _huge_ feature request, but spidering support would be extremely helpful.

it'd be nice to also be able to specify a maximum depth of spidered pages:

``` sh
$ pa11y http://website.org/ --depth 15
```

thoughts?  i'd be happy to contribute, or create a separate module (`pa11y-spider`?) for such a task.

**Comment by adelevie** [comment]
Hey, I pieced together a fairly simple way to achieve this:

```
wget -q http://localhost:1313/sitemap.xml --no-cache -O - | egrep -o "http://localhost:1313[^<]+" | xargs -I '{}' pa11y {}     

```

**Comment by DanielRuf** [comment]
I will probably write a script which does this. For pa11y and a11y.
