### ISSUE TITLE
CodeSniffer error fails to run via command line from bash script.

### ISSUE THREAD

**Issue by JordanGS** [pa11y/pa11y#165]
In an .sh file i have the following: `pa11y --config $FILENAME.js "$URL" > OUTPUT/$FILENAME.txt` with passed in parameters will randomly generate the following error:

```
 > Error: Test function errored for "https://mysite.ca/contact.html"
Error: HTML CodeSniffer: undefined is not an object (evaluating 'f.nodeType')
    at Object.<anonymous> (/home/automaton/.linuxbrew/lib/node_modules/pa11y/lib/pa11y.js:63:16)
    at Object.f [as onCallback] (/home/automaton/.linuxbrew/lib/node_modules/pa11y/node_modules/once/once.js:17:25)
    at /home/automaton/.linuxbrew/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:619:30
    at Array.forEach (native)
    at IncomingMessage.<anonymous> (/home/automaton/.linuxbrew/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:600:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any clarifications on this error would be appreciated, i am unsure myself after having attempted to troubleshoot on google and stack.

**Update:**
This doesn't always happen. Seems random, it'll work once or twice, then fail and go back and forth that way, etc.

**Update 2:** Running with debug flag

Welcome to Pa11y
```

 > PhantomJS browser created
 > Debug: PhantomJS page created
 > Debug: Opening "https://mysite.ca/contact.html" in PhantomJS
 > Debug: Opened "https://mysite.ca/contact.html" in PhantomJS
 > Testing the page "https://mysite.ca/contact.html"
 > Debug: Running beforeScript
 > Debug: Injecting HTML CodeSniffer
 > Debug: Injecting Pa11y
 > Debug: Running Pa11y on the page
 > Debug: PhantomJS page closed
 > Debug: PhantomJS browser exited
```

There is nothing else to the Pa11y report

**Update 3:** I've updated the run command, since it is in a for loop iterating all URL's, i am now running them as background process `pa11y --config $FILENAME.js "$URL" > OUTPUT/$FILENAME.txt &`

Going to leave this running via Jenkins overnight and will update tomorrow if the issue still persists.

**Comment by rowanmanning** [comment]
Hi @JordanGS :)

I haven't seen this before, it actually looks like an [HTML CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) error. Could you try running the bookmarklet against your page to see if that works? If it doesn't work, then it'd be best to reopen this issue with them.

**Comment by JordanGS** [comment]
@rowanmanning I tried running the bookmarklet (The one that's a bookmark in my browser) and it works with no issues.

**Comment by JordanGS** [comment]
@rowanmanning fixed it, the pa11y command needs to be run as a background process on linux, need to watch the pid and wait for it to finish or kill it if it hangs. Good stuff. =D
