### ISSUE TITLE
Pass the original url to the beforeScript feature

### ISSUE THREAD

**Issue by GlynnPhillips** [pa11y/pa11y#169]
It could be useful for the `beforeScript` feature to know about the original url passed to pa11y.

One user case would be logging into a site that has a barrier/paywall but don't respect the users original request after log in.
- `pa11y --debug --config config.js "https://example.com/cool-story"`
- https://example.com/cool-story automatically redirects you to https://example.com/barrier
- The `beforeScript` within the `config.js` would handle logging into `example.com`
- Then `beforeScript` could use the original url to redirect back to the correct place.

**Comment by rowanmanning** [comment]
I'm gonna suggest closing this, as we're trying to encourage people away from `beforeScript` and towards actions. @GlynnPhillips: you happy with that?

**Comment by GlynnPhillips** [comment]
Over the moon 🌝
