### ISSUE TITLE
Can I do *.html and get all HTML files in a directory?

### ISSUE THREAD

**Issue by DarthOpto** [pa11y/pa11y#173]
If I have a directory with lots of other directories with HTML files in several of them, is there a way to look for all of the HTML files and run pa11y against them?
For example:
```
root directory
     first directory
          first.html
     second directory
          second.html
```
could I point to the root directory and then run `pa11y file:/root/*.html`?

**Comment by hollsk** [comment]
Hi @DarthOpto !

Something like this might do the trick: https://github.com/pa11y/pa11y/blob/master/example/multiple-concurrent/index.js

The example uses URLs directly, so it'd need to be tweaked a little to look at the local filesystem recursively (you can do that with Node's `fs` module). 

Hope that helps get you on track!

**Comment by DarthOpto** [comment]
@hollsk Thank you very much. I will give that a shot. As a side note, will this work with an Angular app?

**Comment by hollsk** [comment]
That's a very good question. Theoretically, it should work. Pa11y spins up a PhantomJS headless browser as its test environment, and Phantom supports AngularJS, so I can't see any immediate reason why it wouldn't work. 

I _think_ it should be fine - so long as the files are recognisable HTML, they should be parsed as such.

**Comment by DarthOpto** [comment]
Thank you.

Curtis Salisbury, MBA, MHRM
curtis.salisbury@gmail.com
curtissalisbury@yahoo.com

(801)310-4173 (Mobile)
(801)899-2143 (Home)

**Comment by hollsk** [comment]
You're welcome - I'll close this issue now, and if you have any problems, please open a new one. 

Enjoy! :-)
