### ISSUE TITLE
Different Results Command Line v. Node Script

### ISSUE THREAD

**Issue by DarthOpto** [pa11y/pa11y#174]
I am getting completely different results when I go through the command line just to my login page I am getting 11 errors, 3 warnings, and 9 notices. When I run my javascript file, I am only getting the following:

```
[ { code: 'WCAG2AA.Principle2.Guideline2_4.2_4_2.H25.2',
    context: '<title>DG Incident Response</title>',
    message: 'Check that the title element describes the document.',
    selector: 'html > head > title',
    type: 'notice',
    typeCode: 3 },
  { code: 'WCAG2AA.Principle3.Guideline3_1.3_1_1.H57.2',
    context: '<html><head><style type="text/css">@c...</html>',
    message: 'The html element should have a lang or xml:lang attribute which describes the language of the document.',
    selector: 'html',
    type: 'error',
    typeCode: 1 } ]
```

The javascript file I am using is below: 

``` javascript
'use strict';

var pa11y = require('pa11y')

// create a test instance with some default options
var test = pa11y({

    // Log what's happening to the console
    log: {
      debug: console.log.bind(console),
      error: console.error.bind(console),
      info: console.log.bind(console)
    }
});

//Test the login screen
test.run('http://10.26.3.12:8080/#/Account/Login', function(error, result){
  if (error){
    return console.error(error.message);
  }
  console.log(result);
});

```

Am I doing something wrong? As a side note, the web app I am trying to test is an angular app.

**Comment by hollsk** [comment]
How strange. Your script is correct, so no need to worry there. Could you please show us what the HTML source looks like so that we can try to replicate? A gist or codepen will be fine, no need for the full app. 

Thanks!

**Comment by DarthOpto** [comment]
It’s an angular app, and I am in test so I have no idea where everything is that would be needed. The HTML for that page is pretty sparse and only has just a couple of elements as everything else is part of the Angular stuff I believe.

**Comment by hollsk** [comment]
I'm interested in the HTML that Pa11y _actually_ sees versus what it _should_ see - if it's mangled, or cut off, or perhaps if it's somehow being redirected to a page that it shouldn't be. 

You can try adding a beforeScript method to your code that will output the HTML of the current page. I've added an example below. Does the HTML it outputs match what you see when you visit the login page in a browser and view source? 

```
'use strict';
var pa11y = require('pa11y')

var testUrl = "http://10.26.3.12:8080/#/Account/Login";

// create a test instance with some default options
var test = pa11y({

    // Log what's happening to the console
    log: {
      debug: console.log.bind(console),
      error: console.error.bind(console),
      info: console.log.bind(console)
    },

    // beforeScript() accepts three parameters: the page object, the pa11y options, and a callback 
	beforeScript: function(page, options, next) {

		page.onConsoleMessage = function(msg) {
		  console.log(msg);
		}

		page.open(testUrl, function(status) {
		  page.evaluate(function() {
		  	console.log(document.documentElement.outerHTML);
		  });
		});

		// Call next() to continue with the tests 
		next(); 
	}

});

//Test the login screen
test.run(testUrl, function(error, result){
  if (error){
    return console.error(error.message);
  }
  console.log(result);
});
```

**Comment by DarthOpto** [comment]
I believe that all it is seeing is this which is what I get when I do View Source:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>Removing Company Title</title>

        <!--have to load here so the script loader will work-->
        <script src="resources/js/jquery-2.1.1.js"></script>
        <script src="load-reporting-resources.js"></script>
    </head>
    <body ng-app="digitalGuardian_module" ng-controller="appCtrl" ng-class="{waiting:appIsWaiting}">
        <div ui-view></div>
    </body>
</html>
```

Versus what I see when I open up the developer tools, which is a lot more.

**Comment by hollsk** [comment]
Great, that helps, thanks! So the contents of the view aren't being loaded. Since it works ok on the CLI, it sounds like a race condition. 

A quick and dirty workaround might be to use the `wait` option in Pa11y, to pause testing until (hopefully) Angular has finished rendering its components:

```
...
// create a test instance with some default options
var test = pa11y({
    wait: 5000,
    log: {
      debug: console.log.bind(console),
      error: console.error.bind(console),
      info: console.log.bind(console)
    },
...
```

A more robust way to handle it would be to emit an event from your app once Angular has finished loading:

```
$scope.$on('$viewContentLoaded', function () {
  window.callPhantom();
});
```

... and then use beforeScript in your Pa11y script to halt the tests until that event is received (I didn't test this code):

```
	beforeScript: function(page, options, next) {
		page.onCallback = function() {
			console.log('Received callback');
			next(); // direct Pa11y to continue
		};
	}
```

**Comment by DarthOpto** [comment]
I actually did add a 10 second wait to my script and it had no effect. I got the same results.

**Comment by hollsk** [comment]
Yep, it doesn't always work for some reason (I've never tried this myself, that's just what I see from other people's issues around the 'net). Try the second method, which is the more "proper" way to do it. Essentially the problem is occurring between Angular and Phantom, so try the tools that Angular and Phantom provide. 

Here's the Angular documentation on emitting an event once the view has loaded: https://github.com/angular-ui/ui-router/wiki#view-load-events

And this is the Phantom documentation for the callback handler (the `beforeScript` method I've provided in my previous comment will cover that): http://phantomjs.org/api/webpage/handler/on-callback.html

**Comment by rowanmanning** [comment]
Did we get anywhere with this? I'm going to close as a potential incompatibility between Angular and PhantomJS but happy to reopen if that's not the case.
