### ISSUE TITLE
Error: HeadlessError: Phantom immediately exited with: 127

### ISSUE THREAD

**Issue by mgifford** [pa11y/pa11y#175]
I'm not sure why I'm getting this error. I'm just trying to set this up. 

$ pa11y nature.com
Welcome to Pa11y

 > Error: HeadlessError: Phantom immediately exited with: 127
    at ChildProcess.immediateExit (/usr/local/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:153:23)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by hollsk** [comment]
Hi @mgifford - could you give us a little more info about your setup, please? Node version and Phantom version? Also are you running on your local machine or in a container? What's the operating system?

**Comment by mgifford** [comment]
Hmm..  I have gone through the steps, but something seems to be off it's true. I can't run this:

```
$ /usr/local/bin/phantomjs -v
env: node\r: No such file or directory
```

I'm doing this on a Mac...

**Comment by hollsk** [comment]
Hm. Looks like your Phantom executable is in DOS mode and throwing an error on an `/r` line ending. You can try converting it to Unix-style format instead - if you're using [Homebrew](https://github.com/Homebrew/brew), then you can do:

```
$ brew install dos2unix
$ dos2unix /usr/local/bin/phantomjs
```

**Comment by mgifford** [comment]
That seemed to work, thanks!

I couldn't actually apply dos2unix to /usr/local/bin/phantomjs though as it was a symbolic link.  I tracked down exactly where this was causing me grief with:

```
$ which phantomjs
/usr/local/bin/phantomjs
$ ls -la /usr/local/bin/phantomjs
lrwxr-xr-x  1 mikegifford  admin  44 14 Jul 17:54 /usr/local/bin/phantomjs -> ../lib/node_modules/phantomjs2/bin/phantomjs
```

**Comment by hollsk** [comment]
Oh, good catch. I'll need to remember that if the situation pops up again, thanks!

**Comment by PhillyWebGuy** [comment]
I've gotten to the point of getting the dos2unix error with symbolic links. Then what? Where do I go from there?

**Comment by PhillyWebGuy** [comment]
Ah, nevermind. I figured it out.

**Comment by mgifford** [comment]
Ultimately what fixed my issue seemed to be http://stackoverflow.com/questions/18218134/warning-phantomjs-not-found 

and specifically:

npm install phantomjs -g
