### ISSUE TITLE
Context markup different than source code

### ISSUE THREAD

**Issue by DannyJoris** [pa11y/pa11y#176]
I'm getting errors related to HTML objects. When I navigate to the site, I'm seeing iframes instead. The markup is related to a video player, so I assume that the object is replaced with an iframe with javascript.

I tried setting a timeout, but that didn't work either: `pa11y http://msbonline.georgetown.edu/ --wait 10000`.

This is the error I'm getting, which is not reflected when visiting the site:

```
 • Error: Object elements must contain a text alternative after all other alternatives are exhausted.
   ├── WCAG2AA.Principle1.Guideline1_1.1_1_1.H53
   ├── #kaltura_player_1463757730
   └── <object style="display: block;;display:block;" class="" id="kaltura_player_1463757730" name="kaltura_player_1463757730" data="https://cdnapisec.kaltura.com/index.php/kwidget/wid/_941911/uiconf_id/32796641/entry_id/1_tut379zd/cache_st/1" type="applica...
```

Has PhantomJS javascript disabled when performing audits?

**Comment by rowanmanning** [comment]
Hi Danny, I'll look into this. No, we don't disable JavaScript when we're running Pa11y on a page, so it's not that.

**Comment by rowanmanning** [comment]
Hi @DannyJoris, I'm not able to replicate the issue at the moment – has your page changed? I don't get the error that you mention when I run the following (with other errors ignored for clarity):

```sh
pa11y http://msbonline.georgetown.edu/ --wait 10000 --ignore "warning;notice;WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail;WCAG2AA.Principle1.Guideline1_1.1_1_1.H37;WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.NoContent;WCAG2AA.Principle2.Guideline2_4.2_4_1.H64.1;WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Button.Name;WCAG2AA.Principle1.Guideline1_1.1_1_1.H30.2;WCAG2AA.Principle1.Guideline1_3.1_3_1.H42.2;WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.EmptyNoId"
```

**Comment by hollsk** [comment]
This issue is pretty old now, so I'm assuming you've long since fixed your problem and/or moved on ;) 

If you need anything from us in future, we can do it in a new issue 👍
