### ISSUE TITLE
Can't open a site hosted on the same vps

### ISSUE THREAD

**Issue by jonnybarnes** [pa11y/pa11y#177]
Pa11y works with a friends site hosted on his server, but not with my site on my server.

A sample entry from `~/.pm2/logs/pa11y-out.0.log`:

```
Starting to run tasks @ Tue Jul 19 2016 00:30:00 GMT+0100 (BST)
Starting task 57856decb48b466a480725f0
Starting task 57856eecb48b466a480725f2
  > PhantomJS page created
  > PhantomJS page created
  > Opening "https://jonnybarnes.uk" in PhantomJS
  > Opening "https://aaronparecki.com" in PhantomJS
  > PhantomJS page closed
  > PhantomJS browser exited
Failed to finish task 57856eecb48b466a480725f2: Page "https://jonnybarnes.uk" could not be opened
  > Opened "https://aaronparecki.com" in PhantomJS
  > Injecting HTML CodeSniffer
  > Injecting Pa11y
  > Running Pa11y on the page
  > Waiting for 3000ms
  > Test function ran for "https://aaronparecki.com"
  > PhantomJS page closed
  > PhantomJS browser exited
Finished task 57856decb48b466a480725f0
Finished running tasks @ Tue Jul 19 2016 00:30:11 GMT+0100 (BST)
```

Now, its not actually phantomjs, this test script opens my page as expected:

``` js
var page = require('webpage').create();
var url = 'https://jonnybarnes.uk';

console.log('Loading: ' + url);

page.onResourceError = function(resourceError) {
    page.reason = resourceError.errorString;
    page.reason_url = resourceError.url;
};

page.onResourceReceived = function(response) {
    console.log('Response (#' + response.id + ', stage "' + response.stage + '"): ' + JSON.stringify(response));
}

page.open(url, function(status){
    if (status !== 'success') {
        console.log('Error opening URL ' + page.reason_url + ', because: ' + page.reason);
        phantom.exit(1);
    } else {
        console.log('Open page success');
        phantom.exit();
    }
});
```

So I’m not sure what gives. FYI, my vps is running Debian 8.5 and has node 6.3.0 installed.

**Comment by hollsk** [comment]
Hi @jonnybarnes - thanks for the detailed ticket! 

We use `'ssl-protocol': 'tlsv1'` in the config by default, and it looks like your webserver is rejecting that request due to a protocol mismatch. If you change your pa11y config to use `'ssl-protocol': 'any'` that should get you up and running.

**Comment by jonnybarnes** [comment]
Where would I declare the `ssl-protocol` value? Adding it to `config/production.json` seems not to work.

**Comment by jonnybarnes** [comment]
Okay, directly editing `pa11y.js` inside the `node_modules/` works! :D

But an `npm update` could overwrite that in the future...

**Comment by hollsk** [comment]
Glad you got it working! And you're right about the overwriting - normally you'd want to create a new file elsewhere to spin up a Pa11y instance, and override the default configuration there. We've put some basic examples up here: https://github.com/pa11y/pa11y/tree/master/example

**Comment by hollsk** [comment]
We deployed an update to one of Pa11y's dependencies that should make debugging this kind of issue easier in future: https://github.com/springernature/truffler/pull/13
