### ISSUE TITLE
pa11y command line options as configuration options

### ISSUE THREAD

**Issue by PhillyWebGuy** [pa11y/pa11y#186]
Is there a reason why we can't include things like reporter configuration in configuration files?

**Comment by rowanmanning** [comment]
No reason, no. It would make sense for you to be able to configure Pa11y in either place, it's just that nobody has had time to do it. Would happily accept a PR :)

**Comment by PhillyWebGuy** [comment]
Ok. In that case, you maybe hearing from me again :)

**Comment by Rayraegah** [comment]
We considered this at first, but soon moved all our pa11y config to npm scripts and simple bash files and launch them with specific commands line:

```
npm run pa11y:csvreport
npm run pa11y:xyzconfig
```

**Comment by andrewmee** [comment]
I'm undertaking this work over here; https://github.com/pa11y/pa11y/pull/355

Should hopefully make it into the pa11y 5 initial release, or soon after!

**Comment by rowanmanning** [comment]
This has been added in `5.0.0-beta.4`
