### ISSUE TITLE
Cookie only works on initial request

### ISSUE THREAD

**Issue by chiahrens** [pa11y/pa11y#188]
Setting the cookies via headers only sets the cookies on the initial request. Consecutive ajax requests are made without the cookies.

**Comment by rowanmanning** [comment]
Hi @chiahrens, I have a feeling this is probably a limitation of PhantomJS. Could a potential solution would be to set cookie headers explicitly in the AJAX requests on your page?

I'm going to close this as Pa11y does not have the ability to change the way AJAX behaves, but still happy to try and debug with you.

**Comment by thibaudcolas** [comment]
This can now be solved with Puppeteer, by manually creating `browser` and `page` instances and forwarding them to pa11y. Quick example:

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.setCookie({
  name: "sessionid",
  domain: "localhost",
  path: "/",
  value: sessionid,
  expirationDate: 1798790400,
  hostOnly: false,
  httpOnly: false,
  secure: false,
  session: false,
  sameSite: "no_restriction",
});

const options = Object.assign({}, pa11yOptions, {
  browser: browser,
  page,
});

const result = await pa11y(
  `http://localhost:8000/admin${scenario.path}`,
  options,
);
```

As far as I understand, without this it's impossible to have any tests that go beyond the first page load for auth-ed views (any AJAX whatsoever, submitting forms / navigating).
