### ISSUE TITLE
Invalid JSON output?

### ISSUE THREAD

**Issue by kahunacohen** [pa11y/pa11y#191]
Hi, the default reporter and the json reporter seem to output invalid json. For example, keys have no double quotes, and values are single quoted. I can't imagine why since you are using `bfj` module which I assume would properly parse JSON.

**Comment by joseluisbolos** [comment]
Hi @kahunacohen 

Thanks for your bug report.

Unfortunately, I can't seem to be able to to replicate this issue here. For example, running the following command:

```pa11y --reporter json nature.com > report.json```

Returns the following result (snippet):
```
[{"code":"WCAG2AA.Principle2.Guideline2_4.2_4_2.H25.2","context":"<title>Nature Research: science journa...</title>","message":"Check that the title element describes the document.","selector":"html > head > title","type":"notice","typeCode":3},
```

As far as I can see both keys and values are correctly enclosed in double quotes and the result correctly validates.

Could you please provide more details of how are you trying to pa11y (platform, OS, node version, URL, etc) so we can try to replicate this?

Thanks.

**Comment by kahunacohen** [comment]
I am running programmatically from node. That `json` string is invalid. And obviously the `eval` is my quick hack.

```
'use strict';

var async = require('async');
var pa11y = require('../..');
var htmlReporter = require('../../reporter/html');
var jsonReporter = require('../../reporter/json');

var argv = process.argv;
var std = argv[argv.length - 1];


// Create a test instance with some default options
try {
    var test = pa11y({
        standard: std,
        ignore: [
            "Section508.O.NoSuchID",
            "notice"
        ]
        // Log what's happening to the console
        /*
        log: {
            debug: console.log.bind(console),
            error: console.error.bind(console),
            info: console.log.bind(console)
        }
        */

    });
} catch(er) {
    console.log('Problem running test. Did you supply a standard as an argument?');
    process.exit(1);
}

// Define some URLs to test, and a concurrency
var urls = [
    'https://www.ncbi.nlm.nih.gov/',
    'https://www.ncbi.nlm.nih.gov/pubmed',
    'https://www.ncbi.nlm.nih.gov/pubmed?term=cancer',
    'https://www.ncbi.nlm.nih.gov/pubmed/123',
];
var concurrency = 4; // Run four tests at a time

// Use the async library to create a queue. This accepts a
// function to handle the URLs, and a concurrency.
// https://github.com/caolan/async
var queue = async.queue(function(url, done) {

    // The queue function will be called with each URL. We
    // can then run the pa11y test function on them and call
    // `done` when we're finished to free up the queue
    test.run(url, function(error, results) {
        if (error) {
            return console.error(error.message);
        }
        //var html = htmlReporter.process(results, url);
        var json = jsonReporter.process(results, url);
        console.info(JSON.stringify(eval(json)));
        done();
    });

}, concurrency);

// Add a function that is triggered when the queue
// drains (it runs out of URLs to process)
queue.drain = function() {
    //console.log('All done!');
};

// Lastly, push the URLs we wish to test onto the queue
queue.push(urls);
```

**Comment by kahunacohen** [comment]
Node version: v0.10.24
Linux

**Comment by rowanmanning** [comment]
Hi @kahunacohen, I'm looking into this now. For a start, the latest version of [Pa11y only supports Node.js 4+](https://github.com/pa11y/pa11y#support-and-migration). Are you using an older version of Pa11y? (`pa11y --version`).

**Comment by rowanmanning** [comment]
The code you posted above runs fine in Node.js 4.

One thing I notice is that you're logging the JSON for each result separately. If you're piping this into a file then each _line_ will be valid JSON but not the whole thing. You'd need to add each result to an array or something before JSON-encoding it.

If you can explain what you're trying to achieve, then I'm happy to help out with getting your code to output what you expect, but I don't think this is a bug in Pa11y itself.

**Comment by kahunacohen** [comment]
> The code you posted above runs fine in Node.js 4.

Indeed  I was using a very old version of node. I changed to `v4.5.0`, removed my `node_modules` directory and ran `npm install` again, but that doesn't change anything. My code pasted above produces valid JSON because I hacked it with the code:

```
JSON.stringify(eval(json))
```
...but I would expect the `json` variable returned by the line:

```
var json = jsonReporter.process(results, url);
```

to be valid json to begin with. Instead I get stuff like the following which is invalid due to single quoted values and non-quoted keys:

```
...
{ code: 'Section508.D.PresMarkup.B',
    context: '<b>Cancer</b>',
    message: 'Semantic markup should be used to mark emphasised or special text so that it can be programmatically determined.',
    selector: '#maincontent > div > div:nth-child(5) > div:nth-child(17) > div:nth-child(2) > p > a > b',
...
```
> If you can explain what you're trying to achieve, then I'm happy to help out with getting your code to output what you expect, but I don't think this is a bug in Pa11y itself.

I am simply following your example at https://github.com/pa11y/pa11y/blob/master/example/multiple-concurrent/index.js. I modified the script a bit to take a parameter (standard), test some different URLs, and imported the json reporter.

**Comment by rowanmanning** [comment]
Oh! I understand the confusion. The JSON reporter doesn't actually return a JSON string, this is confusing I know. We added the ability to load reporters in the JavaScript API recently and the JSON one was problematic because the streaming BFJ would have a different API than all of the other reporters.

The JSON reporter actually just returns an object, the same one that's passed in. [You can see it here](https://github.com/pa11y/pa11y/blob/master/reporter/json.js#L31). I'd recommend just using standard `JSON.stringify()` or using BFJ yourself directly rather than this reporter.

Sorry for the confusion, we should clarify the documentation around this.

**Comment by kahunacohen** [comment]
OK. Thanks. Not sure I really understand. Why call it a json reporter? And isn't this the same as the default output?

**Comment by rowanmanning** [comment]
It's called the JSON reporter because its original purpose is to output JSON when used with the CLI version of Pa11y. It still does this using BFJ, but the behaviour just didn't translate over to the JavaScript API when it came to being written.
