### ISSUE TITLE
How to write custom tests

### ISSUE THREAD

**Issue by kahunacohen** [pa11y/pa11y#192]
Loving this product. Not seeing much in the docs apart from some vauge wording about using a config to point to custom standards.

I would love to know how to best write my own standard. I'd be willing to contribute to the docs to make this clearer to others. I also saw in some discussion somewhere that you are abandoning HTML Code Sniffer as  tester and PhantomJS. Is this coming shortly? If so how will this affect being able to write my own tests to fit into pa11y?

**Comment by rowanmanning** [comment]
Hi @kahunacohen. There are no immediate plans to move away from HTML CodeSniffer, as it'd be a significant amount of work and we don't really have the resource to maintain our own testing suite.

In terms of writing your own standard, the best place to look/ask about it is probably the [HTML CodeSniffer repo](https://github.com/squizlabs/HTML_CodeSniffer). Pa11y allows you to reference a custom build of HTMLCS so you could fork it maybe?

**Comment by kahunacohen** [comment]
I see. I'll try this.

**Comment by kahunacohen** [comment]
Can you explain exactly the relationship between HTML CodeSniffer and pa11y? Who sponsers pa11y? Thanks!

**Comment by kahunacohen** [comment]
When I clone html code sniffer, point pa11y using `htmlcs` config at the html cs js file in that cloned repo on my file system, pa11y hangs. Using node v4.5.0 on Linux. Have you guys ever used this option?

**Comment by rowanmanning** [comment]
Hi, yep we've used this option a lot. It requires that you point at a fully built version of HTML CodeSniffer, there are [instructions on how to do this in their repo](https://github.com/squizlabs/HTML_CodeSniffer#building-the-auditor). For the version of HTMLCS that's bundled with Pa11y, we use Make – [you can see the task here](https://github.com/pa11y/pa11y/blob/master/Makefile#L48).

So your code will need a script that creates a built version of HTMLCS for this to work.

**Comment by rowanmanning** [comment]
I'm going to close this issue for now, as it's in the remit of HTML CodeSniffer.
