### ISSUE TITLE
pa11y not parsing html page source, only works with url

### ISSUE THREAD

**Issue by rajesh825** [pa11y/pa11y#196]
Hello, 
I was trying to use Pa11y to parse html page source using -H command line flag

`$ pa11y -H ./index.html   **or**  pa11y --htmlcs ./index.html`

however pa11y not recognising html content and displaying pa11y command line help , even though command line help states can provide path to source from (listed below)

-H, --htmlcs <url>             the URL or path to source HTML_CodeSniffer from 

Am I right in understanding, Pa11y can parse html content,  not just html content from url.

**Comment by rowanmanning** [comment]
Hi @rajesh825, you're misunderstanding the `-H, --htmlcs` option. That is used to point to a custom build of HTML CodeSniffer and not the page you're testing.

You can test local HTML files with Pa11y by using the `file` protocol, as mentioned here: https://github.com/pa11y/pa11y/issues/75#issuecomment-110384123
