### ISSUE TITLE
Multiple user interactions & navigation before testing page

### ISSUE THREAD

**Issue by marcelosomers** [pa11y/pa11y#199]
I'm trying to test a site that requires multiple interactions & login before I can access the page I need to test. This is a similar issue to #162 and #167, but can't seem to find the fix there. I am using the JavaScript interface to test.

The flow I need to configure using `beforeScript` goes something like this:

I want to test http://mysite.com/checkout/delivery.html, but to access we need to:

1. Navigate to http://mysite.com/products/
1. Click Add to Cart & wait to see if product has been added
1. Manually navigate to http://mysite.com/checkout/login.html, fill in fields, and submit
1. Once submitted, we will be at http://mysite.com/checkout/delivery.html and want to test this page

First off, I'm not quite sure if I should do `test.run()` on http://mysite.com/products/ (the page you need to initially navigate to) or http://mysite.com/checkout/delivery.html (the page I actually want to test). The documentation and the referenced issues above make it seem like I run it on the initial page, but that didn't work - it ran the check on the initial page and not where the `beforeScript` ended up.

So I've written this beforeScript, assuming it's the latter, delivery.html (the page I want to test):

```javascript
test.run('http://mysite.com/checkout/delivery.html', {
  beforeScript: function(page, options, next) {
    var waitUntil = function(condition, retries, waitOver) {
      page.evaluate(condition, function(error, result) {
        if (result || retries < 1) {
          // Once the changes have taken place continue with Pa11y testing
          waitOver();
        } else {
          retries -= 1;
          setTimeout(function() {
            waitUntil(condition, retries, waitOver);
          }, 200);
        }
      });
    };

    page.evaluate(function() {
      // start off navigating to the products page
      window.location.href = 'http://mysite.com/products/';
    }, function() {
      waitUntil(function() {
        // wait for the page load
        return window.location.href = 'http://mysite.com/products/';
      }, 20, function() {
        // add the product to the cart
        var addToCartButton = document.getElementById('addToCartButton');
        var cartCount = document.getElementById('cartCount');

        addToCartButton.click();
      }, function() {
        // wait until the item is added to cart
        waitUntil(function() {
          return cartCount.innerHTML === '1';
        }, 20, function() {
          page.evaluate(function() {
            // navigate to the login page
            window.location.href = 'http://mysite.com/checkout/login.html';
          }, function() {
            // wait until the page is loaded
            waitUntil(function() {
              return window.location.href === 'http://mysite.com/checkout/login.html';
            }, 20, function() {
              // log in
              var user = document.querySelector('#username');
              var password = document.querySelector('#password');
              var submit = document.querySelector('#submit');

              user.value = 'exampleUser';
              password.value = 'password1234';

              submit.click();
            }, function() {
              waitUntil(function() {
                // wait for the page to load on the page we want to test
                return window.location.href === 'http://mysite.com/checkout/delivery.html';
              }, 20, next)
            })
          })
        })
      })
    })
  }
}, function(error, results) {
  // handle the results
})
```

However, for some reason the results for this returned to the login page, which I know because this site redirects to a *different* login page than the one referenced in the flow above. I'm guessing it tried to hit the final URL on `test.run()` without executing the `beforeScript`?

So am I doing this right? Which URL should I pass in to test? Do I then navigate back to step 0 to add my product to the cart and walk through all the steps, ending in a `waitUntil()` on the desired test page?

I know this is complex, so I appreciate any help!

**Comment by hollsk** [comment]
Hi @marcelosomers - it's _very_ complex, you're right 😃 

You were correct the first time. The URL in `test.run` is the one that you begin on, and Pa11y only begins to test the page it's currently on once it receives the `next` instruction. I'm assuming that your first script was more or less similar to this one except for the URL, and I think that the complexity of what you're doing has masked the context of how you're going about it. 

The first thing to do is to remove your `beforeScript` from the `test.run` block. That's part of the pa11y configuration setup, so it should be defined elsewhere, the actual run block should be quite sparse. You're looking for something laid out like this: 

```
// set up your initial configurations
var test = pa11y({

	beforeScript: function(page, options, next) {
		var waitUntil = function(condition, retries, waitOver) {
			page.evaluate(condition, function(error, result) {
				if (result || retries < 1) {
					// Once the changes have taken place continue with Pa11y testing
					waitOver();
				} else {
					retries -= 1;
					setTimeout(function() {
						waitUntil(condition, retries, waitOver);
					}, 200);
				}
			});
		};

		// begin the evaluations.... 
		page.evaluate(function() {
			// navigate to first location
		}, function() {
			waitUntil(function() {
				// wait until first thing happens...
			}, 20, function() {
				page.evaluate(function() {
					// navigate to second location
				}, function() {
					waitUntil(function() {
						// wait until second thing happens...
					}, 20, function() {
						page.evaluate(function() {
							// navigate to third location
						}, function() {
							waitUntil(function() {
								/// wait until third thing happens...
							}, 20, next)
						}	
					})
				})
			})
		});

});

// Begin on this URL
test.run('mysite.com/products/', function(error, result) {
	if (error) {
		return console.error(error.message);
	}
	console.log(result);
});
```

The evaluation block I've put in there might not actually work if you try copying it as I got horribly confused with the callback structure! But that's the basic idea. 

Remember to use the PhantomJS context inside each block that interacts with a document - the `// add the product to the cart` and `// log in` methods in your script above are missing that, and so you'll get a not defined error for `document` on those lines. 

Hopefully this will help get you moving forward, please let me know how you get on!

**Comment by marcelosomers** [comment]
Thank you so much for your response! I saw #200 as well, which would be super beneficial, even though it's more of an architecture discussion than pa11y specific. I hope this documentation is able to be written, because this is callback hell for sure.

Makes sense to move the `beforeScript` from the `test.run` block. But FYI, the documentation [makes it sound like you can override it per test](https://github.com/pa11y/pa11y#configuration).

So I tried to pair down my test as I rebuilt it, and it's still testing the original URL, not the one loaded when I call `next`. Here's what I paired it down to:

```
page.evaluate(function() {
  // simulate an interaction on http://mysite.com/products.html
  ...
}, function() {
  waitUntil(function() {
    // wait for a random DOM node changes values on http://mysite.com/products.html
    return cartCounter.innerHTML === '1'
  }, 20, function() {
    page.evaluate(function() {
      // navigate to the checkout login
      window.location.href = 'http://mysite.com/checkout/login.html';
    }, function() {
      waitUntil(function() {
        // wait for checkout login to load and test it
        return window.location.href = 'http://mysite.com/checkout/login.html';
      }, 20, next)
    })
  })
})
```

```
test.run('http://mysite.com/products.html', function(error, result) {
  if(error) {
    return console.error(error.message)
  }
  console.log(result);
});
```

In this case, based on the output results, http://mysite.com/products.html is tested (the page title notice shows up as so), and not http://mysite.com/checkout/login.html (the page I wait to load and call `next` on).

**Comment by hollsk** [comment]
Oh, hrm. The documentation _does_ say that, very clearly. Perhaps I'm wrong about having to set it up beforehand (wouldn't be the first time ;) ) 

In any case, I've created my own bare-bones HTML site and Pa11y JS to simulate your interactions, and I don't get the same results as you with my slightly simplified code. One thing I did in my Pa11y JS was to add a couple of helpers to get more information out of Phantom, and if I add the same helpers to your code, HTML Code Sniffer seems to throw an `undefined` error on something, so perhaps there's something about the syntax that Phantom doesn't like, so it stops evaluating. I can't see what it could be, though! 

Here's my Pa11y JS if you want to give this a try against your application instead: 

```
var test = pa11y({

    beforeScript: function(page, options, next) {

        // Phantom helpers
        page.onConsoleMessage = function(msg) {
            // this allows you to use console.log() inside page.evaluate() to log to your NodeJS console
            console.log(msg);
        };
        page.onError = function(msg, trace) {
          // this will log an error to your NodeJS console if any JS errors occur on the page being tested
          var msgStack = ['ERROR: ' + msg];
          if (trace && trace.length) {
            msgStack.push('TRACE:');
            trace.forEach(function(t) {
              msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function +'")' : ''));
            });
          }
          console.error(msgStack.join('\n'));
        }; 

        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    // Once the changes have taken place continue with Pa11y testing
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        // begin the evaluations.... 
        page.evaluate(function() {

            // add the product to the cart
            var addToCartButton = document.getElementById('addToCartButton');
            var cartCount = document.getElementById('cartCount');
            addToCartButton.click();
            console.log('add the item to the cart');

        }, waitUntil(function() {
              
              // wait until first thing happens...
              return cartCount.innerHTML === '1';

            }, 20, function() {
                page.evaluate(function() {

                    console.log('cart count: '+cartCount.innerHTML);
                    console.log('redirect to login page');
                    window.location.href = 'http://mysite.com/checkout/login.html';

                }, waitUntil(function() {
                        
                        // wait until second thing happens...
                        return window.location.href === 'http://mysite.com/checkout/login.html';

                    }, 20, function() {
                        page.evaluate(function() {

                            console.log('log the user in');
                            var user = document.querySelector('#username');
                            var password = document.querySelector('#password');
                            var submit = document.querySelector('#submit');

                            user.value = 'exampleUser';
                            password.value = 'password1234';
                            submit.click();

                        }, waitUntil(function() {

                                /// wait until third thing happens...
                                return window.location.href === 'http://mysite.com/checkout/delivery.html';

                            }, 20, next)
                        ) 
                    })
                )
            })
        );     

    } // end beforeScript

}); // end pa11y config
```

If does work (fingers crossed) then maybe your fresher eyes will be able to spot the difference that I couldn't. If it doesn't work, then at least the helpers will let us debug more easily.

**Comment by hollsk** [comment]
We now recommend using `actions` for situations like this 😄 

https://github.com/pa11y/pa11y#actions
