### ISSUE TITLE
Add complex interactions to Pa11y examples/cookbook

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y#200]
We've already got a [beforeScript example](https://github.com/pa11y/pa11y/tree/master/example/before-script) but it's pretty simple and means that people end up in callback hell if they follow it while doing something complicated (e.g #199 ). Would be good to see an expanded example that uses promises instead. 

This isn't a Pa11y problem, it's a javascript architecture / design pattern problem, but it shouldn't take long to build an example and it'd be useful to point people towards when things start getting hairy.

**Comment by rowanmanning** [comment]
@hollsk reckon we can close this now that we have actions?

**Comment by hollsk** [comment]
Yeah, no real need for it now 👍
