### ISSUE TITLE
Something squirly is going on with local files

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y#201]
## Summary: 

Local files loaded with the file: protocol don't seem to be getting read by Phantom, even though Phantom reports success at opening them(?!)

As a result, all pages that are tested in this way return the same two errors, "no title" and "no lang". 

I've also tested with Phantom's screenshotter and that seems to confirm that there's nothing there for it to read, even though the opening of the file hasn't failed. 

## To replicate:

`pa11y file:./local-file.html --config config.js`

local-file.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Test Local files</title>
</head>
<body style="background:#fff">
		<!-- Duplicate ID -->
		<p id="para">foo</p>
		<p id="para">bar</p>

		<form action="">
			<!-- No label -->
			<input id="input" name="input" value="" />
			<!-- No submit -->
		</form>
	</div>
</body>
</html>
```

(note: has title, has html lang, has other things wrong)

config.js:
```
'use strict';
var pa11y = require('../..');
var test = pa11y({
  log: {
    debug: console.log.bind(console),
    error: console.error.bind(console),
    info: console.log.bind(console)
  },
  beforeScript: function(page, options, next) {

    var title = page.evaluate(function() {
      return document.title;
    });
    console.log('page title: '+ title); // should log 'page title: Test Local Files'

    page.render('screenshot.png'); // should render a screenshot of the page

    next(); 
  }

});

test.run('file://./localfile.html', function(error, result) {
  if (error) {
    return console.error(error.message);
  }
  console.log(result);
});
```

Console output:
```
PhantomJS browser created
 > PhantomJS browser created
PhantomJS page created
Opening "file://./hide-elements.html" in PhantomJS
Opened "file://./hide-elements.html" in PhantomJS
Testing the page "file://./hide-elements.html"
Running beforeScript
page title: undefined
 > Testing the page "http://file:./hide-elements.html"

Results for file:./hide-elements.html:

 • Error: A title should be provided for the document, using a non-empty title element in the head section.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_2.H25.1.NoTitleEl
   ├── html > head
   └── <head></head>

 • Error: The html element should have a lang or xml:lang attribute which describes the language of the document.
   ├── WCAG2AA.Principle3.Guideline3_1.3_1_1.H57.2
   ├── html
   └── <html><head></head><body></body></html>

2 Errors
0 Warnings
0 Notices
```

The `console.log('page title: ' + title);` returns `undefined` (as does `document`, if that's logged instead). You can see in the second error in the output that the whole HTML doc is missing. 

What could be going on? The file exists and Phantom happily runs `state.page.open` on it, but the contents seem to be vanishing into the ether. Has something changed? Am I running the tests against local files incorrectly? :thinking: :thinking: :thinking: 

(we should probably also add some unit tests for this if we figure out what's going on)

**Comment by hollsk** [comment]
This user on Reddit appears to have the same problem (6 months ago, no solution found there either) https://www.reddit.com/r/javascript/comments/4jbnui/phantomjs_rendering_from_local_file/

**Comment by joseluisbolos** [comment]
It looks like phantomjs (and therefore pa11y) will only accept full-path URIs as per the [File URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme) specs, which takes the form of:

```
file://fully_qualified_domain_name/path
```

If the fully qualified domain name is localhost, this can be omitted. However, the single slash between host and path is part of the syntax of URLs and cannot be omitted.

I can verify that this works as expected:
```
pa11y file:///path/to/local-file.html --config config.js
```

As action points I propose:

* Modify the [README.md] so we clarify that in the following example, the full path must be used:
`pa11y file:///path/to/your/file.html`
* For consistency, I would also suggest to change all the other examples so they use URLs instead, so
`pa11y nature.com` becomes `pa11y http://www.nature.com`. We know that pa11y will happily accept the former but I think it's less error-prone anyway.

Does it sound good?

**Comment by hollsk** [comment]
OMG. Good spot. Agree that these updates to the docs will help.

We could probably also add some error handling so that Pa11y will notify and exit if it encounters a faulty path. Because Phantom doesn't throw any kind of error, it's essentially a silent failure state.

@Alicole - does this help with your local vs URL problem earlier?

**Comment by joseluisbolos** [comment]
Agreed on adding some error handling. Not sure how to do it though without using... regexes! :scream:

**Comment by hollsk** [comment]
NO REGEX FOR YOU!

**Comment by Alicole** [comment]
@hollsk -- sounds goods -- at least prevent confusion in terms of the user.

As you say if the underlying library does not provide any appropriate error handling, anything added for Pa11y would be beneficial and a definite improvement in terms of UX.

A potential +1 for the team, is it worth contributing this back to Phantom considering the number of projects now that depend on it as a headless web server.
