### ISSUE TITLE
Detect if a local filepath passed to Pa11y is relative, throw error if this is the case

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y#203]
See #201 for details.

PhantomJS will accept a local file with a relative path and return a "success" status on `page.open`, but is unable to read the file. No errors are thrown when this happens, so Pa11y continues to run on a blank page, which gives unexpected and confusing results. 

Node v0.11.2 and up have a [path.isAbsolute()](https://nodejs.org/api/path.html#path_path_isabsolute_path) method that could be of use.

**Comment by pamo** [comment]
What about using [path.resolve()](https://nodejs.org/api/path.html#path_path_resolve_paths) to get the absolute path using the input and `__dirname`?

**Comment by usmanatron** [comment]
Im going to have a go at this!

**Comment by pamo** [comment]
@usamantron I started taking a look but got lost in a few rabbit holes trying to find where the path is resolved. Seems like truffler takes care of that though.

**Comment by rowanmanning** [comment]
I _think_ this is a [Truffler](https://github.com/springernature/truffler) issue, but haven't had time to verify. Either way it'd probably benefit from this code.

**Comment by rowanmanning** [comment]
We've fixed this in Pa11y 5.x, which properly resolves local paths. So I'm gonna close this
