### ISSUE TITLE
Pa11y not working

### ISSUE THREAD

**Issue by SimitTomar** [pa11y/pa11y#206]
Hi,

I installed Pa11y but on running my scripts, I am not getting any Pa11y results, rather getting the below error:

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.buildMarkdown [as process] (D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\reporter\m
    at D:\Llyods\AutomationFramework\pao-savings-cwa\tests\acceptance\wdio\features\step_definitions\Accessibility-St
    at D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\node_modules\truffler\lib\truffler.js:182:11
    at D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\node_modules\async\lib\async.js:697:13
    at D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\node_modules\async\lib\async.js:52:16
    at D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\node_modules\async\lib\async.js:267:21
    at D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\node_modules\async\lib\async.js:44:16
    at D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\node_modules\async\lib\async.js:694:17
    at D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\node_modules\async\lib\async.js:173:37
    at D:\Llyods\AutomationFramework\pao-savings-cwa\node_modules\pa11y\node_modules\truffler\lib\truffler.js:102:13

Configuration:
Pa11y: 4.01
Node: 4.2.2
Phantomjs2: 2.2.0
Windows 7

**Comment by joseluisbolos** [comment]
Hi @SimitTomar,

Welcome to Pa11y! Thanks for creating this issue.

Do you think you could be able to provide some more details - like a simplified version of the scripts that you're running that triggers this behaviour?

The error that you show is not very descriptive, but it looks like it could be a problem with your code. It's impossible for us to tell without seeing it. If you can show us some code we could try to replicate it on our side.

**Comment by SimitTomar** [comment]
Hi joseluisbolos,

I actually didn't make any changes in my code and today it started working on my local machine (Not sure if it was because of slow response). However I am still getting the same error on my CI setup which is a Linux Server and the execution happens on Saucelabs. 

This is the code that I have:

             var test = pa11y({
                 allowedStandards: [accessibility_standard, 'Custom Standard'],
                 ignore: ['notice', '', 'warning', ''],
                 wait: 10000
             });

             if(run_pa11y === true){

                 //Create a promise for Pa11y execution
                 pr_pa11y = new Promise(function (resolve, reject) {

                     //Run Pa11y on Test URL
                     test.run(absurl, function (error, results) {

                         console.log("\n" + "RUNNING Pa11y ACCESSIBILITY TESTING with \"" + accessibility_standard + "\" Standard on page \"" + page + "\"" + "\n");

                         //Create Pa11y Report
                         pa11y_report = Reporter.process(results, absurl);
                         pa11y_report_json = Reporter_json.process(results, absurl);
                         pa11y_err_msg = '';

                         for (var i = 0; i < pa11y_report_json.length; i++) {
                             tmp_json_obj = pa11y_report_json[i];
                             tmp_msg = '';

                             for (var key in tmp_json_obj) {
                                 //Loop through Json attributes & capture Errors & their descriptions
                                 if (tmp_json_obj.hasOwnProperty(key)) {
                                     attrName = key;
                                     attrValue = tmp_json_obj[key];

                                     //Temp store message value of each attribute
                                     if (attrName === "message") {
                                         tmp_msg = attrValue;
                                     }

                                     if ((attrName === "type") && (attrValue === "error")) {
                                         count++;
                                         if (pa11y_err_msg === '') {
                                             pa11y_err_msg = "\t Pa11Y Error" + count + ": " + tmp_msg;
                                         } else {
                                             pa11y_err_msg = pa11y_err_msg + "\n\t Pa11Y Error" + count + ": " + tmp_msg;
                                         }
                                     }
                                 }
                             }
                         }

                         //Get error count from Pa11y run
                         errors = pa11y_report.match(/\d+ Errors/g);
                         errors_pa11y = errors[0].replace(' Errors', '');

                         //Get Warnings Count from Pa11y run
                         warnings = pa11y_report.match(/\d+ Warnings/g);
                         warning_count = warnings[0].replace(' Warnings', '');

                         //Get Notices Count from Pa11y run
                         notices = pa11y_report.match(/\d+ Notices/g);
                         notice_count = notices[0].replace(' Notices', '');

                         resolve(results);
                     })
                 });

                 pr_pa11y.catch(function(err){
                     console.log('\n Caught Error in Pa11y Run: \n' + err);
                 });

             } else {
                 //Create a dummy promise for Pa11y execution so that FireEyes execution can continue
                 console.log('\n Skipped Pa11y Execution for Dynamic Page Test\n');
                 errors_pa11y = 0;
                 pa11y_report = 'SKIPPED';
                 pr_pa11y = new Promise(function (resolve, reject) {
                     resolve();
                 })
             }


Should it not work on Saucelabs the way it is working on my Local Machine or Do I need any specific setup for it to run ?

**Comment by joseluisbolos** [comment]
Thanks, I think that helps.

We've not that familiar with SauceLabs, as we're not using it ourselves, but I'm not sure that what you are trying to do could work.

The way that pa11y works (be it the command-line pa11y, or your own pa11y-based node app) is by firing up a headless phantomjs instance, load a website, and then using phantom's API to inject the [HTML_CodeSniffer/](http://squizlabs.github.io/HTML_CodeSniffer/) bookmarklet and capture its results.

My understanding, from looking at [SauceLabs Node.js examples](https://wiki.saucelabs.com/display/DOCS/Node.js+Test+Setup+Example), is that saucelabs works in a similar way. You use a node app to talk to selenium's API, load a website, and interact with it.

Both tools seem to be doing similar things, namely firing a (headless) browser and interacting with it, so I don't think you could be able to use pa11y with it, unless you heavily modify pa11y in order to remove the dependency on phantomjs and use selenium instead.

What you can do is to inject HTML_CodeSniffer yourself. I believe this should be possible and it may be similar to what you're doing with FireEyes. If you inject CodeSniffer and capture the results yourself then you don't need pa11y at all, as you would be replicating what pa11y does.

Please let me know if I got the wrong idea - There seems to be quite a few different products in SauceLabs' website so I'm not sure if this is what you are actually trying to achieve.

**Comment by SimitTomar** [comment]
Hi @joseluisbolos,

Thanks for the detailed explanation. I think that makes sense, this means that it has actually nothing to do with Saucelabs since its invoking its own browser (phantomjs) on the machine from where the script is executed, Linux Server in my case.

I did a simple pa11y 'My_Site_Url' on the Linux m/c and got the following error:

Welcome to Pa11y

 > PhantomJS browser created
 > Error: HeadlessError: Phantom Process died
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/node-phantom-simple/node-phantom-simple.js:659:12)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)


On running the same URL through my code after adding the 'log' object, this is what I get in the console:

PhantomJS browser created
PhantomJS page created
Opening "My_Site_Url" in PhantomJS
PhantomJS page closed
PhantomJS browser exited


And then finally the error:

Cannot read property 'length' of undefined
running firefox (v44) on Windows 7
TypeError: Cannot read property 'length' of undefined
    at Object.buildMarkdown [as process] (/apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/reporter/markdown.js:34:13)
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/tests/acceptance/wdio/features/step_definitions/Accessibility-Standard-Check.js:83:50
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/node_modules/truffler/lib/truffler.js:182:11
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/node_modules/async/lib/async.js:697:13
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/node_modules/async/lib/async.js:52:16
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/node_modules/async/lib/async.js:267:21
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/node_modules/async/lib/async.js:44:16
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/node_modules/async/lib/async.js:694:17
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/node_modules/async/lib/async.js:173:37
    at /apps/paoworkspace/workspace/pao-savings-cwa-feature-bdd/node_modules/pa11y/node_modules/truffler/lib/truffler.js:146:13


The same passes on my local Windows 7 machine, Really don't know what's wrong here :(

Thanks
Simit

**Comment by SimitTomar** [comment]
Hi joseluisbolos, 

I noticed that on my Jenkins server, my site is taking a bit long but pa11y is not waiting for the response beyond 30 seconds no matter what time I set in timeout. It gets timed out after 30 secs and since by that time the response was empty, it throws the aforementioned error. Not sure why the timeout is not increasing beyond 30secs. Can this be an issue on phantomjs. I am using phantomjs v2.1.7, also tried phantomjs2 v 2.2.0 but no success :( any inputs would be much appreciated.

Thanks
Simit

**Comment by rowanmanning** [comment]
Hi, I'm gonna close this issue for now, apologies for not getting back to you sooner but this issue seems _very_ specific to your setup.

If you're still encountering the same problem then we can take a look but it's difficult to debug. It looks like on SauceLabs you're possibly attempting to run Pa11y within a Firefox VM:

```
running firefox (v44) on Windows 7
TypeError: Cannot read property 'length' of undefined
```

This will never work as Pa11y can only run in a Node.js environment.
