### ISSUE TITLE
Add a troubleshooting document

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y#210]
We already have a troubleshooting doc for the Dashboard, but we need one for Pa11y core too:

https://github.com/pa11y/dashboard/blob/master/TROUBLESHOOTING.md

**Comment by pamo** [comment]
Do you have some common problems with solutions for core or would this just be a placeholder?

**Comment by hollsk** [comment]
Yes! I'm glad you asked :D 

The most common issue in Pa11y core seems to be when it's run against an AngularJS app before the appropriate view has been loaded, so Pa11y tests the wrong page. Here's an issue where I suggest a resolution to that problem (the "more robust" suggestion, not the quick and dirty one - I've also added links to the relevant Phantom and Angular documentation in my next comment after that): https://github.com/pa11y/pa11y/issues/174#issuecomment-231029925

The second most common issue is "Pa11y gives different results to the HTML Codesniffer bookmarklet". There can be lots of different reasons for that and we'll never cover all of them, but some of the most common we've seen are: 
- the page is being tested before it's fully loaded, in which case you can add a "wait", or wait for some event to fire (like in the Angular example);
- the HTML Codesniffer bookmarklet parses and tests the contents of iframes, but due to the way PhantomJS works, we aren't currently able to see inside iframes for testing - the HTML Codesniffer command line tool has the same limitation. We don't have a solution to this except to test the iframed sources directly.

Those are the only common problems in core I think of, but should be enough to go on :-)

**Comment by rowanmanning** [comment]
There's also some stuff in the [Common Questions](https://github.com/pa11y/pa11y#common-questions) section of the README which could be moved into a troubleshooting doc.

**Comment by joseluisbolos** [comment]
There are a few of pa11y-related questions on [StackOverflow](http://stackoverflow.com/search?q=pa11y). Even if they are old, it may be worth having a look and see if there are any of those that could be avoided by improving the docs.
