### ISSUE TITLE
Test with PhantomJS 2.5

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#225]
[PhantomJS 2.5 beta](https://groups.google.com/forum/#!topic/phantomjs/AefOuwkgBh0) has been released, it'd be good to test Pa11y with it before we go live. For this I'd recommend using the PhantomJS path param on the command line and pointing to the new version:

```
pa11y --phantomjs <path> example.com
```

**Comment by rowanmanning** [comment]
OK currently this seems like a no-go, but it may be due to [node-phantom-simple](https://github.com/baudehlo/node-phantom-simple).

Here's the error stack I get when running with PhantomJS 2.5 beta:

```
Welcome to Pa11y

 > Error: HeadlessError: Phantom immediately exited with: null
    at ChildProcess.immediateExit (~/.nvm/versions/node/v6.7.0/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:153:23)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by nickdunn** [comment]
With headless Chrome is it worth continuing the phantom route?

https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE

**Comment by hollsk** [comment]
Probably not 🙂 

Currently Pa11y is pretty tightly coupled to Phantom, and we've been talking about changing things to make it less dependent, so people can choose different headless browsers. But it'd be a major rewrite, so although we all agreed it was a great idea, we hadn't really looked into it seriously. 

Phantom 2.1 isn't going anywhere, and there's still a pretty healthy dev community around it, so we shouldn't worry too much about that, but I don't think there's any benefit to further testing of 2.5 (ergo we can close this issue). 

Mid to long term, we should think about the uncoupling of Pa11y from Phantom. Our focus for the moment is on the replacement for Pa11y Dashboard ([Sidekick](https://github.com/pa11y/sidekick)), so this could be our next big project.

**Comment by nickdunn** [comment]
Makes sense, thanks!

**Comment by rowanmanning** [comment]
If a 2.5 stable release appears then I'd still like to get it working in the 4.x branch of Pa11y – the better ES6 support would allow us to start using newer browser features in preparation for a move to something different (e.g. Headless Chrome).

I'll keep an eye on PhantomJS and reopen this if 2.5 stabilises.
