### ISSUE TITLE
Pa11y example failing due to Phantom process died error

### ISSUE THREAD

**Issue by SriGitHubSri** [pa11y/pa11y#237]
Hi Team,
I am new to pa11y and have just learned and started trying out the example pa11y index.js file under the pa11y(github repo)/example/basic folder in a jenkins job environment as Execute shell command . The command mentioned to run the index.js file is **node example/basic** .The below is the output.
PhantomJS browser created
PhantomJS page created
Opening "http://nature.com" in PhantomJS
PhantomJS page closed
PhantomJS browser exited
**Phantom Process died**

Because of this, I am not able to implement pa11y. Checked the previous issues but wasnt able to find a solution.
Could anyone please help and suggest in resolving this issue?
Thanks in advance!

**Comment by edisch** [comment]
@SriGitHubSri +1

**Comment by rowanmanning** [comment]
Hi @SriGitHubSri: that's odd, and there's really not much to go on. As far as I know we haven't seen this issue before.

Could you send me details of your machine? OS/Version, Node.js version, PhantomJS version and I'll see what I can do.

Also it may be worth trying to run something simple with _just_ [PhantomJS](http://phantomjs.org/) to see if that's working for you.

**Comment by rowanmanning** [comment]
I'm gonna close this and assume you managed to get things working. Feel free to reopen if you're still having issues and you can provide your machine details :)

**Comment by othree** [comment]
I experienced this issue too.
But on dashboard server log.

![2017-06-05 3 19 34](https://cloud.githubusercontent.com/assets/16474/26774347/6c429ce8-4a02-11e7-87a6-32494063955d.png)

I think this is a timeout handling issue.
I have two tracker on my page (GA, Metrica).
And if I use `phantomjs` to open the page.

```javascript
var uri = 'http://www.360totalsecurity.com.local/en/';
var page = require('webpage').create();

page.open(uri, function(status) {
  console.log("Status: " + status);
  phantom.exit();
});
```

Execute by:

```sh
/node_modules/phantomjs-prebuilt/bin/phantomjs --debug=true test.js
```

It will load very long (more than 1 minute).
After open debug mode, I found it is waiting a request until its timeout.

    https://www.google.com.tw/pagead/ga-audiences?....

Error message:

![2017-06-05 3 20 52](https://cloud.githubusercontent.com/assets/16474/26774414/bcb8aae6-4a02-11e7-971e-27b13fa3974a.png)

In plain text:

2017-06-05T15:10:56 [DEBUG] Network - Resource request error: QNetworkReply::NetworkError(OperationCanceledError) ( "Operation canceled" ) URL: "https://mc.yandex.ru/webvisor/28359526?wv-type=1&page-url=http%3A%2F%2Fwww.360totalsecurity.com.local%2Fen%2F&wv-hit=165761017&browser-info=z%3A480%3Ai%3A20170605150958%3Apct%3Atext%2Fhtml%3Bcharset%3Dutf-8%3Ast%3A1496646657%3Au%3A1496646598975282641"

This request is a redirection from a GA collect request.
But this request work well on a normal Chrome.
Not sure why Google didn't answer this request in PhantomJS.

I try to modify the value of timeout and wait to 300000(5mins).
Bot non of them works.
I think *timeout* should able to fix this.
But it didn't.

After I remove this two trackers.
Everything works fine.

On PhantomJS, it responsed very quick as expected.
On pa11y dashboard, it works well now. And I can get results now.


There might have 2 issues here:

1. pa11y can't handle this timeout issue now (tried on pa11y cli)
2. phantomjs `open` callback always need to wait everything ready. Even if I already use `async` to load `analytic.js`

**Comment by kaelig** [comment]
I think I'm having the same issue with pa11y-cli running under a circleci 2.0 image (`circleci/node:8.4.0-browsers`).

The first URL in my `.pa11yci` file gets a report, while the rest fails.

```
[init] listening on 0.0.0.0:40154
yarn run v0.27.5
$ pa11y-ci
Running Pa11y on 3 URLs:
{"datetime":"2017-09-12T06:56:18.271Z","http_method":"GET","http_response":"OK","http_status":200,"ip":"127.0.0.1","payload":"\nStarted GET \"/\" for 127.0.0.1 at 2017-09-12T06:56:18.163Z\n  Parameters: {}\nCompleted 200 OK in 109ms","request_id":"0f721224-4659-419b-adc2-cbcb9f295766","response_time":"109ms","uri":"/","user_agent":"pa11y/4.12.2 (truffler/3.1.0)"}
 > http://0.0.0.0:40154/ - 1 errors
 > http://0.0.0.0:40154/principles/principles - Failed to run
 > http://0.0.0.0:40154/resources/resources - Failed to run

Errors in http://0.0.0.0:40154/:

 • This button element does not have a name available to an accessibility API.
   Valid names are: title attribute, element content.

   (#navigation > button)

   <button type="button" class="_3Exjf" aria-controls="PageNav"
   aria-expanded="false" data-reactid="191"><div class="_27pSt"
   data-reacti...</button>

Errors in http://0.0.0.0:40154/principles/principles:

 • Error: Phantom Process died

Errors in http://0.0.0.0:40154/resources/resources:

 • Error: Error opening url "http://0.0.0.0:40154/resources/resources" : Operation
   canceled

✘ 0/3 URLs passed
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by rowanmanning** [comment]
Hi @kaelig, yours sounds like it _could_ be a memory issue, so possibly not related to this. Could you try adding `"concurrency": 1` to your `.pa11yci` file?

**Comment by kaelig** [comment]
Thanks for looking into it.

I just tried setting `"concurrency": 1` and got the same issue again. They fail in a slightly different order (the 2nd URL says "Operation canceled" and the 3rd one says "Phantom Process died"):

```
#!/bin/bash -eo pipefail
yarn start & sleep 10; yarn run test:pa11y-ci;
yarn start v0.27.5
$ node build/server/main.js
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
[init] listening on 0.0.0.0:40154
yarn run v0.27.5
$ pa11y-ci --config .pa11yci.ci
Running Pa11y on 3 URLs:
{"datetime":"2017-09-12T14:25:50.297Z","http_method":"GET","http_response":"OK","http_status":200,"ip":"127.0.0.1","payload":"\nStarted GET \"/\" for 127.0.0.1 at 2017-09-12T14:25:50.227Z\n  Parameters: {}\nCompleted 200 OK in 71ms","request_id":"93240eb7-a413-46e7-a70c-ac63bd990cf5","response_time":"71ms","uri":"/","user_agent":"pa11y/4.12.2 (truffler/3.1.0)"}
 > http://0.0.0.0:40154/ - 1 errors
 > http://0.0.0.0:40154/principles/principles - Failed to run
 > http://0.0.0.0:40154/resources/resources - Failed to run

Errors in http://0.0.0.0:40154/:

 • This button element does not have a name available to an accessibility API.
   Valid names are: title attribute, element content.

   (#navigation > button)

   <button type="button" class="_3Exjf" aria-controls="PageNav"
   aria-expanded="false" data-reactid="191"><div class="_27pSt"
   data-reacti...</button>

Errors in http://0.0.0.0:40154/principles/principles:

 • Error: Error opening url "http://0.0.0.0:40154/principles/principles" : Operation
   canceled

Errors in http://0.0.0.0:40154/resources/resources:

 • Error: Phantom Process died

✘ 0/3 URLs passed
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

Here's my config file in case it helps:
```
{
  "concurrency": 1,
  "urls": [
    "http://0.0.0.0:40154/",
    "http://0.0.0.0:40154/principles/principles",
    "http://0.0.0.0:40154/resources/resources"
  ]
}
```

**Comment by rowanmanning** [comment]
Well this is odd :) I'll look into properly. Could I have the following info please?

- The version of Node.js you're running on (I think it's 8.4.0 based on logs)
- The version of PhantomJS you're using
- If possible, your `.pa11yci` file (perhaps anonymised)

We're using Pa11y CI extensively in our CircleCI builds at FT, so I'm a little confused by this. We _might_ not be using CircleCI 2.0 with it yet though

**Comment by kaelig** [comment]
Thanks for asking.

- The image I’m using is `circleci/node:8.4.0-browsers`. I’m not certain of the version of PhantomJS but Node.js is definitely 8.4.0 :)
- The pa11y config file is in my previous comment. 

I wish our repo was open source so you could see it for yourself. It could be an issue due to CircleCI though.

**Comment by kaelig** [comment]
@rowanmanning I updated my comment with the latest information I have on the build environment. Hope it helps.

**Comment by mjoyce91** [comment]
Setting `"concurrency": 1` fixed this for us, using CircleCI.
