### ISSUE TITLE
Allow custom sniffs

### ISSUE THREAD

**Issue by edisch** [pa11y/pa11y#239]
It would be awesome if we could implement our own custom sniffs on top of the existing guidelines. I know HTML_CS has "support" for this but I can't find any documentation on how to do it.

**ps: love pa11y**

**Comment by rowanmanning** [comment]
Yes their documentation is a little lacking, but unfortunately it's the only way to do this at the moment. If we ever move away from HTMLCS then we'd definitely like to enable this, but for now I'm afraid I have to close 😔

It may be worth petitioning the maintainers of HTMLCS to write up how to add new sniffs if that would be helpful.

**Comment by rowanmanning** [comment]
Also thanks for the feedback and glad you're enjoying Pa11y :)
