### ISSUE TITLE
Document all of the rules you can ignore

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#24]
This probably involves the joyous task of trawling through [HTML CodeSniffer](https://github.com/squizlabs/HTML_CodeSniffer) and grabbing each of the rules (code plus message).

At the moment you have to copy rules from the console output which is quite inefficient, and doesn't allow you to ignore rules that you haven't come across yet.

**Comment by mjskrzypecka** [comment]
is there any working link for that?
