### ISSUE TITLE
Update all example URLs

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#252]
Currently the codebase is littered with references to nature.com, which is a hangover from when Pa11y was predominantly worked on at Nature Publishing Group. Recently this seemed to cause a little confusion and it probably makes sense to update.

I'm suggesting changing all references from `nature.com` to `pa11y.org`. There are references in the README, the example files, and the integration tests.

**Comment by TheJaredWilcurt** [comment]
For instances of documentation this could be confusing. For example, if someone doesn't understand the concept of a "variable" in programming, showing them this example would not give them any meaningful information and would just confuse them:

```
var Var = 'var';
```

where as something like this is easier to understand and eliminates confusion:

```
var myAge = 12;
```

For documentation, any case where we are using `nature.com` or `pa11y.org` as just a generic placeholder for any website, it should be changed to `website.com` (or something similar), as that is very clear to the user that it is a placeholder URL.

**Comment by hollsk** [comment]
I'm with @TheJaredWilcurt - I guess we've become used to using real domain names in our documentation because we normally write for an internal audience. 

`example.com` is a pretty well-established domain name, that goes to a real website, and that [clearly states](http://example.com/) it's illustrative. I reckon we should switch to that instead.

**Comment by rowanmanning** [comment]
Sounds good to me, I'm convinced :)

**Comment by ian-bartholomew** [comment]
If no one is working on this, I'll take a swing at this one

**Comment by rowanmanning** [comment]
@ian-bartholomew: feel free!

**Comment by hollsk** [comment]
Fixed by @ian-bartholomew 👍
