### ISSUE TITLE
Use the update-notifier package

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#254]
I think we should try using the [update-notifier package](https://www.npmjs.com/package/update-notifier) to let people know when the command-line interface is out of date. It's used by thousands of other packages and should help us keep users up to date. See also https://github.com/pa11y/ci/issues/21

**Comment by andygnewman** [comment]
Have submitted a PR for review for this issue https://github.com/pa11y/pa11y/pull/340

**Comment by josebolos** [comment]
Seeing as most of Pa11y usage comes from CI environments we've decided against including this feature. We release new versions not that often so hopefully this won't be much of an issue ;)
