### ISSUE TITLE
MultiLang support

### ISSUE THREAD

**Issue by foxpcteam** [pa11y/pa11y#259]
Hi,
I want to translate the "message" to another lang.
for example:
"Check that the title element describes the document."

what is the best way to do it?

**Comment by hollsk** [comment]
Hi @foxpcteam - thaanks for using Pa11y! 

We get the ruleset messages directly from [HTML_Codesniffer](https://github.com/squizlabs/HTML_CodeSniffer). You can try asking on that repo if they have any plans for i18n - if it's implemented there, then we can have it here 🙂

**Comment by hollsk** [comment]
An issue for this now exists here: https://github.com/squizlabs/HTML_CodeSniffer/issues/190 

I've subscribed to the issue, but I'm add a link in here in case anybody else wants to follow it :-)

**Comment by rowanmanning** [comment]
I think we should close this at the moment as something we can't currently implement. We can reopen if/when there's a response on HTML CodeSniffer
