### ISSUE TITLE
How get output in web page?

### ISSUE THREAD

**Issue by foxpcteam** [pa11y/pa11y#260]
Hi,

i want to have the same output in my website as in terminal

so if someone enters example.com:8000 it will run the node app.js

My code is:
```
'use strict';

var pa11y = require();

// Create a test instance with some default options
var test = pa11y({

    // Log what's happening to the console
    log: {
        debug: console.log.bind(console),
        error: console.error.bind(console),
        info: console.log.bind(console)
    }

});

test.run('example.com', function(error, result) {
    if (error) {
        return console.error(error.message);
    }

    console.log(result);
});
```

 i have tried to use `expressjs`

```
var express = require('express');
var app = express();

app.get('/', function(req, res){
    res.send("Hello world!");
    test.run('example.com', function(error, result) {
    if (error) {
        return console.error(error.message);
    }

    console.log(JSON.stringify(result));
});
});
```

"Hello word" is working fine.

and all what i have tried to print the output from the  `test.run('example.com', function(error, result) { `without any success.

what i need to do to make this work with `expressjs `or any other  way?

**Comment by hollsk** [comment]
Hey @foxpcteam - I haven't tested this, but are you able to assign the entire `test.run` function to a variable, and then return the results to put in your `res.send` argument? e.g.

```
var express = require('express');
var app = express();

app.get('/', function(req, res){
	var resultSet = test.run('example.com', function(error, result) {
		if (error) {
			return console.error(error.message);
		}
		return JSON.stringify(result);
	});

	res.send(resultSet);
});
```

**Comment by hollsk** [comment]
I'm going to assume you've got this working and close this issue. Feel free to reopen if you still need help! 😄
