### ISSUE TITLE
Return lowest error code

### ISSUE THREAD

**Issue by tothomweb** [pa11y/pa11y#261]
When analyzing a page with, lets say, level AA all the returned errors are of the type:
> WCAG2AA.Principle1.Guideline1_1.1_1_1.H30.2

Given the fact that, for example this error is a level A error, I think it would be more useful to return the lowest error level like:
> WCAG2A.Principle1.Guideline1_1.1_1_1.H30.2

So that with just 1 scan the different levels (an so, priorities) of errors (A, AA or AAA) could be obtained.

**Comment by hollsk** [comment]
Hi @tothomweb - thanks for using Pa11y! 

Ultimately it comes down to way the rulesets are loaded. Every ruleset has its own file, and when you choose to load a particular ruleset you only get access to those specific rules, they're sandboxed from each other. 

The ruleset handling is done by [HTML_Codesniffer](https://github.com/squizlabs/HTML_CodeSniffer/issues), so you could try opening this issue over there, and see what the Squizlabs devs think about it. I'm not familiar enough with their architecture to know whether they can support this easily or not. 

Thanks again!

**Comment by tothomweb** [comment]
Great @hollsk , thanks for the fast reply!
