### ISSUE TITLE
Unable to pass basic auth 

### ISSUE THREAD

**Issue by bhattdeepak90** [pa11y/pa11y#263]
Hi Pallian's

I am not able to pass the basic auth credentials to my web page. I had installed pa11y in Linux environment, and created a config file with below settings:
pa11y({    page: {
        settings: {
            userName: 'uat2uat',
            password: '4pass@ua!'         }
    } });
then using the mentioned CLI command:      pa11y --config config.json  http://example.com
and receiving the below mentioned error: 

PhantomJS browser created
Error: Error opening url "http://example.com" : Operation canceled
    at Object.<anonymous> (/root/.nvm/versions/node/v7.9.0/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:154:18)
    at /root/.nvm/versions/node/v7.9.0/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/root/.nvm/versions/node/v7.9.0/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Refrence: https://github.com/pa11y/pa11y/blob/master/TROUBLESHOOTING.md#how-can-pa11y-log-in-if-my-sites-behind-basic-auth 
Can anyone help me here. Thanks in advanced.

Regards!
Deepak Bhatt

**Comment by joseluisbolos** [comment]
Hi Deepak,

Thanks for your interest in pa11y.

From what you tell us, it's unclear where the problem may lie. Could you please:

* Confirm that you're using basic auth, and not any other method.
* Try with a different site, one that doesn't need authentication, so we can check if we're getting the expected results, and it's a problem with the authentication, or with something else.

Thanks.

**Comment by bhattdeepak90** [comment]
Hi Jose,

Thanks for your quick response. Below are the answers you have asked for:
1. I am using only basic auth method.
2. I have tested the other sites which don't have authentication and getting the proper result as expected. Hence I think the problem lies with basic auth mechanism. Can you please guide me with the steps how to pass the basic auth.

Many Thanks!
Deepak

**Comment by bhattdeepak90** [comment]
Hi All,

I am not able to pass basic auth with pa11y. Please find the below config.js file I am using to pass basic auth credentials. I have masked the actual url in config.js. CLI command used to run pa11y:
pa11y --config config.js  http://myurl.com/
but the command is throwing me an error and I am not able to get the result. I have also done some debugging around it and found that pa11y is executing the test before setting the auth parameters.
If you pass the auth site url in the config.js file and same url in cli command pa11y will not run, but if you pass http://google.com in the cli command it will run return both the results i.e one for your auth site and other for google.com. 

Can anyone help me here

Thanks!
Deepak Bhatt

**Comment by hollsk** [comment]
Hi Deepak - I've run a quick test on a page with http auth and everything looked good there, so it seems like a system-specific problem. 

The "operation canceled" error message comes from PhantomJS, but there are lots of different reasons it could happen. One of the things that the Phantom team recommend is to add a timeout before attempting to open the page. 

Your testing suggests to me that might help here, so please try adding a `wait` to your pa11y config:

```
pa11y({
    wait: 5000
});
```

If it doesn't work we can try another way :-)

**Comment by hollsk** [comment]
I'm going to assume you managed to get this sorted, so I'll close this issue. Feel free to reopen if you're still having trouble though 😄
