### ISSUE TITLE
Unable to click a button in Actions

### ISSUE THREAD

**Issue by DineshkumarS89** [pa11y/pa11y#264]
Hi Team,

I am trying to automate automate accessibility testing using pa11y. I am using pa11y actions to navigate between pages before triggering the accessibility scan.

But i am not click/access buttons which doesn't have id.

Below the HTML code for the logout Button

button type="submit" class="c-application-kap-self-tracker__exit" data-tealium-narrative="Exit" data-reactid=".0.2.0.1.0.1.1.1">Logout</button>*/

Do access a object in actions it will be always via ID

**Comment by hollsk** [comment]
Hi Dinesh,

Thanks for using Pa11y! You should be able to use any selector you like in the action, not just an ID. We don't have anything about that in the documentation, which I'll fix. 

Try something like `click element [data-tealium-narrative="Exit"]` or `click element .c-application-kap-self-tracker__exit` and let us know if it works!
