### ISSUE TITLE
How to use with JSX?

### ISSUE THREAD

**Issue by dragGH102** [pa11y/pa11y#269]
As per the title,

since JSX (React) is basically all Javascript, how to use pa11y to test the HTML returned?

**Comment by hollsk** [comment]
Hi @dragGH102 - Pa11y spins up a PhantomJS instance to render the page, then injects HTML_Codesniffer into it and returns a report based on its findings. We don't check the underlying code itself, only what's rendered as a webpage. 

Hope this helps!

**Comment by lemoustachiste** [comment]
I'm realizing the initial question might be ambiguous to my problem, which however seems related. 

@hollsk does this mean that there is no way to test via pa11y's current implementation against the generated HTML once React code has executed? 

I tried using the -w flag to allow time but I don't think it helps, so just double checking with someone who has more experience with this tool.

Thanks

**Comment by dylanb** [comment]
@lemoustachiste you might want to check out react-axe - it is probably more appropriate for what you are trying to achieve

**Comment by andrewmee** [comment]
Hello @lemoustachiste, as @hollsk mentioned, pa11y is indeed designed to run against that generated HTML.  It doesn't know (or care) what generates that code, it just evaluates the HTML as it stands when it is executed.

The `-w` option allows you to specify a time (in milliseconds) for pa11y to wait while your application gets itself into a state to be tested.  If you're not seeing the results that you expect it might be worth checking that your app is in the state you're expecting at the url and wait time you've specified.
