### ISSUE TITLE
Error: HeadlessError: Phantom immediately exited with: 127 while running on Jenkins

### ISSUE THREAD

**Issue by mskhirwar** [pa11y/pa11y#270]
I am trying to setup a Jenkins job around pa11y with automated check-ins, but I am getting following every time:

```
 > Error: HeadlessError: Phantom immediately exited with: 127
    at ChildProcess.immediateExit (/data/jenkins/workspace/Accessibility/web/node_modules/node-phantom-simple/node-phantom-simple.js:153:23)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Does anybody knows what could be the root cause around this?

**Comment by mskhirwar** [comment]
On further debugging , I have found following log in Jenkins's log:

`./node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`

Jenkins is setup on {"os":"linux","arch":"x64"}

**Comment by josebolos** [comment]
Hi @mskhirwar 

Thanks for using pa11y. The error that you mention looks very similar to this one in the phantomjs repo: https://github.com/ariya/phantomjs/issues/10904

Could you please try installing the missing `libfontconfig` library and see if that fixes the problem for you?

Thanks!

**Comment by mskhirwar** [comment]
Thanks @josebolos for you prompt response. 

I am using Jenkins & I do not have command line access. Is there any other way to fix this issue?

**Comment by mskhirwar** [comment]
Thanks @josebolos, above mentioned issue fixed after installing 'libfontconfig' package. 👍
