### ISSUE TITLE
How to sync pa11y generated data with pa11y dashboard?

### ISSUE THREAD

**Issue by mskhirwar** [pa11y/pa11y#272]
I would like to sync the data generated by pa11y to pa11y dashboad which is getting generated by Jenkins Job on every code check-ins in the repository.

Is there any way to achieve this?

Thanks!

**Comment by rowanmanning** [comment]
Hi @mskhirwar, sorry there is currently no way to do this. The way the dashboard is architected would make it a lot of work to enable. There's no reason you couldn't write a script which accesses the dashboard database directly though.

We're intending on allowing this with [Pa11y Sidekick](https://github.com/pa11y/sidekick) though there's no timeline on when that will release yet.

**Comment by mskhirwar** [comment]
Hi @rowanmanning, no problem by the way thanks for the info.
