### ISSUE TITLE
ConcurrentTest> How to write HTML output into .html file

### ISSUE THREAD

**Issue by sagar441989** [pa11y/pa11y#275]
@rowanmanning 
I have below script is use. It generates HTML output to console. 
Could some one help me writing the output in HTML file?

```
// An example of running Pa11y on multiple URLS
// in parallel, with a configurable concurrency.
'use strict';

var async = require('async');
var pa11y = require('pa11y');

// Create a test instance with some default options
var test = pa11y({

	// Log what's happening to the console
	log: {
		debug: console.log.bind(console),
		error: console.error.bind(console),
		info: console.log.bind(console)
	}

});

// Define some URLs to test, and a concurrency
var urls = [
	'http://www.google.com/',
	'http://www.github.com/',
	'http://www.github.com/'
];
var concurrency = 2; // Run two tests at a time

// Use the async library to create a queue. This accepts a
// function to handle the URLs, and a concurrency.
// https://github.com/caolan/async
var queue = async.queue(function(url, done) {

	// The queue function will be called with each URL. We
	// can then run the pa11y test function on them and call
	// `done` when we're finished to free up the queue
	test.run(url, function(error, results) {
		if (error) {
			return console.error(error.message);
		}
		console.log(results);
		done();
	});

}, concurrency);

// Add a function that is triggered when the queue
// drains (it runs out of URLs to process)
queue.drain = function() {
	console.log('All done!');
};

// Lastly, push the URLs we wish to test onto the queue
queue.push(urls);
```

**Comment by josebolos** [comment]
Hi @sagar441989,

Thanks for using pa11y.

I'm not really getting what you are trying to achieve.

If what you want is for the command line to output the results of a test as HTML, there's already an [HTML reporter](https://github.com/pa11y/pa11y#reporters) built in:

`pa11y --reporter html https://example.com/ > output.html`

If what you want is to display the results of your tests as a website, we already have [Pa11y Dashboard](https://github.com/pa11y/dashboard) which does that and a whole lot more.

If that’s not what you are trying to achieve, could you please clarify? Bear in mind that we don’t offer a code writing service so we may not be able to help you write the code, but at least we may be able to point you in the right direction.

**Comment by sagar441989** [comment]
I am using multiple example script for executing pally against multiple URL.

**Comment by unleashalicia** [comment]
@josebolos 

Great feedback.  Maybe this should go into the README?

**Comment by josebolos** [comment]
Hi @unleashalicia 👋 

Which bit you refer to, specifically?

In addition to the READMEs for each project, we also have a [fancy website](http://pa11y.org/), but we're always looking for ways of improving the documentation!

**Comment by evandiamond** [comment]
@josebolos Was there ever a solve for this? I'd like to be able to output an `.html` file **not** using the command line. Appreciate the help in advance.
