### ISSUE TITLE
allowedStandards is not working

### ISSUE THREAD

**Issue by sagar441989** [pa11y/pa11y#277]
@rowanmanning 
I am using javascript interface and created a script for running pally with below options:
**allowedStandards: ['WCAG2A', 'Section508']**

But the output shows result for WCAG2AA too.  So I tried **standard: 'Section508'** and it worked.

Whats wrong with **allowedStandards**?

**Comment by rowanmanning** [comment]
Hi @sagar441989. Yeah `WCAG2A` is just `WCAG2AA` + `WCAG2AAA` but with some stricter rules. The message IDs reflect that. it would still be running the correct standard.

**Comment by sagar441989** [comment]
Thanks for the clarification.  Still I have below questions for you
1.  If that is the case then use of  **standard: 'WCAG2A'** should give WCAG2AA + WCAG2AAA. But this is not the case. It gives WCAG2A only.
2. allowedStandards: ['Section508']. This also gives WCAG2AA + WCAG2AAA

**Comment by sagar441989** [comment]
@hollsk @rowanmanning Do we have any updates on this?

**Comment by sagar441989** [comment]
@hollsk @rowanmanning  Shall i take it as a issue in Pa11y? I will drop the plan to use the Pa11y in my organisation.

**Comment by rowanmanning** [comment]
Hi @sagar441989, I've just looked into this further and it seems that `allowedStandards` doesn't quite work as expected. Apologies for the wait but we don't monitor closed issues quite as closely as open ones.

I'll see what I can do about fixing, but in the meantime you will need to pass some null values into `allowedStandards` – it'll take ages to explain properly but this problem exists because we deep-extend the user options. Try:

```js
var test = pa11y({
    allowedStandards: ['WCAG2A', 'Section508', null, null]
});
```

I'm interested to know what you're using this feature for, as very few people seem to need it and we'll be changing it in the next major release of Pa11y.

**Comment by sagar441989** [comment]
allowedStandards: ['WCAG2A', 'Section508', null, null] -->> Give below error 
throw new Error('Standard must be one of ' + options.allowedStandards.join(', '));

But When I changed WCAG2A to WCAG2AA it run but not giving me Section508 issues.

Note: I am comparing the Pa11y against a well known paid tool in the market. So I am testing the Pa11y features. As you said please try to fix the issue in the  next release.

**Comment by rowanmanning** [comment]
OK @sagar441989 I think you're definitely misunderstanding what `allowedStandards` is for. All it does is throws an error if you set `standard` to something different – it doesn't run Pa11y with all of the standards that you specify. I'll look at the docs and try to clarify this.

To run Pa11y with both `WCAG2A` and `Section508` you'll need to run it twice with the `standard` option set to each one. `allowedStandards` does not do this.

Regarding your note: all of the Pa11y contributors work on it in their spare time, or time that's generously donated by the companies they work for. We try to get things fixed but there's an awful lot of work involved in maintaining an open source project like this. If you're looking for a tool where you'll get one-on-one support or wish to be able to make demands on project time then I do suggest you opt for the paid one that you mention.
