### ISSUE TITLE
npm install --save pally not working

### ISSUE THREAD

**Issue by bryanrasmussen** [pa11y/pa11y#278]
On my windows 10 I do
 npm install --save pally

get the following error
PS D:\projects\NGANGA\nganga_projects\accessbility> npm install --save pally
npm ERR! code E404
npm ERR! 404 Not Found: pally@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruger\AppData\Roaming\npm-cache\_logs\2017-07-31T17_34_20_010Z-debug.log

the error log says

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'pally' ]
2 info using npm@5.0.4
3 info using node@v6.9.1
4 verbose npm-session eb86d7aa9af57db9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/pally 2115ms
8 silly fetchPackageMetaData error for pally@latest 404 Not Found: pally@latest
9 verbose stack Error: 404 Not Found: pally@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:637:20)
9 verbose stack     at tryOnImmediate (timers.js:610:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:582:5)
10 verbose cwd D:\projects\NGANGA\nganga_projects\accessbility
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "pally"
13 verbose node v6.9.1
14 verbose npm  v5.0.4
15 error code E404
16 error 404 Not Found: pally@latest
17 verbose exit [ 1, true ]

I suppose it is an npm issue that will soon be resolved, but figured I should note it here so you can see if there is more to it.

**Comment by rowanmanning** [comment]
Hi @bryanrasmussen,

Sorry for the confusion, but the `L` in Pa11y is actually a number `1`. I've spoken with npm about aliasing this as it can cause confusion, but the correct command is:

```
npm install --save pa11y
```

Hope this clears things up 🙂

**Comment by bryanrasmussen** [comment]
sorry, I've fallen for this before - normally I catch it, but I'd just
gotten done dealing with a bunch of other npm issues and jumped the gun.
