### ISSUE TITLE
Few questions before adapting Pa11y

### ISSUE THREAD

**Issue by wiprosagar123** [pa11y/pa11y#283]
@hollsk I am thinking of implementing Pa11y in my organisation. Before that I need to have clarity on below questions.
1. Does Pa11y supports XHTML?
2. Is it possible to use headless Chrome instated of PhantomJs?
3. Will there be difference is results in headless browser compared with other browsers?

**Comment by rowanmanning** [comment]
Hi @wiprosagar123 👋 most of this information is available in the docs or issues:

1. I believe so, we haven't had anybody report that it doesn't
2. Not yet, but in a future update yes (See #258)
3. Most of the time the results will be the same, except in [some edge cases](https://github.com/pa11y/pa11y/blob/master/TROUBLESHOOTING.md#why-does-pa11y-give-different-results-to-the-html-codesniffer-bookmarklet)

I hope this helps 🙂 In future there's no need to @ an individual team member, we all get notifications for issues anyway and will respond when we can
