### ISSUE TITLE
TypeError: callback.apply is not a function

### ISSUE THREAD

**Issue by sagar441989** [pa11y/pa11y#293]
I am using multiple-concurrency (with value 10) but it's not working for me . Test runs for few  pages and then everything stops with below error.
node_modules\node-phantom-simple\node-phantom-simple.js:60
        callback.apply(null, args);
                 ^

TypeError: callback.apply is not a function

**Comment by josebolos** [comment]
Hi @sagar441989 

Could you please provide a minimal config that triggers this issue, so we can try to replicate it on our side?

Thanks.

**Comment by wiprosagar123** [comment]
'use strict';
    var async = require('async');
	var pa11y = require('pa11y');
	var htmlReporter = require('pa11y/reporter/html');
	var fs = require('fs');
	var urls = getURLs();
	var targatedURL;
	var loadInProgress = false;
    var CONCURRENCY = 5;
	
	// Create a Pa11y test runner
	var pa11yTest = pa11y({
		log: {
	        debug: console.log.bind(console),
	        error: console.error.bind(console),
	        info: console.info.bind(console)
	    },
	    beforeScript: function(page, options, next) {
	        var waitUntil = function(condition, retries, waitOver) {
	            page.evaluate(condition, function(error, result) {
	           
	                if (result || retries < 1) {
	                    waitOver();
	                } else {
	                    retries -= 1;
	                    setTimeout(function() {
	                        waitUntil(condition, retries, waitOver);
	                    }, 500);
	                }
	            });
	        };
	
	  page.evaluate(function() {
	
	  // do some action  such as login
	   },function() {
	        waitUntil(function() {
	           //Wait until the login has been success and desired page is loaded
	           return window.location.href === targatedURL;
	         },20, next);
	   });
	            
	page.onLoadStarted = function() {
	    loadInProgress = true;
	    console.log('Loading started');
	};
	
	page.onLoadFinished = function() {
	    loadInProgress = false;
	    console.log('Loading finished');
	    page.evaluate(function () {
	       	 //some action but no navigation 
	      }); 
	 };
	
	page.onNavigationRequested = function(url, type, willNavigate, main) {
	  console.log('Trying to navigate to: ' + url);
	  targatedURL=willNavigate;
	  if(url.includes('some pattern')){
	    page.evaluate(function() {
	    console.log("navigated");
	   // fill up form     	   		  
	      });
		}
	}
 },
 	standard: 'WCAG2A'
	});
	
	function getURLs(){
		// read form file
	   
	   return links;
	}
	
	

var queue = async.queue(function(url, done) {
   
    pa11yTest.run(url, function(error, results) {
	        // FYI ignoring errors for now, you might want to log these somewhere
	        if (!error) {
	            var errorCount = results.filter(result => result.type === 'error').length;
	            console.log(`Finished testing ${url}: ${errorCount} errors`);
	            var html = htmlReporter.process(results, url);
				writeReportToHTML(htmlReporter.process(results,url ),process.env.resultFileName);
	        } else {
				console.log(error);
			}	
	        done();
	    });
}, CONCURRENCY);

queue.drain = function() {
    console.log('All tasks have been processed');
};

queue.push(urls, function(error) {
    console.log('Finished processing Nature Plants home');
});
	
	function writeReportToHTML(htmlText,fileName){
	
	    if (!fs.existsSync("reports/")){
	        fs.mkdirSync("reports/");
	    }
	
	    fs.appendFile("reports/" + fileName + ".html",htmlText, function(err) {
	            if(err) {
	                return console.log(err);
	            }
	            console.log("Results added to reports/" + fileName + ".html");
	        });
	}
	
	function removeExistingReports(){
	    var path="reports/"
	    if( fs.existsSync(path) ) {
	        fs.readdirSync(path).forEach(function(file,index){
	            var curPath = path + "/" + file;
	            if(fs.lstatSync(curPath).isDirectory()) { // recurse
	                deleteFolderRecursive(curPath);
	            } else { // delete file
	                fs.unlinkSync(curPath);
	            }
	        });
	        fs.rmdirSync(path);
	    }
	  }

**Comment by sagar441989** [comment]
@josebolos  Any updates on the issue? I shared the code above.

**Comment by hollsk** [comment]
FYI i've corrected the formatting of your code 🙂 

Do the tests fail after a particular number of URLs each time, or is it random?

**Comment by sagar441989** [comment]
Yes it is random

**Comment by hollsk** [comment]
Ok, thanks - local configuration shouldn't be a problem. 

I've tried to run your code, but there are a lot of custom actions and methods in there, so I can't run it without modifying it. If I modify it to get it running, it won't look like your code anymore, so won't be any use in debugging yours 😉 

Could you please give us a reduced test case that has the _minimum_ amount of code needed for us to be able to replicate the problem?

**Comment by wiprosagar123** [comment]
```
'use strict';
    var async = require('async');
	var pa11y = require('pa11y');
	var htmlReporter = require('pa11y/reporter/html');
	var fs = require('fs');
	var urls = getURLs();
	var targatedURL;
	var loadInProgress = false;
    var CONCURRENCY = 5;
	
	// Create a Pa11y test runner
	var pa11yTest = pa11y({
		log: {
	        debug: console.log.bind(console),
	        error: console.error.bind(console),
	        info: console.info.bind(console)
	    },
	    beforeScript: function(page, options, next) {
	        var waitUntil = function(condition, retries, waitOver) {
	            page.evaluate(condition, function(error, result) {
	           
	                if (result || retries < 1) {
	                    waitOver();
	                } else {
	                    retries -= 1;
	                    setTimeout(function() {
	                        waitUntil(condition, retries, waitOver);
	                    }, 500);
	                }
	            });
	        };
	
	  page.evaluate(function() {
	
	  // do some action  such as login
	   },function() {
	        waitUntil(function() {
	           //Wait until the login has been success and desired page is loaded
	           return window.location.href === targatedURL;
	         },20, next);
	   });
	            

	page.onLoadFinished = function() {
	    loadInProgress = false;
	    console.log('Loading finished');
	    page.evaluate(function () {
	       	 //some action but no navigation 
	      }); 
	 };
	
	page.onNavigationRequested = function(url, type, willNavigate, main) {
	  console.log('Trying to navigate to: ' + url);
	  targatedURL=willNavigate;
	  if(url.includes('some pattern')){
	    page.evaluate(function() {
	    console.log("navigated");
	   // fill up form     	   		  
	      });
		}
	}
 },
 	standard: 'WCAG2A'
	});
	
	function getURLs(){
		// read form file
	   
	   return links;
	}
	
	

var queue = async.queue(function(url, done) {
   
    pa11yTest.run(url, function(error, results) {
	        // FYI ignoring errors for now, you might want to log these somewhere
	        if (!error) {
	            var errorCount = results.filter(result => result.type === 'error').length;
	            console.log(`Finished testing ${url}: ${errorCount} errors`);
	    
	        } else {
				console.log(error);
			}	
	        done();
	    });
}, CONCURRENCY);

queue.drain = function() {
    console.log('All tasks have been processed');
};
queue.push(urls, function(error) {
    console.log('Finished processing Nature Plants home');
});
```

**Comment by wiprosagar123** [comment]
@hollsk The above code works when I run it using CLI with node command.  
In my case the set up is done inside a project directory and I am using ProcessBuilder to run the node command. Could this be an issue?

**Comment by rowanmanning** [comment]
@wiprosagar123: the code above doesn't run for me, I get:
```
ReferenceError: links is not defined
```

With code that a Pa11y user has written, it's extremely difficult for us to find the time to debug for you. It definitely seems like this is a problem that isn't caused by Pa11y itself. If your code runs using the `node` command on the command line, but not with `ProcessBuilder` then yes I'd assume that `ProcessBuilder` is causing the issue somehow.

**Comment by sagar441989** [comment]
@rowanmanning That's really helpful. I think I will have to check with proceesbuilder then
