### ISSUE TITLE
Overhaul the reporters interface

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#297]
Ideally in a way that means we can use Pa11y 5.x reporters in 4.x – this would mean a matching 4.x update which I'm happy to do. Reporters could possibly do with being async and having a more strict interface.

I haven't thought loads about it. Will post ideas here when I've formed them more, feel free to do that as well.

**Comment by rowanmanning** [comment]
OK here's how I think reporters should work, and this is what I've started implementing. Everything's changeable :) Some feedback would be great before I get too far.

## Reporter file

A reporter file is a JS file which implements some (or all) of the methods that Pa11y needs to function.

Reporter methods return strings, which are output to the console by the Pa11y CLI itself – it's not the job of the reporter to do this. This means that reporters are useful when you're using the JS API, not just the CLI.

Technically all of the methods are optional, they default to an empty function which means nothing will be output when they're called.

Here's an example reporter with some descriptions of the methods:

```
const reporter = module.exports = {};

// The `supports` property is used to indicate which
// versions of Pa11y the reporter supports. It should be
// valid semver. This feature will be back-ported, and the
// CLI will output a warning if there's a version mismatch
// (required)
report.supports = '>=5.0.0';

// The `begin` method is called when Pa11y starts running.
// It's used by the CLI reporter as a welcome message
// (optional)
report.begin = () => {
    return 'Welcome to Pa11y';
};

// The `results` method is the most important, and is in
// charge of turning the full Pa11y JSON structure into
// something human-readable. This now receives the full
// structure, not just the array of issues
// (required)
report.results = (results) => {
    for (const issue of results.issues) {
        console.log(issue.code);
    }
};

// The `error` method is in charge of formatting error
// messages. This is important as without it the end user
// will get no feedback if something is wrong
// (required)
report.error = (message) => {
    return message;
};

// The `info` method is in charge of outputting general
// information about the running of Pa11y, e.g. the URL
// that is being tested and the status of actions
// (optional)
report.info = (message) => {
    return message;
};

// The `debug` method is in charge of outputting extra
// debug information about the running of Pa11y, e.g.
// the current state of the page
// (optional)
report.debug = (message) => {
    return message;
};
```

## Which will be included?

I think that all reporters should be moved out of core and into modules of their own. By default we'd add the CLI, JSON, and CSV reporters but via the `package.json` rather than just included in the library.

**Comment by hollsk** [comment]
Yes, I like it a lot. 

What's happening with the markdown reporter, are we quietly dropping it or republishing as its own package?

**Comment by rowanmanning** [comment]
I think drop it for now and then reimplement as its own package later. I don't really want to commit to producing like 5 different reporters as separate packages

**Comment by hollsk** [comment]
Seems fair 😆 

I do like the layout of these new reporters (and all those lovely comments 😍 )
