### ISSUE TITLE
Move reporters out of the core library

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#299]
I think it would be good if the core library had no reporters, and they were all separate modules. It'd reduce the complexity of this codebase and hopefully encourage third parties to build their own reporters. This kind of relies on #297 being done.

## Move out

- [x] [CLI](https://github.com/pa11y/pa11y-reporter-cli)
- [x] [CSV](https://github.com/pa11y/pa11y-reporter-csv)
- [x] [JSON](https://github.com/pa11y/pa11y-reporter-json)

## Build

- [x] [HTML](https://github.com/pa11y/pa11y-reporter-html)
- [x] [TSV](https://github.com/pa11y/pa11y-reporter-tsv)

**Comment by hollsk** [comment]
I like this idea. Especially if there's some kind of common format, it should make it easier for people to write new ones. It'd mean we could do more bulky documentation around building reporters to give people a bit more confidence when working with them 👍
