### ISSUE TITLE
Allow for callbacks in 5.x

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#305]
I wonder whether we should support callbacks if a third parameter to the `pa11y` function is provided. That way we lower the barrier to entry for the JS API if a developer isn't comfortable with promises or async yet.

That would mean you can use `pa11y` in any of the following ways:

```js
// Async (currently supported)
try {
    const results = await pa11y(url, options);
    console.log(results);
} catch (error) {
    console.error(error);
}

// Promises (currently supported)
pa11y(url, options)
    .then(results => {
        console.log(results);
    })
    .catch(error => {
        console.error(error);
    });

// Callbacks (proposed)
pa11y(url, options, (error, results) => {
    if (error) {
        console.error(error);
    } else {
        console.log(results);
    }
});
```

**Comment by rajesh-frontendengineer** [comment]
Can we integrate pa11y with any of the e2e frameworks ? Like Protractor.

**Comment by rowanmanning** [comment]
Hi Rajesh, that's not relevant to this issue. Feel free to open separately, but I it's unlikely we'll add support for multiple browser engines.
