### ISSUE TITLE
wait for element not working for angular

### ISSUE THREAD

**Issue by surendraJ** [pa11y/pa11y#306]
Once I noticed wait for element....added to 4.12.1 version I immediately tried and it looks good for non angular pages but not working for single page application. I tried wait for element #id to be added / wait for element #id to be visible. 
```
'actions': [
   		        'set field #locationInput to Irving, TX',
   		        'click element #search',
   		        'wait for element #searchResultContainer to be visible'
   		  	]
```
I am always getting '`Failed action: element #searchResultContainer to be visible'` log error. 

**Here is angular code in same page** 
```
..input .....
...search button
<!-- Result Container -->
<div id="searchResultContainer " ng-show="myController.results > 0">
...other logic
</div>
```
I know searchResultContainer  always exist in dom. I am wondering is something we can do element displayed or like that 

I tried from ng-if condition and `wait for element #searchResultContainer  to be added`, even though I am not getting success 
```
<div id="searchResultContainer " ng-if="myController.results > 0">
.......
</div>
```

This new feature working for non angular pages perfectly. I am not sure If I am missing anything. Would you please check this one, as this feature gonna be very useful for lot of users. Thanks

**Comment by iandevlin** [comment]
Hi @surendraJ, if the snippet of code you have posted is exactly what is in your code, then I see that there is a space at the end of the `id` of `searchResultContainer` which means it will not be matched.

**Comment by surendraJ** [comment]
@iandevlin Sorry that was typo mistake. Actually there is no such space at the end and also I tried from css class as well. Its not working for me.

**Comment by iandevlin** [comment]
@surendraJ Ok, I just wanted to point it out, just in case.

**Comment by hollsk** [comment]
I've whipped up a reduced test case and can replicate. Not really sure what Angular is doing that's different, as it looks from the console like it's just applying a `display:none`! Maybe not, then. 

More eyes on it would be great, but here's my test case ⬇️ - should contain everything needed to replicate.

html:
```
<!DOCTYPE html>
<html class="" lang="en">
<head>
<title>reduced test case: Angular</title>
</head>
<body>
<div class="container ng-scope" ng-app="showApp" ng-controller="mainController">

    <div class="page-header text-center">
       <h1>ngShow and ngHide</h1>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <form>
          <div class="form-group">
            <label for="search">Type a number into the box</label>
            <input type="text" class="form-control" ng-model="search" id="search" name="search">
            <input type="submit" value="submit" disabled/>
          </div>
        </form>
      </div>
      
      <div class="col-xs-6">
        <img id="cat" ng-src="https://i.imgur.com/vkW3Lhe.jpg" class="img-responsive img-thumbnail ng-hide" ng-show="search > 0" src="https://i.imgur.com/vkW3Lhe.jpg">
      </div>
    </div>
    
</div>

<script src="https://code.angularjs.org/1.2.13/angular.js"></script>
<script>var showApp = angular.module('showApp', [])

.controller('mainController', function($scope) {

}); 
</script>
</body></html>
```

config:

```
{
	"actions": [
		"set field .form-control to 1",
		"wait for element #cat to be visible"
	]
}
```

result:

```
± pa11y --ignore warning --ignore notice http://0.0.0.0:8000/angular.html
Welcome to Pa11y

 > PhantomJS browser created
 > Testing the page "http://0.0.0.0:8000/angular.html"
 > Running actions
 > Error: Test function errored for "http://0.0.0.0:8000/angular.html"
Error: Failed action: element "#cat" failed to be visible
    at /Users/hollsk/repositories/git/pa11y/lib/action.js:236:20
    at /Users/hollsk/repositories/git/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/Users/hollsk/repositories/git/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by hollsk** [comment]
Also I notice that if i remove the `wait for element to become visible`, I get an error for the `ng-hide` element, anyway - as though it was visible. And if I run the html codesniffer bookmarklet, that also returns the error, as though it was never hidden in the first place.
