### ISSUE TITLE
 HTML CodeSniffer: undefined error

### ISSUE THREAD

**Issue by mncrff** [pa11y/pa11y#335]
When trying to run a pa11y scan through the command line on any site, I get the following error:

```
Error: HTML CodeSniffer: undefined is not an object (evaluating 'window.HTMLCS.process')
    at Object.<anonymous> (/usr/local/lib/node_modules/pa11y/lib/pa11y.js:71:16)
    at Object.f [as onCallback] (/usr/local/lib/node_modules/pa11y/node_modules/once/once.js:25:25)
    at /usr/local/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:636:30
    at Array.forEach (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:617:17)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Any help is appreciated!

**Comment by rowanmanning** [comment]
Hi @mncrff. Could I get the following information from you? (You can get most of this by running `pa11y --environment`):

- Pa11y version
- Node.js version
- OS Version
- An example of a page that fails

**Comment by nzambello** [comment]
Hi everyone, I'm new of pa11y.
I had the same issue and I resolved adding `-H http://squizlabs.github.io/HTML_CodeSniffer/build/HTMLCS.js` as described [here](https://github.com/pa11y/pa11y#htmlcs-string)

**Comment by mncrff** [comment]
@rowanmanning, here is the information:

Pa11y:      4.13.0
Node.js:    8.2.1
npm:        5.3.0
PhantomJS:  2.1.1
OS:         16.7.0 (darwin)

A page that fails: https://www.microsoft.com/en-us/

Oddly enough I had a few other pages that were having the same error yesterday, but not today =/

**Comment by mncrff** [comment]
Wow, @nzambello 's suggestion seems to work. Is there a reason why `http://squizlabs.github.io/HTML_CodeSniffer/build/HTMLCS.js` works but `lib/vendor/HTMLCS.js` doesn't? Why do they differ? Without knowing anything about the inner workings of pa11y, the `lib/vendor/HTMLCS.js` seems buggy.

**Comment by Godoy** [comment]
Hi folks,
I had the same problem here using pa11y 5.0.0-beta.2 and node 8.6.0. 

It worked after I downgrade to 5.0.0-beta.1

**Comment by jasonday** [comment]
I'm having a similar issue using the dashboard:

```
  > Injecting HTML CodeSniffer
  > Injecting Pa11y
  > Running Pa11y on the page
  > Waiting for 5000ms
  > Test function errored for "https://www.llbean.com/llb/shop/32709"
  > PhantomJS page closed
  > PhantomJS browser exited
Failed to finish task 5a0f2e38cac07ef825678548: HTML CodeSniffer: undefined is not an object
process')
Finished running one-off task @ Fri Nov 17 2017 13:47:02 GMT-0500 (Eastern Standard Time)
```

Occurring on target.com and https://www.llbean.com/llb/shop/32709

Downloaded and installed the dashboard this AM, no changes to dependencies.

npm: 5.5.1
Node: 8.9.1
dashboard: 2.30 (from package.json)

**Comment by hollsk** [comment]
@rowanmanning I thought we upgraded HTMLCS to 2.1.1 in #326 ? 

I just tried running all of the URLs these users have provided, but I used the latest build from https://squizlabs.github.io/HTML_CodeSniffer/build/HTMLCS.js instead of the one bundled in `lib/vendor/HTMLCS`. Everything works fine with that, but crashes using our bundled version.

The version number in the latest build and in `lib/vendor/HTMLCS` both say 2.1.1, though!

**Comment by greengiraffe** [comment]
Same issue here, regardless of the tested page. @nzambello's suggestion works. Here's the environment and debug output:

```sh
$ pa11y --environment

Pa11y:      4.13.1
Node.js:    8.6.0
npm:        5.5.1
PhantomJS:  2.1.1
OS:         17.2.0 (darwin)
```
```sh
$ pa11y http://www.zeit.de --debug
Welcome to Pa11y

 > PhantomJS browser created
 > Debug: PhantomJS page created
 > Debug: Opening "http://www.zeit.de" in PhantomJS
 > Debug: Opened "http://www.zeit.de" in PhantomJS
 > Testing the page "http://www.zeit.de"
 > Debug: Injecting HTML CodeSniffer
 > Debug: Injecting Pa11y
 > Debug: Running Pa11y on the page
 > Error: Test function errored for "http://www.zeit.de"
 > Debug: PhantomJS page closed
 > Debug: PhantomJS browser exited
Error: HTML CodeSniffer: undefined is not an object (evaluating 'window.HTMLCS.process')
    at Object.<anonymous> (/usr/local/lib/node_modules/pa11y/lib/pa11y.js:71:16)
    at Object.f [as onCallback] (/usr/local/lib/node_modules/pa11y/node_modules/once/once.js:25:25)
    at /usr/local/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:636:30
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:617:17)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rowanmanning** [comment]
I _think_ this is fixed now, seems there was something wrong with our internal build of HTML CodeSniffer. I've released the following versions, could you verify that things works for you?

  - Pa11y 4.13.2
  - Pa11y 5.0.0-beta.3

**Comment by greengiraffe** [comment]
Running Pa11y 4.13.2 with the same command as above works now, I didn't try the beta though. Thanks for the fix!

**Comment by greengiraffe** [comment]
@rowanmanning Running pa11y programmatically doesn't work now, also due to HTMLCS.

Example:
```js
const pa11y = require('pa11y')

let test = pa11y({
  standard: 'WCAG2AA',
  log: {
		debug: console.log.bind(console),
		error: console.error.bind(console),
		info: console.log.bind(console)
	}
})

test.run('http://www.zeit.de/', (error, results) => {
  if (error) {
    console.error(error.message)
  }
  console.log(results)
})
```

Output:
```
PhantomJS browser created
PhantomJS page created
Opening "http://www.zeit.de/" in PhantomJS
Opened "http://www.zeit.de/" in PhantomJS
Testing the page "http://www.zeit.de/"
Injecting HTML CodeSniffer
Injecting Pa11y
Running Pa11y on the page
Test function errored for "http://www.zeit.de/"
PhantomJS page closed
PhantomJS browser exited
HTML CodeSniffer: undefined is not an object (evaluating 'window.HTMLCS.process')
undefined
```
