### ISSUE TITLE
--config option example?

### ISSUE THREAD

**Issue by seanredmond** [pa11y/pa11y#336]
I'm having trouble figuring out how to use a config file with a simple command line test (or whether one can).  I need to go to a URL, click a link, and test the resulting page. Let's say it's the "More information..." link on http://example.com (which goes to https://www.iana.org/domains/reserved).

With this saved in example-test.json

    pa11y({
      actions: [
        'click element body > div > p:nth-child(3) > a',
        'wait for url to be https://www.iana.org/domains/reserved'
      ]
    });

I would expect that `pa11y -c example-test.json http://example.com` would output the results for https://www.iana.org/domains/reserved (25 errors), but instead I just get the results for example.com (1 error), as if there was no config file. The examples and sample code are either ambiguous or seem to be aimed at running tests from your own JS so I'm having a hard time seeing what's wrong.

**Comment by rowanmanning** [comment]
Hi @seanredmond, currently Pa11y 5 will error more helpfully in this case, as the config file you're using is malformed JSON - you don't need the `pa11y` call in there:

```json
{
  "actions": [
    "click element body > div > p:nth-child(3) > a",
    "wait for url to be https://www.iana.org/domains/reserved"
  ]
}
```

You've highlighted that we do need better documentation around config files, so we'll get on that.

**Comment by seanredmond** [comment]
Thanks! It also seems the config file has to have a `.json` extension?

**Comment by rowanmanning** [comment]
No, a `.js` extension _should_ work, but in that case you'll need to use `module.exports` to export the config.

**Comment by seanredmond** [comment]
I had used `.cfg` (because it's a config file, right?), and after a few minutes of "what the...?" tried changing the extension to `.json`. Just another minor detail that I didn't see in the docs.

I'm happy to take on the task of this documentation.

**Comment by andrewmee** [comment]
Hey @seanredmond I wonder if you could take a moment to read [our new documentation around configuration](https://github.com/pa11y/pa11y/tree/5.x#configuration) and see if it makes more sense now?

We explicitly call out the different options for providing configuration now, and have made an attempt to clarify the whole section generally.

**Comment by hollsk** [comment]
gonna close this issue as we updated the docs and we've also moved to pa11y 5 ☺️
