### ISSUE TITLE
Invalid JSON output

### ISSUE THREAD

**Issue by sagar441989** [pa11y/pa11y#342]
1. pa11y --reporter json https://github.com/login > report.json

Extra backslash gets added into output in  JSON file.

**Comment by rowanmanning** [comment]
Hi @sagar441989, I haven't been able to replicate this with either Pa11y 4 or 5 – the JSON is valid for both when testing this URL. Could you provide more information about your pa11y install with `pa11y --environment`?

**Comment by sagar441989** [comment]
Environment Details:
Pa11y:      4.13.0
Node.js:    6.11.0
npm:        3.10.10
PhantomJS:  2.1.1
OS:         10.0.14393 (win32)

What I run?
pa11y --standard Section508 --reporter json https://github.com/login > Github.json

Output:
[{"code":"Section508.L.NoContentAnchor","context":"<a class=\"header-logo\" href=\"https://github.com/\" aria-label=\"Homepage\" data-ga-click=\"(Logged out) Header, go to homepage, icon:logo-wordmark\">\n      <svg aria-hidden=\"true\" ...</a>","message":"Anchor element found with a valid href attribute, but no link content has been supplied.","selector":"html > body > div:nth-child(1) > div:nth-child(3) > div > a","type":"error","typeCode":1},{"code":"Section508.N.Errors","context":"<form accept-charset=\"UTF-8\" action=\"/session\" method=\"post\"><div style=\"margin:0;padding:0;...</form>","message":"If an input error is automatically detected in this form, check that the item(s) in error are identified and the error(s) are described to the user in text.","selector":"#login > form","type":"notice","typeCode":3},{"code":"Section508.N.Labels","context":"<form accept-charset=\"UTF-8\" action=\"/session\" method=\"post\"><div style=\"margin:0;padding:0;...</form>","message":"Check that descriptive labels or instructions (including for required fields) are provided for user input in this form.","selector":"#login > form","type":"notice","typeCode":3},{"code":"Section508.N.KeyboardNav","context":"<form accept-charset=\"UTF-8\" action=\"/session\" method=\"post\"><div style=\"margin:0;padding:0;...</form>","message":"Ensure that this form can be navigated using the keyboard and other accessibility tools.","selector":"#login > form","type":"notice","typeCode":3},{"code":"Section508.L.PlaceholderAnchor","context":"<a href=\"\">Reload</a>","message":"Anchor element found with link content, but no href, ID, or name attribute has been supplied.","selector":"html > body > div:nth-child(9) > span:nth-child(2) > a","type":"warning","typeCode":2},{"code":"Section508.L.PlaceholderAnchor","context":"<a href=\"\">Reload</a>","message":"Anchor element found with link content, but no href, ID, or name attribute has been supplied.","selector":"html > body > div:nth-child(9) > span:nth-child(3) > a","type":"warning","typeCode":2}]

**Comment by rowanmanning** [comment]
@sagar441989: when I paste that JSON into https://jsonlint.com/ it passes, can you confirm that this works for you?

**Comment by sagar441989** [comment]
JASON format is fine but the content is messed up. In the result "context" key shows backslash in its value.

**Comment by rowanmanning** [comment]
Yes, that's required in JSON. You need to escape quote characters (`"`) and line breaks (`\n`) in a string with backslashes. I've looked through and there's no backslash that shouldn't be there.

If you parse it with any JSON library, the back-slashes won't be present in the parsed values.

I'm going to close this as the JSON is valid.
