### ISSUE TITLE
Happy Koalaween!

### ISSUE THREAD

**Issue by TheJaredWilcurt** [pa11y/pa11y#343]
Hi Pa11y People!!!

[Koa11y](https://open-indy.github.io/Koa11y) just had a new release and we wanted to say thanks for all the hard work on Pa11y!

# Happy Koalaween! :smiley: 

![Happy Koalaween, koala in a pumpkin mask](https://user-images.githubusercontent.com/4629794/32086032-971a6338-baa0-11e7-8957-75a3c01e3c5b.png)

<p align="center">
:jack_o_lantern: :koala: :spider: :ghost: :spider_web: :koala: :jack_o_lantern: :ghost: :spider: :spider_web: :ghost: :koala: :spider: :spider_web: :jack_o_lantern:
</p>

(this issue can be closed whenever)

**Comment by rowanmanning** [comment]
I never want to close this!

**Comment by TheJaredWilcurt** [comment]
It is now November, and Koalaween is over. If we don't close this ticket now the Koala will turn into a squishy pumpkin.

![pumpkin](https://user-images.githubusercontent.com/4629794/32278539-64f4409a-beec-11e7-8a0c-479d7c739164.jpg)

Farewell!
