### ISSUE TITLE
WebdriverIO plugin?

### ISSUE THREAD

**Issue by kaelig** [pa11y/pa11y#349]
Have you considered creating a plugin for WebdriverIO?

I'm currently using pa11y-cli to test accessibility on polaris.shopify.com, and I'm also using WebdriverIO for visual regression testing (with Percy.io). Looking at my wdio tests, I'd quite like to bundle both Percy and pa11y in the same suite.

My test file looks like this:

```js
describe('Take snapshots', () => {
  urls.map((path) =>
    it(`${path} looks as expected`, () => {
      browser.url(path);
      browser.pause(2000);
      browser.percySnapshot(path);
    }));
});
```

Docs for the Percy.io plugin: https://percy.io/docs/clients/javascript/webdriverio

I was wondering if we could have something similar, e.g.:

```js
browser.pa11y(path);
```

Or maybe there's already a way to do this at the moment and I've missed it?

**Comment by rowanmanning** [comment]
Hey Kaelig :)

This would be useful, but not something me or the rest of the core team will have time for soon. If it's something you fancy investigating then I'd definitely accept a PR.

Alternatively maybe this is a case for a new Pa11y repo/project like pa11y-webdriver? So as not to further complicate the main codebase. Again very little time to work on this myself but would definitely be up for pulling a project into the Pa11y org.

**Comment by jgornick** [comment]
I agree that providing a webdriver plugin for pa11y is definitely beneficial.

For this reason, we ended up using aXe (https://www.axe-core.org/) which provides a webdriver plugin (https://github.com/dequelabs/axe-webdriverjs). To tie it all together, we use the https://github.com/E1Edatatracker/protractor-axe-report-plugin project inside our protractor tests to validate and report a11y.

**Comment by josebolos** [comment]
Hi all, as @rowanmanning mentioned we're more than happy to accept contributions, but this is not something that we would be willing to implement ourselves, so I'm closing the issue.
