### ISSUE TITLE
Question : How to invoke Pa11y as ajax call from HTML pages

### ISSUE THREAD

**Issue by sudhar99** [pa11y/pa11y#351]
I know it is more of a question than reporting an issue. But I couldn't find any other medium to post my question and pardon my ignorance. I am trying to test old legacy large application for accessibility and is developed in J2EE. It doesn't have the test scripts and most of the tests are being carried out manually. In this regard, I am looking for a embedded ajax snippet in all pages (as part of template) to test for the current HTML page by talking to pa11y server. When I test the page(s) thru browser, I expect the ajax script would send the current HTML source to Pa11y server and the accessibility report is saved for later access.  Hope I make sense !!! and looking for ways to accomplish this as the application is protected under login/password etc. and not feasible to create script for 100s of pages...

Let me know your thoughts and greatly appreciate your time.

**Comment by rowanmanning** [comment]
Hi @sudhar99, this probably not a job that Pa11y can do, as Pa11y runs in Node.js. I'd recommend looking into using [HTML CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) directly and then writing some of your own code around it to send to your server.

Sorry I can't really help more than that, your use case is quite specific to you and not something that would be useful for the team here to build 🙂
