### ISSUE TITLE
Make colour contrast error messages better

### ISSUE THREAD

**Issue by leggsimon** [pa11y/pa11y#354]
Just an idea to improve the error message on colour contrast errors,

```
 • This element has insufficient contrast at this conformance level. Expected a
   contrast ratio of at least 4.5:1, but text in this element has a contrast
   ratio of 4.34:1. Recommendation: change text colour to #0a737d.
```
^ This is the current error, it would be good to know what the current `color` and `background-color` that fail is.

Idea:

```
 • The color #XXXXXX on a background of #XXXXXX has insufficient contrast
   at this conformance level. Expected a contrast ratio of at least 4.5:1, but text
   in this element has a contrast ratio of 4.34:1. 
   Recommendation: change text colour to #0a737d.
```

Maybe a good starter issue

**Comment by rowanmanning** [comment]
Yeah this _would_ be useful.

Currently we're relying on [HTML CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) for all our error messaging, and I'm not sure how easy that'll be to modify without maintaining a fork. Alternatively we could build something into Pa11y which does some translation of error messages before output.

If we go in that direction then I'd prefer if it only happened in Pa11y 5.x to avoid maintaining the code in two separate branches.

**Comment by josebolos** [comment]
Hi @leggsimon!

Thank you so much for such a detailed issue. As mentioned by @rowanmanning, pa11y uses HTML CodeSniffer by default to run its tests. Unfortunately, we don't have the resources to add such a feature ourselves, or to maintain a fork of HTML Codesniffer.

Thank you!
