### ISSUE TITLE
Multiple roots on one page?

### ISSUE THREAD

**Issue by morganpackard** [pa11y/pa11y#357]
I've found the `root` option, which is very useful. However, I have multiple elements on my page (all matching the same selector) which I'd like to test. Is there currently a way to do this? From what I can tell, `pa11y` uses the first match it finds and ignores the rest.

**Comment by rowanmanning** [comment]
Ah yep that's currently what the `root` option does, just the first element. It _should_ be possible for it to run it for every matching element but there would be a few things to bear in mind to anybody tackling this work:

1. You'd probably need to run HTML CodeSniffer multiple times against each element, then concatenate the arrays of results together.
2. How would it be handled if, for example, there are multiple elements matching the `root` selector and one is the child of another. Should the result appear twice, or should there be some logic to detect whether a selected root element is already within another matching element?

**Comment by morganpackard** [comment]
We were able to get past this limitation by using the page root, but hiding all other elements. 

```
pa11y(PAGE_URL, {hideElements: '.thingToHide, .otherThingToHide'}
```

**Comment by thuanrausaigon** [comment]
Đã được sửa loi

**Comment by rowanmanning** [comment]
I'm gonna close this for now as something we probably won't tackle any time soon. If anybody wants to think further about implementation and give it a go then you're welcome to 👍
