### ISSUE TITLE
Pa11y 5.0.0-beta.5 fails to run on pages with strict Content-Security-Policy.

### ISSUE THREAD

**Issue by adunkman** [pa11y/pa11y#364]
Hello! I’ve just installed the beta using `npm install -g pa11y@beta`, and it fails to run:

```
$ pa11y https://www.dunkman.me

Welcome to Pa11y

 > Running Pa11y on URL https://www.dunkman.me

Error: Evaluation failed: ReferenceError: _runPa11y is not defined
    at options (<anonymous>:3:3)
    at ExecutionContext.evaluateHandle (/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/lib/ExecutionContext.js:66:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

Here’s the output from `npm install -g pa11y@beta`:

```$ npm install -g pa11y@beta
/usr/local/bin/pa11y -> /usr/local/lib/node_modules/pa11y/bin/pa11y.js

> puppeteer@0.13.0 install /usr/local/lib/node_modules/pa11y/node_modules/puppeteer
> node install.js

Downloading Chromium r515411 - 73.2 Mb [====================] 100% 0.0s 
Chromium downloaded to /usr/local/lib/node_modules/pa11y/node_modules/puppeteer/.local-chromium/mac-515411
+ pa11y@5.0.0-beta.5
added 62 packages in 17.895s
```

Here’s some version information: 

```
OS X 10.13.2 (17C88)

$ pa11y --version
5.0.0-beta.5

$ node --version
v8.1.2
```

**Comment by adunkman** [comment]
It seems to work on other sites — given the error message, I feel this might be related to the fact that https://www.dunkman.me has a strict content-security-policy? Not sure, just a shot in the dark.

**Comment by adunkman** [comment]
Just going to keep working out loud — the `--debug` output confirmed that it’s failing right after attempting to inject scripts into the page. 

```
$ pa11y --debug https://www.dunkman.me

Welcome to Pa11y

 > Running Pa11y on URL https://www.dunkman.me
 > Debug: Launching Headless Chrome
 > Debug: Opening URL in Headless Chrome
 > Debug: Setting request method
 > Debug: Setting request headers
 > Debug: Injecting HTML CodeSniffer
 > Debug: Injecting Pa11y
 > Debug: Running Pa11y on the page

Error: Evaluation failed: ReferenceError: _runPa11y is not defined
    at options (<anonymous>:3:3)
    at ExecutionContext.evaluateHandle (/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/lib/ExecutionContext.js:66:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by adunkman** [comment]
Cross-linking https://github.com/GoogleChrome/puppeteer/issues/1229 which seems to be why the error message is misleading here. Not sure if there’s a workaround.

**Comment by JakeChampion** [comment]
@adunkman As Pa11y is using Chrome HeadlessI think it could use the `--disable-web-security` flag to disable CSP. The list of flags is [here](https://peter.sh/experiments/chromium-command-line-switches/).

**Comment by JakeChampion** [comment]
When [this pull request](https://github.com/GoogleChrome/puppeteer/pull/1624) to puppeteer is merged then Pa11y could have a better error message for this scenario.

**Comment by adunkman** [comment]
Hmm, unfortunately `--disable-web-security` doesn’t help us here, since that disables the same-origin policy (but doesn’t seem to affect the content-security-policy). 

```
$ pa11y --config=./pa11y.json --debug https://www.dunkman.me

Welcome to Pa11y

 > Running Pa11y on URL https://www.dunkman.me
 > Debug: Launching Headless Chrome
 > Debug: Opening URL in Headless Chrome
 > Debug: Setting request method
 > Debug: Setting request headers
 > Debug: Injecting HTML CodeSniffer
 > Debug: Injecting Pa11y
 > Debug: Running Pa11y on the page

Error: Evaluation failed: ReferenceError: _runPa11y is not defined
    at options (<anonymous>:3:3)
    at ExecutionContext.evaluateHandle (/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/lib/ExecutionContext.js:66:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

pa11y.json:

```json
{
  "chromeLaunchConfig": {
    "ignoreHTTPSErrors": true,
    "args": [
      "--disable-web-security"
    ]
  }
}
```

**Comment by JakeChampion** [comment]
@adunkman Perhaps https://peter.sh/experiments/chromium-command-line-switches/#reduce-security-for-testing is the flag we need? 

If not then another possible solution would be to create a proxy server which strips the Content Security Policy http header, this is what cypress.io currently does. cypress.io is looking into [alternative approaches](https://github.com/cypress-io/cypress/issues/1030), if they work then we can copy the approach inside pa11y.

**Comment by adunkman** [comment]
Still no dice with `--reduce-security-for-testing` — I don’t think there’s a flag to disable handling of the `Content-Security-Policy` header. 

```json
{
  "chromeLaunchConfig": {
    "ignoreHTTPSErrors": true,
    "args": [
      "--disable-web-security",
      "--reduce-security-for-testing"
    ]
  }
}
```

**Comment by adunkman** [comment]
For a work-around, I’ve discovered that puppeteer is embedding the pa11y script using a inline script tag — so I had to adjust the `Content-Security-Policy` to allow `'unsafe-inline'` for the pa11y run: 

```http
Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline';
```

**Comment by khrome83** [comment]
@adunkman is this a code change, or a configuration setting?

**Comment by adunkman** [comment]
@khrome83 it was a code change in my app to allow the test to run.

**Comment by rowanmanning** [comment]
We might have a fix in the works for this. Instead of including the Pa11y scripts as `<script/>` tags, I'm loading the files and evaluating them as strings. So far this has worked with all of the `Content-Security-Policy` headers I've thrown at it

**Comment by rowanmanning** [comment]
@adunkman, @JakeChampion, @khrome83, I've just published Pa11y `5.0.0-beta.8` which contains the fix for this. I've tested myself a fair bit, but it'd be great if you could confirm that this works for your pages.

If not then we can reopen and try to work out why.

**Comment by adunkman** [comment]
Hm, seeing the same issue at `5.0.0-beta.8` — I’m assuming it’s still because I’m forbidding `unsafe-inline`. 

```
$ pa11y --debug https://www.dunkman.me

Welcome to Pa11y

 > Running Pa11y on URL https://www.dunkman.me
 > Debug: Launching Headless Chrome
 > Debug: Opening URL in Headless Chrome
 > Debug: Setting request method
 > Debug: Setting request headers
 > Debug: Injecting HTML CodeSniffer
 > Debug: Injecting Pa11y
 > Debug: Running Pa11y on the page

Error: Evaluation failed: ReferenceError: _runPa11y is not defined
    at options (<anonymous>:3:3)
    at ExecutionContext.evaluateHandle (/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/lib/ExecutionContext.js:66:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

I’m not sure how puppeteer is actually evaluating things with `page.evaluate` (the fix introduced in #371) — I traced it down to puppeteer’s [ExecutionContext#evaluate](https://github.com/GoogleChrome/puppeteer/blob/5368051610babf52e7df927c323d315a493fb56f/lib/ExecutionContext.js#L40-L45) but then I get a little lost. 

@rowanmanning you mentioned in #371:

> I've tested with the reported URLs as well as my own test pages which have very strict content security policies.

Have you gotten pa11y to run on the URL I’m testing, `https://www.dunkman.me`? Just wanted to make sure it wasn’t just me. 😱

**Comment by adunkman** [comment]
Wait! 

Of course, the moment _after_ I submit the comment, I realize that I’m running against a global installation of pa11y, and I upgraded my local version of pa11y to `5.0.0-beta.8`. After updating my global version to `5.0.0-beta.8`, the issue is fixed for me: 

```
$ pa11y --debug https://www.dunkman.me

Welcome to Pa11y

 > Running Pa11y on URL https://www.dunkman.me
 > Debug: Launching Headless Chrome
 > Debug: Opening URL in Headless Chrome
 > Debug: Setting request method
 > Debug: Setting request headers
 > Debug: Injecting HTML CodeSniffer
 > Debug: Injecting Pa11y
 > Debug: Running Pa11y on the page
 > Debug: Document title: "Andrew Dunkman"

No issues found!
```

Sorry for the noise! Thanks for the fix, and lots of hearts! ❤️ 💟 ❤️ 💟

**Comment by rowanmanning** [comment]
That's OK :) glad to help. Thanks for bringing this to my attention in the first place!
