### ISSUE TITLE
Issue with logging when using the JavaScript API and CLI reporter

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#366]
_Opening on behalf of @jryanconklin so I have a more permanent place to respond than Slack_ 🙂 

> **J. Ryan Conklin:** Hello! I’m running pa11y from a javascript file using the cli as the reporter. I’m currently getting a bit of output. I believe the headless chrome object in console. Is that expected?
>
> **Rowan Manning:** ... Any way you could share your code?
>
> **J. Ryan Conklin:** Sure ... here’s the test: https://github.com/phase2/particle/blob/epic/v10/tools/tests/accessibility/pa11y.js

---

I'm not sure if I've managed to replicate with the code above, could you comment with the output you're getting, @jryanconklin? The output I'm getting is as follows (ignore the fact that the URLs are erroring, this is just because I don't have the application running locally):

<details><summary><b>Command output when running code linked to above</b></summary>
<pre><code>Running Pa11y on URL http://0.0.0.0:8080/pl/patterns/00-protons-demo-borders/00-protons-demo-borders.html
Launching Headless Chrome
Running Pa11y on URL http://0.0.0.0:8080/pl/patterns/01-atoms-alert-demo-alerts/01-atoms-alert-demo-alerts.html
Launching Headless Chrome
Running Pa11y on URL http://0.0.0.0:8080/pl/patterns/02-molecules-card-demo-cards/02-molecules-card-demo-cards.html
Launching Headless Chrome
Opening URL in Headless Chrome
Opening URL in Headless Chrome
Setting request method
Setting request headers
Setting request method
Setting request headers
Opening URL in Headless Chrome
Setting request method
Setting request headers
Injecting HTML CodeSniffer
Injecting HTML CodeSniffer
Injecting HTML CodeSniffer
Injecting Pa11y
Injecting Pa11y
Injecting Pa11y
Running Pa11y on the page
Running Pa11y on the page
Running Pa11y on the page
Document title: ""
Document title: ""
Document title: ""

Results for URL: http://0.0.0.0:8080/pl/patterns/00-protons-demo-borders/00-protons-demo-borders.html

 • Error: A title should be provided for the document, using a non-empty title element in the head section.
   ├── WCAG2AAA.Principle2.Guideline2_4.2_4_2.H25.1.NoTitleEl
   ├── html > head
   └── <head><script type="text/javascript">...</head>

1 Errors

Results for URL: http://0.0.0.0:8080/pl/patterns/01-atoms-alert-demo-alerts/01-atoms-alert-demo-alerts.html

 • Error: A title should be provided for the document, using a non-empty title element in the head section.
   ├── WCAG2AAA.Principle2.Guideline2_4.2_4_2.H25.1.NoTitleEl
   ├── html > head
   └── <head><script type="text/javascript">...</head>

1 Errors

Results for URL: http://0.0.0.0:8080/pl/patterns/02-molecules-card-demo-cards/02-molecules-card-demo-cards.html

 • Error: A title should be provided for the document, using a non-empty title element in the head section.
   ├── WCAG2AAA.Principle2.Guideline2_4.2_4_2.H25.1.NoTitleEl
   ├── html > head
   └── <head><script type="text/javascript">...</head>

1 Errors
</code></pre>
</details>

**Comment by jryanconklin** [comment]
Sure thing, it's a huge bit of text so I went ahead and set it to an output.txt:

[output.txt](https://github.com/pa11y/pa11y/files/1636223/output.txt)

**Comment by rowanmanning** [comment]
Ah I see the issue, the log you're seeing is a forwarded `console.log` from one of the pages being tested. There are a couple of ways you can disable this output:

1. By suppressing debug logs altogether:
    ```diff
	  log: {
	-   debug: console.log,
	+   debug: () => {},
	    error: console.error,
	    info: console.log,
	  },
    ```

2. By using a bit of a dirty trick to get rid of only browser console messages:
    ```diff
	  log: {
	-   debug: console.log,
	+   debug: (message) => {
	+       if (!message.startsWith('Browser Console:')) {
	+           console.log(message);
	+       }
	+   },
	    error: console.error,
	    info: console.log,
	  },
    ```

I've also opened #367, as we should probably have an easier way to disable these logs. And also this should be logging the console message text, not the object – I'm investigating that part.

**Comment by jryanconklin** [comment]
Thanks! That works like a charm.
