### ISSUE TITLE
Allow disabling of browser debug logs

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#367]
In #329 Pa11y started outputting logs from the browser when in debug mode, but there's currently no way to disable this behaviour. When testing web pages which make heavy use of `console.log`, the debug output is a bit unwieldy.

I propose adding a flag to the command line (something like `--disable-browser-logs`) and a corresponding option to the JavaScript API (something like `disableBrowserLogs: true`. This should be added only to the 5.x branch I think.

See #366 for a real world example of this tripping somebody up.

**Comment by andrewmee** [comment]
I'm not convinced we need this new flag/option... I think that when running pa11y in debug mode you would expect a verbose output, and that generally speaking console messages form a useful addition to that output.

Each new flag or option we add increases the complexity of pa11y, and of its documentation (which can already be a bit daunting) and so I'd be reluctant to add even more.  Particularly flags that are co-dependent on other flags such as this one would be on `--debug`. (I think I'm particularly aware of this after trying to document the `level`, `threshold`, and `reporter` options which are only effective in some circumstances).

Given it's possible to deal with this by massaging the `debug` log function like you noted in [your response](https://github.com/pa11y/pa11y/issues/366#issuecomment-358244019), is it worth adding yet more configuration?

**Comment by rowanmanning** [comment]
Yeah I agree, I opened this before I discovered #368. I think any complaints about the debug logs being long should now be fixed. Good shout, gonna close.
