### ISSUE TITLE
Pa11y 5.x opens double the Chrome processes

### ISSUE THREAD

**Issue by colinrotherham** [pa11y/pa11y#369]
Hi @rowanmanning,

I've noticed that every Chromium process opened via Puppeteer also opens a 2nd tab with the "Get to Chromium Faster" suggesting it as the default OS browser. You can see this with `headless: false`.

Can Pa11y take the lead from Karma here?
https://github.com/karma-runner/karma-chrome-launcher/blob/master/index.js#L35

```js
args: [
    '--no-default-browser-check'
]
```

They've got some extra flags to turn off throttled background rendering and timers too!

```js
args: [
    '--disable-background-timer-throttling',
    '--disable-renderer-backgrounding'
]
```

Thought I'd discuss here before opening a pull request.

**Comment by rowanmanning** [comment]
@colinrotherham I hadn't noticed this, well spotted. I'm happy to either accept a PR or work on this myself if you don't have the time.

**Comment by colinrotherham** [comment]
@rowanmanning When I wrote this issue, the flag `--no-default-browser-check` wasn't working.

Now with the latest puppeteer and Pa11y I'm still seeing two tabs but at least the first one is now empty, the first start page isn't loaded—it's just blank.

I'll leave this for now.

**Comment by rowanmanning** [comment]
Let's close this for now. If this is causing issues for anyone in the future then please comment here and we can reopen :)
