### ISSUE TITLE
"Img element is marked so that it is ignored by Assistive Technology" should not be a warning

### ISSUE THREAD

**Issue by 36degrees** [pa11y/pa11y#372]
Given a simple page with a single decorative image which can be safely ignored by assistive technologies:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My Website</title>
  </head>

  <body>
    <img src="http://pa11y.org/resources/brand/logo.svg" alt="">
  </body>
</html>
```

When running pa11y against it, you get a warning for WCAG2AA Principle 1, HTML technique 67:
```
• Warning: Img element is marked so that it is ignored by Assistive Technology.
   ├── WCAG2AA.Principle1.Guideline1_1.1_1_1.H67.2
   ├── html > body > img
   └── <img src="http://pa11y.org/resources/brand/logo.svg" alt="">
```

I think that pa11y is raising this to prompt the user to manually verify whether this is the correct behaviour for the image as it depends on the image content.

However, when this sort of manual verification is prompted elsewhere within pa11y it is done as a `notice` with guidance to help the user verify that something is correct, such as with titles:

```
 • Notice: Check that the title element describes the document.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_2.H25.2
   ├── html > head > title
   └── <title>My Website</title>
```

I would suggest re-classifying WCAG2AA.Principle1.Guideline1_1.1_1_1.H67.2 as a notice, and modifying the text to something like:

> Notice: Img element is marked so that it is ignored by Assistive Technology. Check that this behaviour is correct.

We have seen users investing time and effect trying to 'fix' these warnings, despite the implementation being correct, because the way it is reported is confusing.

**Comment by hollsk** [comment]
hey @36degrees - you should raise this in the HTML_Codesniffer project instead: https://github.com/squizlabs/HTML_CodeSniffer (that's where our rulesets come from).

Thanks for using Pa11y! 😄

**Comment by rowanmanning** [comment]
@36degrees: also worth noting in here that we understand this issue and in Pa11y v5.0 notices and warnings will be ignored by default, so you'll only see actionable issues :)
