### ISSUE TITLE
how exactly --add-rule works?

### ISSUE THREAD

**Issue by wiprosagar123** [pa11y/pa11y#375]
When I run below, the output gives result for different rules
pa11y  --add-rule Principle1.Guideline1_3.1_3_1_AAA https://github.com/login
**Output:**
Welcome to Pa11y

 > PhantomJS browser created
 > Testing the page "https://github.com/login"

Results for https://github.com/login:

 • Notice: Check that the title element describes the document.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_2.H25.2
   ├── html > head > title
   └── <title>Sign in to GitHub · GitHub</title>

 • Warning: Check that this element has an inherited background colour or image to complement the corresponding inline foreground colour.
   ├── WCAG2AA.Principle1.Guideline1_4.1_4_3_F24.F24.FGColour
   ├── html > head > link:nth-child(63)
   └── <link rel="mask-icon" href="https://assets-cdn.github.com/pinned-octocat.svg" color="#000000">

 • Warning: This element is absolutely positioned and the background color can not be determined. Ensure the contrast ratio between the text and all covered parts of the background are at least 4.5:1.
   ├── WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Abs
   ├── html > body > div:nth-child(1) > a
   └── <a href="#start-of-content" tabindex="1" class="px-2 py-4 show-on-focus js-skip-to-content">Skip to content</a>

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── html > body > div:nth-child(1) > a
   └── <a href="#start-of-content" tabindex="1" class="px-2 py-4 show-on-focus js-skip-to-content">Skip to content</a>

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── html > body > div:nth-child(1) > div:nth-child(3) > div > a
   └── <a class="header-logo" href="https://github.com/" aria-label="Homepage" data-ga-click="(Logged out) Header, go to homepage, icon:logo-wordmark"> <svg aria-hidden="true" ...</a>

 • Notice: If an input error is automatically detected in this form, check that the item(s) in error are identified and the error(s) are described to the user in text.
   ├── WCAG2AA.Principle3.Guideline3_3.3_3_1.G83,G84,G85
   ├── #login > form
   └── <form accept-charset="UTF-8" action="/session" method="post"><div style="margin:0;padding:0;...</form>

 • Notice: Check that descriptive labels or instructions (including for required fields) are provided for user input in this form.
   ├── WCAG2AA.Principle3.Guideline3_3.3_3_2.G131,G89,G184,H90
   ├── #login > form
   └── <form accept-charset="UTF-8" action="/session" method="post"><div style="margin:0;padding:0;...</form>

 • Notice: Check that this form provides suggested corrections to errors in user input, unless it would jeopardize the security or purpose of the content.
   ├── WCAG2AA.Principle3.Guideline3_3.3_3_3.G177
   ├── #login > form
   └── <form accept-charset="UTF-8" action="/session" method="post"><div style="margin:0;padding:0;...</form>

 • Notice: If this form would bind a user to a financial or legal commitment, modify/delete user-controllable data, or submit test responses, ensure that submissions are either reversible, checked for input errors, and/or confirmed by the user.
   ├── WCAG2AA.Principle3.Guideline3_3.3_3_4.G98,G99,G155,G164,G168.LegalForms
   ├── #login > form
   └── <form accept-charset="UTF-8" action="/session" method="post"><div style="margin:0;padding:0;...</form>

 • Notice: Check that a change of context does not occur when this input field receives focus.
   ├── WCAG2AA.Principle3.Guideline3_2.3_2_1.G107
   ├── #login > form > div:nth-child(1) > input:nth-child(1)
   └── <input name="utf8" type="hidden" value="✓">

 • Notice: Check that a change of context does not occur when this input field receives focus.
   ├── WCAG2AA.Principle3.Guideline3_2.3_2_1.G107
   ├── #login > form > div:nth-child(1) > input:nth-child(2)
   └── <input name="authenticity_token" type="hidden" value="BPI58jgcw+3IbadoN0VWPsiexIB50ZdMwpS1JDINAIGNOQp/aukQEMOY8y0mfgSpZ8qebzY8pR2nS9Mv/Wq9ng==">

 • Notice: Check that a change of context does not occur when this input field receives focus.
   ├── WCAG2AA.Principle3.Guideline3_2.3_2_1.G107
   ├── #login_field
   └── <input autocapitalize="off" autocorrect="off" autofocus="autofocus" class="form-control input-block" id="login_field" name="login" tabindex="1" type="text">

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── #login > form > div:nth-child(4) > label:nth-child(3) > a
   └── <a href="/password_reset" class="label-link">Forgot password?</a>

 • Notice: Check that a change of context does not occur when this input field receives focus.
   ├── WCAG2AA.Principle3.Guideline3_2.3_2_1.G107
   ├── #password
   └── <input class="form-control form-control input-block" id="password" name="password" tabindex="2" type="password">

 • Notice: Check that a change of context does not occur when this input field receives focus.
   ├── WCAG2AA.Principle3.Guideline3_2.3_2_1.G107
   ├── #login > form > div:nth-child(4) > input:nth-child(5)
   └── <input class="btn btn-primary btn-block" data-disable-with="Signing in…" name="commit" tabindex="3" type="submit" value="Sign in">

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── #login > p > a
   └── <a href="/join?source=login" data-ga-click="Sign in, switch to sign up">Create an account</a>

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── html > body > div:nth-child(4) > ul > li:nth-child(1) > a
   └── <a href="https://github.com/site/terms" class="link-gray" data-ga-click="Footer, go to terms, text:terms">Terms</a>

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── html > body > div:nth-child(4) > ul > li:nth-child(2) > a
   └── <a href="https://github.com/site/privacy" class="link-gray" data-ga-click="Footer, go to privacy, text:privacy">Privacy</a>

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── html > body > div:nth-child(4) > ul > li:nth-child(3) > a
   └── <a href="https://github.com/security" class="link-gray" data-ga-click="Footer, go to security, text:security">Security</a>

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── html > body > div:nth-child(4) > ul > li:nth-child(4) > a
   └── <a href="https://github.com/contact" class="link-gray" data-ga-click="Footer, go to contact, text:contact">Contact GitHub</a>

 • Notice: Check that a change of context does not occur when this input field receives focus.
   ├── WCAG2AA.Principle3.Guideline3_2.3_2_1.G107
   ├── #ajax-error-message > button
   └── <button type="button" class="flash-close js-ajax-error-dismiss" aria-label="Dismiss error"> <svg aria-hidden="true" ...</button>

 • Warning: Anchor element found with link content, but no href, ID or name attribute has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.Placeholder
   ├── html > body > div:nth-child(9) > span:nth-child(2) > a
   └── <a href="">Reload</a>

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── html > body > div:nth-child(9) > span:nth-child(2) > a
   └── <a href="">Reload</a>

 • Warning: Anchor element found with link content, but no href, ID or name attribute has been supplied.
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.Placeholder
   ├── html > body > div:nth-child(9) > span:nth-child(3) > a
   └── <a href="">Reload</a>

 • Notice: Check that the link text combined with programmatically determined link context identifies the purpose of the link.
   ├── WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81
   ├── html > body > div:nth-child(9) > span:nth-child(3) > a
   └── <a href="">Reload</a>

 • Notice: Check that a change of context does not occur when this input field receives focus.
   ├── WCAG2AA.Principle3.Guideline3_2.3_2_1.G107
   ├── #facebox > div > button
   └── <button type="button" class="facebox-close js-facebox-close" aria-label="Close modal"> <svg aria-hidden="true" ...</button>

0 Errors
4 Warnings
22 Notices

**Comment by rowanmanning** [comment]
Hi 👋 the `--add-rule` option doesn't _replace_ all of the existing rules it just adds that rule to the list of rules to test against. So if the default set was:

  - example-rule-1
  - example-rule-2

Then running `pa11y --add-rule example-rule-3 http://example.com/` would have a set of:

  - example-rule-1
  - example-rule-2
  - example-rule-3

If you only want to test against one rule then you'd need to ignore all of the others like this:

```
pa11y --add-rule example-rule-3 --ignore example-rule-1 --ignore example-rule-2 http://example.com/
```

**Comment by wiprosagar123** [comment]
Thank you
