### ISSUE TITLE
Actions failing for Angular applications

### ISSUE THREAD

**Issue by hugo-marello** [pa11y/pa11y#376]
Version= 5.0.0-beta.8

While using a '*ngIf' on Angular, it will remove or add a tag to the browser's DOM (checked on chrome devtools). 
Actions like 'wait for element &lt;selector&gt; to be &lt;state&gt;' won't work at all, I have double checked the selectors.

Any clues on why it won't trigger the action?

**Comment by rowanmanning** [comment]
Hi @hugo-marello, could I get a few things from you?

1. The Pa11y version information provided by `pa11y --environment`
2. A copy of the page you're testing, if possible?
3. A copy of your Pa11y configuration

Thanks

**Comment by hollsk** [comment]
Hi @hugo-marello - I'm going to assume you've managed to fix this, so I'm closing this issue. 

If you're still having problems then please feel free to open a new issue 🙂
