### ISSUE TITLE
Pa11y Rules for Validation of Accessibility

### ISSUE THREAD

**Issue by SriGitHubSri** [pa11y/pa11y#400]
Hi Team,

I tried to install **pa11y** after installing **NodeJS8.11** in a **linux** machine. Since we only have access to npm modules but not to an external drive, instalation failed to download Chromium for which I set 
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD, and was able to install PA11Y. Verified it by running **./pa11y.js -V**.

After that I downloaded a copy of linux-chrome.zip and extracted it to node_modules folder, but still got the same error 
**Chromium revision is not downloaded. Run "yarn install" or "npm install**

Could you please help in resolving this issue?

**Comment by rowanmanning** [comment]
Hi @SriGitHubSri, glad you solved the Chrome issue. The tests we use are the ones provided by HTML CodeSniffer: http://squizlabs.github.io/HTML_CodeSniffer/ - there's more information about the rules there

**Comment by maksimkarpov** [comment]
> Hi Team,
> 
> **The above issue got resolved when specifid the chrome path in puppeteer module.**
> 
Hi @SriGitHubSri, having exactly same problem, can you please share how you specify the path?

**Comment by ThugDebugger** [comment]
Same issue as above, can this issue be re-opened since it persists

**Comment by ThugDebugger** [comment]
@maksimkarpov My issue ended up being a post-install script to install Chromium/Puppeteer not being able to finish out on initial install, which didn't occur to me until [looking at this issue in the Puppeteer repo](https://github.com/puppeteer/puppeteer/issues/4091#issuecomment-468525516)

If you're on MacOS you can get past this by: 

1. Uninstalling Pa11y
2. Installing at root with the following command: `sudo npm i pa11y -g --unsafe-perm=true --allow-root`
