### ISSUE TITLE
Pa11Y Issue With HTML Reporting

### ISSUE THREAD

**Issue by SriGitHubSri** [pa11y/pa11y#403]
Have installed **pa11y** and **pa11y-reporter-html**. Via JavaScript Interface, I am not able to report results in HTML format. But the same way, I tried to report in CSV, and it works fine.

**Could you please help in this?**

**PA11Y Version:**  5.0.3 using command ./pa11y.js -V

**Code Snippet:**  
//Importing pa11y-reporter-html

```
const result = await pa11y('http://nature.com', {
			// Log what's happening to the console
			log: {
				debug: console.log,
				error: console.error,
				info: console.log
			}
		});
		console.log("HTML OUPTUT")
		const htmlResults = html.results(result);
                console.log(htmlResults);
```

**Output Displayed:**

_Running Pa11y on URL http://nature.com
Launching Headless Chrome
Opening URL in Headless Chrome
Setting request method
Setting request headers
Injecting HTML CodeSniffer
Injecting Pa11y
Running Pa11y on the page
Document title: "Nature Research: science journals, jobs, information and services."
HTML OUPTUT
Promise { <pending> }_

**Comment by rowanmanning** [comment]
Hi @SriGitHubSri, this is because the `results` method of a reporter is promise-based, you will need to use `await` here as well. E.g.

```diff
  const result = await pa11y('http://nature.com', {
      // Log what's happening to the console
      log: {
          debug: console.log,
          error: console.error,
          info: console.log
      }
  });
  
  console.log("HTML OUPTUT");
- const htmlResults = html.results(result);
+ const htmlResults = await html.results(result);
  console.log(htmlResults);
```
