### ISSUE TITLE
Link to ruleset examples is broken in documentation

### ISSUE THREAD

**Issue by joacim-boive** [pa11y/pa11y#405]
https://github.com/pa11y/pa11y#rules-array

I expect the documentation to contain a link but looks like markdown:
" [HTML Code Sniffer WCAG2AAA ruleset][htmlcs-wcag2aaa-ruleset]."

Where do I find the actual documentation at HTML CS? Because I can't figure out how I specify the additional rules in .pa11ci.

**Comment by rowanmanning** [comment]
Sorry about that, I've fixed in #406, the link is:
https://github.com/pa11y/pa11y/wiki/HTML-CodeSniffer-Rules
