### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [pa11y/pa11y#409]
Hi I am looking for open source projects to contribute graphical design, I have done several jobs for free in opensource projects, I would like to know if you are interested that I make a logo for this your project ?.
I read your work and I love this project also the name it´s great, so If you want Im here for help.

Greetings

Nuno

**Comment by hollsk** [comment]
Hi Nuno - thanks so much for your offer, it's very kind of you! 

That said, we don't need a logo as we already have one. It's not obvious from looking at our repos that it exists, though :smile: 

I think I need to update our documentation to add our branding 😉
