### ISSUE TITLE
Puppeteer + Lighthouse already successfully running on RHLS but when trying to run pa11y, get `Failed to launch chrome` Error

### ISSUE THREAD

**Issue by ray-kim-12** [pa11y/pa11y#411]
I already have Puppeteer + Lighthouse successfully running on RHLS 7.4 but when trying to run pa11y for the first time, got the following error message:

```
Unhandled Rejection at: Promise Promise {
17:16:07 [Lighthouse & Pa11y Tests]   <rejected> Error: Failed to launch chrome!
17:16:07 [Lighthouse & Pa11y Tests] [0614/171607.549811:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

## Expected behaviour
Should not happen as I already set this up for when I used Puppeteer with lighthouse ??

## Actual behaviour
The output above

**Comment by rowanmanning** [comment]
Hi @ray-kim-12, it's possible that working out #410 will help with this. OK if we try and get that working first?

**Comment by hollsk** [comment]
Hi @ray-kim-12 - you can try to work around this by running chrome with the `--no-sandbox` flag enabled: 

```
chromeLaunchConfig: {
    args: ['--no-sandbox']
}
```
