### ISSUE TITLE
Crawl entire website

### ISSUE THREAD

**Issue by vyom00** [pa11y/pa11y#417]
Hi

Can i crawl the entire website with pa11y dahsboard ?

Thanks

**Comment by hollsk** [comment]
Hi @vyom00 - it's not possible with Pa11y Dashboard.  We recommend choosing representative templates to add to the Dashboard, that include your most important pages and functions. 

If you're using continuous integration, we also have [Pa11y CI](https://github.com/pa11y/pa11y-ci), which accepts a sitemap. It doesn't feed back results into Pa11y Dashboard, but can be used to fail builds if accessibility errors are encountered.

**Comment by joeyciechanowicz** [comment]
As @hollsk said, it's not possible within the dashboard.

However if you are content with a command line tool then you can use https://github.com/liip/TheA11yMachine to crawl a site
