### ISSUE TITLE
Running Pa11y-ci with sitemap 

### ISSUE THREAD

**Issue by paul-ks** [pa11y/pa11y#418]
Hi, I am running pa11y-ci with a sitemap like that: pa11y-ci --sitemap **url of sitemap** and I am getting the following message: The sitemap "**url of sitemap**" could not be loaded.

Also, how can I tell pa11y-ci to point to a sitemap on the filesystem instead of an url?

Thanks,
Paul

**Comment by hollsk** [comment]
Issue moved to [pa11y/pa11y-ci #65](https://github.com/pa11y/pa11y-ci/issues/65) via [**ZenHub**](https://www.zenhub.com/)
