### ISSUE TITLE
pa11y won't accept submit button to be outside of form

### ISSUE THREAD

**Issue by brentguf** [pa11y/pa11y#419]
Hi, 

I keep getting the following error, even though we have a `button` with correct `form` attribute and `form` with correct `id` attribute:

> This form does not contain a submit button, which creates issues for those who cannot submit the form using the keyboard. Submit
   buttons are INPUT elements with type attribute "submit" or "image", or BUTTON elements with type "submit" or omitted/invalid.

Is it possible pa11y only looks inside form elements?

Thanks.

**Comment by hollsk** [comment]
Hi @brentguf - thanks for using Pa11y! 

The rulesets come from HTML_Codesniffer, so the change would need to be made there instead of in Pa11y. Could you please open this issue in the [HTML_Codesniffer repo](https://github.com/squizlabs/HTML_CodeSniffer/issues) instead? Thanks!

**Comment by fuzzbomb** [comment]
I couldn't find an issue in the HTML_Codesniffer repo so I filed one myself.

**Comment by hollsk** [comment]
thanks @fuzzbomb !

**Comment by fuzzbomb** [comment]
I fixed this upstream in HTML_Codesniffer, and it's been merged. It'll be in the next release whenever that gets tagged.

**Comment by hollsk** [comment]
Nice one, thanks very much - I'll update this issue once we've merged the new version and released it.

**Comment by hollsk** [comment]
Hi @brentguf - not yet, sorry! The codesniffer release that includes the fix hasn't gone out yet. Hopefully soon, though.

**Comment by thibaudcolas** [comment]
It looks like HTML_CS [2.3.0](https://github.com/squizlabs/HTML_CodeSniffer/releases/tag/2.3.0) was released in january with that change, along with the fix for #416. I'm not entirely sure how to upgrade since the dependency is vendored (copy-paste some file?), but happy to take a stab at it and make a PR if that helps.

**Comment by joeyciechanowicz** [comment]
#460 changed to using HTML_CodeSniffer from NPM and is now using `2.3.0`. Though we need to do a release of `pa11y` with this change.
If you need it sooner then you can install pa11y from git.
