### ISSUE TITLE
pa11y WCAG 2.1 support

### ISSUE THREAD

**Issue by nicolocarpignoli** [pa11y/pa11y#425]
Hi, thanks for your work, it's really helpful. 
I see from the readme and using pa11y for a while that it uses WCAG 2.0, a version from 2008. From June 2018 we also have WCAG 2.1 standard available.
Does pa11y support new rules from this new version of the standard? If not, do you have in plan to add them in the future?

Reference: https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/

Thanks

**Comment by hollsk** [comment]
Hi @nicolocarpignoli - thanks for using Pa11y! Glad you find it useful ❤️ 

We don't support WCAG 2.1 yet, but we do plan to. We rely on [HTML_Codesniffer](https://github.com/squizlabs/HTML_CodeSniffer) for our rulesets, and they're working on the WCAG 2.1 update now, so it'll arrive shortly. 

We also plan to incorporate [aXe Core](https://github.com/dequelabs/axe-core) as an optional test runner, and I believe they include WCAG 2.1 in their current ruleset. We're not quite ready to merge that work yet, but you can [follow the PR](https://github.com/pa11y/pa11y/pull/408) if you'd like to keep up to date on how it's going 😄

**Comment by jerren1122** [comment]
First I would like to say thanks, this is a great tool and I appreciate the work you do. 

I was looking through HTMLCodeSniffer's ruleset.js on their master branch https://github.com/squizlabs/HTML_CodeSniffer/blob/master/Standards/WCAG2AA/ruleset.js

It appears that they have added WCAG 2.1 rules to their test set. 

When I pull down Pa11y and look at the ruleset.js for WCAG2AA HTML Code Sniffer it states
    "description: 'Web Content Accessibility Guidelines (WCAG) 2.0 AA"

**Comment by joeyciechanowicz** [comment]
Though WCAG 2.1 AA has been added to the `ruleset`, HTML_CodeSniffer hasn't been released yet with that change though. The latest release was 2.4.1 in July 2019, and those changes are from November 2019.
Once a new version is released, we'll pull it into pa11y.

**Comment by jerren1122** [comment]
Thanks, I appreciate you getting back to me.

On Feb 24, 2020, at 7:07 AM, Joey Ciechanowicz <notifications@github.com> wrote:

﻿

Though WCAG 2.1 AA has been added to the ruleset, HTML_CodeSniffer hasn't been released yet with that change though. The latest release was 2.4.1 in July 2019, and those changes are from November 2019.
Once a new version is released, we'll pull it into pa11y.
