### ISSUE TITLE
Test HTML Snippets

### ISSUE THREAD

**Issue by alistair-hmh** [pa11y/pa11y#427]
Hi there!

I'm just beginning to dig into this codebase. It is not clear from the documentation (perhaps this is because it does not exist), - whether there is a way to test snippets of HTML, rather than pointing Selenium/Puppeteer, etc to a whole page?

Ideally, I would be able to test fragments of an app.

Is that possible?

**Comment by hollsk** [comment]
Hey @alistair-hmh - I'm afraid not! Pa11y spins up a headless browser and then injects a script into the rendered page that does the actual testing, so it's only really designed to work on full pages. 

One of the teams where I work had to solve a similar problem to yours, and they ended up using https://github.com/nickcolley/jest-axe instead. Might be useful to you too 😄

**Comment by alistair-hmh** [comment]
Thanks @hollsk! I will check that out.
