### ISSUE TITLE
Use Given Puppeteer Page Instance without page.goto()

### ISSUE THREAD

**Issue by kevinatown** [pa11y/pa11y#428]
Hey! I think it will be great for a way to tell pa11y to ignore the URL and not run `page.goto()` and just use the provided puppeteer page instance. This would allow for:

- a single puppeteer page instance to be programmed separately using puppeteer's own api
- once a page instance manipulated/rendered it can be verified using e2e tests and passed to pa11y

It should be trivial to implement; adding an option like `ignoreUrl` that defaults to false and requires a page instance.

**Comment by kevinatown** [comment]
Also I got a branch with what I was thinking and tests, it was super simple.

**Comment by hollsk** [comment]
Cool! We'd be happy to review a PR if you'd like to submit it 😄

**Comment by kevinatown** [comment]
@hollsk Thanks for your quick response, heres the PR. lmk what y'all think.

**Comment by hollsk** [comment]
Thanks @kevinatown ! Haven't had time for a proper look yet, hoping to do that on friday. From a quick scan it looks great though 😄 

Will get back to you shortly!

**Comment by kevinatown** [comment]
Awesome! Let me know if there is anything I need to change!

**Comment by AndrewLeedham** [comment]
@hollsk Any movement on this. Would be a great addition.

**Comment by hollsk** [comment]
Yes, I agree! I need somebody with a bit more experience than I have to review, and I've been struggling to find somebody who has the time. 

But I haven't forgotten about it, and I'm still on the lookout for a suitable reviewer, hoping to find somebody soon. Thanks for your patience 😄

**Comment by kevinatown** [comment]
@hollsk small bump on the status of the review

**Comment by thaffenden** [comment]
Would also love to use this if you have a chance to finish off the PR.

**Comment by hollsk** [comment]
No promises on timelines, but we've managed to get a bit of momentum on our backlog now, so hopefully we'll get back to this one soon. 

Thanks for your patience, everyone - i know it's taken a while!

**Comment by joeyciechanowicz** [comment]
Closing as the PR is merged
