### ISSUE TITLE
WCAG 2.1 Support

### ISSUE THREAD

**Issue by aweingarten** [pa11y/pa11y#436]
Please add support for WCAG 2.1.
https://www.w3.org/TR/WCAG21/#wcag-2-1-supporting-documents

btw:
Thank you so much for this tool.  I love using it in my CI/CD pipeline.  It makes such a difference

**Comment by thibaudcolas** [comment]
#408 could also be a solution for this, as Axe supports WCAG2.1 (not sure to which extent though).
