### ISSUE TITLE
Multiple reporters?

### ISSUE THREAD

**Issue by krukru** [pa11y/pa11y#446]
Hi there,

is it possible to run pa11y with multiple reporters? We are using pa11y as part of our CI pipeline and we would like to have HTML output for developers and json (or csv) for our CI system. Of course you could run the binary twice, once for each reporter, but this seems inefficient.

Thanks for the great software :)

**Comment by joeyciechanowicz** [comment]
Hi @krukru, thanks for the intrest. Unfortuantly it's not possible to use multiple reporters with the pa11y CLI.

However it would be simple to write your own script that ran pa11y using the JS API and called multiple reporters. The reporters are all seperate NPM packages and can be found under the [pa11y](https://github.com/pa11y) GitHub account.

- https://github.com/pa11y/pa11y-reporter-json
- https://github.com/pa11y/pa11y-reporter-html

They (if I recall correctly) just take the output from `pa11y()` directly. Though you need to call `reporter.begin` first.
