### ISSUE TITLE
Support for Local Storage Manipulation

### ISSUE THREAD

**Issue by dylan0d** [pa11y/pa11y#451]
First of all I've been using pa11y for a couple of weeks now and very much enjoying it

This isn't a bug but rather a suggestion. Our web app has some instructions on first login that pop up over the rest of the applications. These must be manually dismissed or if a certain value is set to true in the local storage they don't show up at all. 

Normally I would use the actions to carry out any navigation required but there doesn't seem to be an action for manipulation local storage in the browser. Is this a feature that's being considered for the future? It would remove the need for a lot of code on our application.

**Comment by joeyciechanowicz** [comment]
Can you hide the elements with CSS rules? Pa11y supports this on the CLI using `--hide-elements` and through the  API [`hideelements`](https://github.com/pa11y/pa11y#hideelements-string).

If not, can you use the [`click`](https://github.com/pa11y/pa11y#actions-array-beta) action to dismiss the pop up before running pa11y?

If that's not possible then you might need to go another route (setup a puppetteer page manually and pass that in). Actions are designed to do what a user would do (with the addition of the `wait-for` to facilitate that).  Local storage manupulation doesn't fall under that.

**Comment by dylan0d** [comment]
Thanks for responding, we eventually did go down that route of setting up a the page in puppeteer before starting pa11y. I had forgotten about raising this, will close now
