### ISSUE TITLE
Cannot set field value if value contains string " to "

### ISSUE THREAD

**Issue by kkoskelin** [pa11y/pa11y#452]
## Expected behaviour
Using `actions`, I should be able to `set field` value for a SELECT menu and specify an option value whose text contains the string " to ".
e.g. `"set field #delivery-method to Send to Me"`

## Actual behaviour
Test fails due to greedy regexp in actions.js and splits on the final occurrence of "to", producing an error:
` • Error: Failed action: no element matching selector "#delivery-method to Send"`

## Steps to reproduce
Create a page with a `select` menu in which an option contains a value containing the word 'to' (a space on either side) such as "Send to Me".  Create an action which attempts to set the specified select value.

## Environment:
```
Pa11y:      5.1.0
Node.js:    8.9.4
npm:        6.4.1
OS:         18.5.0 (darwin)
```

**Comment by josebolos** [comment]
Fixed in #453. Thanks a lot for contributing!
