### ISSUE TITLE
Increase info shown when debug is enabled

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#475]
The pa11y CLI has a `--debug` option that prints our a list of the steps that pa11y is doing when testing a page. This is sometimes useful to debug, for example, problems in the actions passed to pa11y, or problems in pa11y itself, but there's not enough info being output to debug a page that is not behaving as expected or producing the wrong results.

For example, this is the output of a test that uses HTTP Auth:

```
pa11y --debug http://www.example.com/

Welcome to Pa11y

 > Running Pa11y on URL http://www.example.com/
 > Debug: Launching Headless Chrome
 > Debug: Opening URL in Headless Chrome
 > Debug: Setting request method
 > Debug: Setting request headers
 > Debug: Browser Console: Failed to load resource: the server responded with a status of 401 (Unauthorized)
 > Debug: Injecting HTML CodeSniffer
 > Debug: Injecting Pa11y
 > Debug: Running Pa11y on the page
 > Debug: Document title: ""
```

This is not producing the expected result (a successful test run). The HTTP Auth doesn't seem to be working (the server returns a `401 Unauthorized`) but it works fine when using `curl`. However, there's not much useful information in the output that can help us debug the problem, for example:

> Debug: Setting request method

But the request method is not shown.

> Debug: Setting request headers

But the headers (which contain the authentication details) are not shown.

We would like to increase the information shown when debugging is enabled, so _any_ issues with actions can be debugger easier without having to resort to things like Wireshark.

**Comment by danyalaytekin** [comment]
Hey @josebolos, going to close this, since the final merge above with work @m1rp and @sangitamane appears to have addressed the issue raised, but please reopen if I'm mistaken.

- #526
