### ISSUE TITLE
User Session

### ISSUE THREAD

**Issue by vishal-ghawale** [pa11y/pa11y#499]
How to set "user session" data to request internal pages of application through pa11y or Pa11y-CI so we can run the test on internal pages of application as well ?

**Comment by joeyciechanowicz** [comment]
You can pass `headers` with a cookie in it: https://github.com/pa11y/pa11y#headers-object

You can also use `[actions](https://github.com/pa11y/pa11y#actions)` to log the user in.

Failing that, you can set up the `puppeteer` instance yourself and pass the `browser` and `page` in (with the `ignoreUrl` option)
