### ISSUE TITLE
pa11y failed to Error: Failed to launch chrome! 

### ISSUE THREAD

**Issue by kvemulap01** [pa11y/pa11y#505]
**npm -v**
6.12.1
**node -v**
v12.13.1
**pa11y -V**
5.3.0
**RHEL vrsion**
7.6 (Maipo)
Also, I tried the below-mentioned steps, but no luck. 
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
----------------------------------------------------------------------------------------------------------
Getting below error while running "pa11y www.google.com"

Welcome to Pa11y

 > Running Pa11y on URL http://www.google.com

Error: Failed to launch chrome!
[1127/090329.278232:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x56253f37b879 base::debug::CollectStackTrace()
#1 0x56253f2d8c63 base::debug::StackTrace::StackTrace()
#2 0x56253f2ed013 logging::LogMessage::~LogMessage()
#3 0x562540a8795e service_manager::ZygoteHostImpl::Init()
#4 0x56253ef1cadc content::ContentMainRunnerImpl::Initialize()
#5 0x56253ef6872c service_manager::Main()
#6 0x56253ef1b0b1 content::ContentMain()
#7 0x56253ef6799d headless::(anonymous namespace)::RunContentMain()
#8 0x56253ef6770b headless::HeadlessShellMain()
#9 0x56253ccf81b8 ChromeMain
#10 0x7ffa2d6c53d5 __libc_start_main
#11 0x56253ccf802a _start

Received signal 6
#0 0x56253f37b879 base::debug::CollectStackTrace()
#1 0x56253f2d8c63 base::debug::StackTrace::StackTrace()
#2 0x56253f37b401 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7ffa3383a5d0 <unknown>
#4 0x7ffa2d6d9207 __GI_raise
#5 0x7ffa2d6da8f8 __GI_abort
#6 0x56253f37a265 base::debug::BreakDebugger()
#7 0x56253f2ed461 logging::LogMessage::~LogMessage()
#8 0x562540a8795e service_manager::ZygoteHostImpl::Init()
#9 0x56253ef1cadc content::ContentMainRunnerImpl::Initialize()
#10 0x56253ef6872c service_manager::Main()
#11 0x56253ef1b0b1 content::ContentMain()
#12 0x56253ef6799d headless::(anonymous namespace)::RunContentMain()
#13 0x56253ef6770b headless::HeadlessShellMain()
#14 0x56253ccf81b8 ChromeMain
#15 0x7ffa2d6c53d5 __libc_start_main
#16 0x56253ccf802a _start
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007fffce70e678 r13: 00007fffce70d658 r14: 00007fffce70d658 r15: 00007fffce70d670
  di: 000000000000bba1  si: 000000000000bba1  bp: 00007fffce70d600  bx: 00007ffa2da6a868
  dx: 0000000000000006  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007fffce70d4c8
  ip: 00007ffa2d6d9207 efl: 0000000000000202 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/pa11y/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/usr/lib/node_modules/pa11y/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:198:15)
    at Interface.close (readline.js:394:8)
    at Socket.onend (readline.js:172:10)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

**Comment by hollsk** [comment]
Hi Krishna,

Please try the suggestion in this issue: https://github.com/pa11y/pa11y/issues/411

Thanks for using Pa11y!

**Comment by kvemulap01** [comment]
Hi @hollsk 

Thank you quick reply, no it is not working, still getting the same error.

**Comment by hollsk** [comment]
Can you post your full configuration file, please? You can redact any URLs that need to stay private.

**Comment by josebolos** [comment]
I guess that everything is working now for you, feel free to create another issue if not!
