### ISSUE TITLE
HTML_Codesniffer 2.5.0 is out

### ISSUE THREAD

**Issue by hollsk** [pa11y/pa11y#514]
https://github.com/squizlabs/HTML_CodeSniffer/releases/tag/2.5.0 💖 

Comparison with 2.4.1 here: https://github.com/squizlabs/HTML_CodeSniffer/compare/2.4.1...2.5.0

I have forgotten how this is managed. Does it all go through the runner now? Do all the Pa11y tools use the runner?

**Comment by joeyciechanowicz** [comment]
Yep, everything uses runners now. So just has to be bumped there.

I'm pretty certain all the pa11y tools use the runners now. As they all use pa11y which then uses the runners.

**Comment by josebolos** [comment]
Pa11y v6.0.0 is now out, which includes version 2.5.1 of HTML_CodeSniffer.
