### ISSUE TITLE
pa11y scans the angular application before it has loaded completely.

### ISSUE THREAD

**Issue by aanand07** [pa11y/pa11y#515]
I'm trying to integrate pa11y with my angular application, but pa11y scans the app before it has completely rendered, this gives an incomplete report. I've tried using action to wait for a particular element in the innermost route to be available, but by that time pa11y times out, and the timeout provided in the conf file does not seem to work. The only way I'm able to generate an accurate report is by providing a very large timeout and wait time.
I think there should be a way to prevent pa11y from running before the application renders completely.

## Environment:
```
Pa11y:      5.3.0
Node.js:    10.15.3
npm:        6.4.1
OS:         10.0.18362 (win32)
```

**Comment by hollsk** [comment]
Hi @aanand07 ! Pa11y includes this action:

`'wait for #my-image to emit load'`

You can try combining that action with Angular's UI router view load events, as described here: https://github.com/angular-ui/ui-router/wiki#view-load-events

Hope it helps 😄

**Comment by aanand07** [comment]
Hi @hollsk , thanks for your reply. 
I couldn't find a way to emit load event from angular v8. But I've been trying the below action, which should work ideally.

> "wait for element #some-id to be visible"
 But pa11y just times out after 30000ms, even if it couldn't find the id, some user friendly error message should be thrown, it shouldn't time out , what you say?

**Comment by iain-davis** [comment]
@aanand07, did you discover a way around this issue? We're having a similar issue with a React project. We don't want to run the scan until the page is fully rendered, but the scan seems to scan too early. We attempted to use a wait for, with the same result you had (timeout after 30000ms).

**Comment by aanand07** [comment]
@iain-davis, we've used [wait-on](https://www.npmjs.com/package/wait-on), to wait till the application gets rendered in the browser, and then we run pa11y. And actions have been added in config to wait for a particular element to visible.

**Comment by joeyciechanowicz** [comment]
`wait for .selector to be visible` is an easy approach.

Aditionally you can set up a puppeteer `browser` and `page` instance with any pre-scan actions performed (wait for elements, click stuff etc) and then pass that to `pa11y` with the `ignoreUrl` flag.

**Comment by iain-davis** [comment]
The puppeteer approach will be what we explore next. We've attempted a wait for `wait for #element-id to be visible` and that simply timed out at 30 seconds which may suggest we have something broken going on. The puppeteer approach might shed some light on what's going on.

**Comment by joeyciechanowicz** [comment]
I've found the `screen capture example.png` really helpful for debugging SPA's in the past.
Especially used in combination with `--wait 30000`
