### ISSUE TITLE
Replace chalk with a leaner alternative

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#516]
`pa11y` uses [`chalk`, which has an install size of 105kB](https://packagephobia.now.sh/result?p=chalk).

There are some similar packages which seem to have zero dependencies and an install size of ~10kB:

* https://packagephobia.now.sh/result?p=kleur
* https://packagephobia.now.sh/result?p=colorette

We should consider replacing this library wherever is used in pa11y.

**Comment by kkoskelin** [comment]
@josebolos I only see `chalk` being referenced in the `package-lock.json` -- is this not needed for `pa11y/pa11y` or have I overlooked something?

**Comment by josebolos** [comment]
Hi @kkoskelin! It was probably introduced by one of the depencies that I fixed already, so there may be nothing to do here. I'll keep this issue open until we release 6.0.0 final.

**Comment by josebolos** [comment]
This is now fixed in pa11y v6.0.0.
