### ISSUE TITLE
npm ERR! notarget No matching version found for pa11y@beta

### ISSUE THREAD

**Issue by puneshkunmun** [pa11y/pa11y#522]
Hi Team,

I am facing issue, while running my package.json :

npm ERR! code ETARGET
npm ERR! notarget No matching version found for pa11y@beta
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 

Previously this was running fine.

**Comment by josebolos** [comment]
Hi @puneshkunmun,

Thanks for creating this issue! There are currently two versions of pa11y published on npm:

* Version 5 (the current stable).
* Version 6 (currently in alpha release).

You probably want to remove the "beta" tag from your command and just use:

```
npm install -g pa11y
```

I hope that helps!

**Comment by josebolos** [comment]
Assuming this fixed your problem, closing the issue. Feel free to reopen if not!
