### ISSUE TITLE
Remove support for the (old) Section 508

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#528]
This is a leftover from before WCAG 2.0 was incorporated by reference into Section 508, so we should probably remove all the options related to this as it's unlikely anyone will still be using it.

**Comment by redgardner** [comment]
I'd be happy to pick this work up if that's okay? 

Should pa11y-runner-axe also have this reference removed? https://github.com/pa11y/pa11y-runner-axe/blob/master/lib/runner.js#L89

**Comment by josebolos** [comment]
This has now been released as part of v6.0.0, thanks @redgardner for the PR!
