### ISSUE TITLE
FR: IBM equal access "accessibility-checker" as runner

### ISSUE THREAD

**Issue by masi** [pa11y/pa11y#531]
## Expected behaviour
`pa11y --runner equal-access` works.

## Actual behaviour
Runner _equal-access_ not recognized.

## Information:
https://www.npmjs.com/package/accessibility-checker

**Comment by kkoskelin** [comment]
Did you actually install the `accessibility-checker`module?  It is not included with `pa11y` as far as I know.

**Comment by masi** [comment]
It's not included, that's the point :)

I really should have been more verbose and not relying on FR for feature request alone.

Or would it work magically if I installed bot packages in the same directory. I actually didn't try because the docs do not mention _equal-access_ at all.

Writing a runner seems to be straigthforward. I guess I could try my luck.

**Comment by kkoskelin** [comment]
You can see how runners are loaded here: https://github.com/pa11y/pa11y/blob/master/lib/pa11y.js#L441
If you have a project containing both `pa11y` and your runner, it should find it via `require` I believe.

**Comment by joeyciechanowicz** [comment]
You need a package in your `node_modules` that matches the name `pa11y-runner-RUNNER_NAME` which implements the pa11y runner API.
In this instance you'd need a wrapper around `accessibility-checker` and publish it as `pa11y-runner-equal-access ` then you can run `pa11y --runner equal-access`
