### ISSUE TITLE
Don't download Chromium

### ISSUE THREAD

**Issue by RobinKnipe** [pa11y/pa11y#533]
## Expected behaviour
Running `pa11y` with `npx` makes no sense if it has to download `chromium` every time. Instead you should be able to cache a previously downloaded instance, or better yet, use a locally installed version.
> $ chromium --version
    Chromium 86.0.4240.111 snap
    $ npx pa11y --environment
    ~Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s~
    Pa11y:      5.3.0
    Node.js:    14.13.1
    npm:        6.14.8
    OS:         5.4.0-48-generic (linux)

## Actual behaviour
Chromium is downloaded each time `pa11y` is run with `npx`.

## Steps to reproduce
Run any command with `pa11y`, even one that doesn't require any browser interaction, e.g.
```
npx pa11y --environment
```

## Environment:
```
$ npx pa11y --environment
Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
Pa11y:      5.3.0
Node.js:    14.13.1
npm:        6.14.8
OS:         5.4.0-48-generic (linux)
```

**Comment by josebolos** [comment]
Hi @RobinKnipe 

Thanks for creating this issue.

[npx](https://www.npmjs.com/package/npx) is a useful tool to execute Node.js-based binaries when you're running a tool inside a CI system, as it saves you the hassle of having to install pa11y itself.

Npx is not related to Pa11y but rather part of the NPM project, so you may want to suggest any improvements [to their repo](https://github.com/npm/npx#readme).

Thank you!

**Comment by RobinKnipe** [comment]
Hi @josebolos . Thanks for the quick reply. I feel there is an underlying concern here that still has not been addressed - whether running `pa11y` with `npx` or by any other means - I would still expect the _default_ behaviour to check if `chromium` is already available locally before trying to download it. For example on my machine I use Chromium as my main browser but pa11y still tries to download its own copy, I would hope this shouldn't be necessary.

**Comment by RobinKnipe** [comment]
P.S.
I will look into the `npx` cache opportunity - I note that there is a `--cache` command line argument, so I guess there should be a way to do this - although it still feels like something the pa11y project should be trying to use.
