### ISSUE TITLE
Feature request - support playwright browser instance

### ISSUE THREAD

**Issue by mickyginger** [pa11y/pa11y#534]
At https://frontendmentor.io we've been using pa11y to run accessibility testing against uploaded solutions to the platform.

We also used puppeteer to take a screenshot of the page (and do various other bits and pieces). However we had quite a lot of rendering issues, so we switched to playwright.

We had been passing in the puppeteer browser instance to pa11y in order to optimize the process, but now that we've switched to playwright, we're no longer able to do that. We're now experiencing some timeouts on staging which we think are related to performance (we're not actually sure because the only error we get is a timeout error.)

I'd like to have a go at modifying the `lib/pa11y.js` file to handle a playwright browser instance, but I thought it might be worth running it by you first, incase you're already looking into it or have some reckons on the best approach.

**Comment by josebolos** [comment]
Hi @mickyginger,

Thanks for creating this issue. At the moment, we're not keen on in migrating away from `puppeteer`, as it currently covers all our needs, and migrating away from it would add to the maintenance burden. We're already stretched as it is.

Luckily, it looks like `puppeteer` has added support to Firefox in their latest version, so it may be possible to achieve what you want using this feature:
https://github.com/puppeteer/puppeteer/blob/v8.0.0/docs/api.md#puppeteerconnectoptions

**Comment by mickyginger** [comment]
Thanks for your reply @josebolos, I'll close this for now then.

**Comment by venkatsaivikram** [comment]
<img width="786" height="755" alt="Image" src="https://github.com/user-attachments/assets/a915f5b3-d6e0-4404-b14c-cb63616050fe" />

I had the same scenario, I'm using playwirght and wanted to integrate pa11y with it.. After debugging through pa11y code flow for generating report, got to know that it expects some puppeteer page object methods which are not available in playwright page object.. Luckily the above code works for me, in which the required props are overridden with noop functions . Might not be a standard way, but it does the job. Hope it helps.
