### ISSUE TITLE
Error on non 200 response

### ISSUE THREAD

**Issue by gemal** [pa11y/pa11y#538]
Using latest pa11y

I was trying to validate a page which returned a 302 so I ended up validating the wrong page

Is there a way to not allow anything but HTTP 200 codes?
or to make sure the validated page is the same as the specified one?

**Comment by kkoskelin** [comment]
It sure doesn't look like there is a facility for this in pa11y right now.  To do this, you'd need to capture the output of `gotoUrl` (the response) and inspect its `status` which would contain the numeric value.  Then you could decide to throw an exception for codes you don't want.  But it does appear that puppeteer won't throw an exception provided it receives a valid HTTP code (even 5xx).

**Comment by iamdharmesh** [comment]
@kkoskelin I think adding `pageStatusCode` to the result is the better option here(like below). what do you think? I would be more than happy to raise PR for this if it looks good to you. Also, maybe we can add pageStatusCode optionally, which is enabled by options passed to pa11y function. 

```
{
  documentTitle: 'Title',
  pageUrl: 'https://example.com',
  issues: [
    ...
  ],
  pageStatusCode: 200
}
```
Thanks.

**Comment by jeffpaul** [comment]
@josebolos @joeyciechanowicz any preference on your end for the approach above?

**Comment by joeyciechanowicz** [comment]
Do you mean that the 302 wasn't followed? Or that it was followed and it
was the redirected-to page that got tested?

**Comment by iamdharmesh** [comment]
@joeyciechanowicz behavior with 302 seems fine. 
My concern here is with generic purpose. For example, the web page behind auth (401), Page not found (404), etc... for these kind of cases, pa11y responds page issues with success (like below). So, it becomes difficult to identify that pa11y has validated different content than we are expecting to be validated.

```
{
    documentTitle: '401 Authorization Required',
    pageUrl: 'https://example.com/',
    issues: [
      {
        code: 'WCAG2AA.Principle3.Guideline3_1.3_1_1.H57.2',
        type: 'error',
        typeCode: 1,
        message: 'The html element should have a lang or xml:lang attribute which describes the language of the document.',
        context: '<html><head><title>401 Authorization ...</html>',
        selector: 'html',
        runner: 'htmlcs',
        runnerExtras: {}
      }
    ]
}
  
```
I believe, Adding more information related to page response like HTTP Response status code to the result will help here.
(Throwing error for non-200 response code will also work here, but not sure if it affect other use-cases)

Thanks

**Comment by joeyciechanowicz** [comment]
Thanks for the extra context @iamdharmesh. 

From the looks of it, this falls under one of two categories:
1.Additional tests are needed to check the correctness of the system, and the 401/403 could have been caught by a different step of the build.
2. The actions/setup functionality of pa11y cannot provide the guarantees needed that you're in the state you expect to be.

If this does fall under 2), then could the [`wait for path`](https://github.com/pa11y/pa11y#wait-for-fragmentpathurl) action be used instead?

**Comment by iamdharmesh** [comment]
Thanks for the response @joeyciechanowicz,

For my current use-case it falls under 1).
