### ISSUE TITLE
Align Attribute non issue

### ISSUE THREAD

**Issue by smustgrave** [pa11y/pa11y#552]
• Align attributes .

(#block-prac-content > article > div > div > div > div:nth-child(3) > div >
p:nth-child(17))

<p align="center" style="margin-right:1px; margin-bottom:14px;
margin-left:3px; text-align:center; text-indent:-0.5pt"><span
style="font-size:12pt"><s...</p>

Why is this being flagged? I'm in the process of recertifying my 508 cert but I took a few years ago and don't remember Align attributes being an issue.

https://www.ssa.gov/accessibility/andi/help/install.html is the tool that's recommended by DHS and that doesn't seem to check that either.  

Is it something that shouldn't be flagged?

**Comment by kkoskelin** [comment]
Which reporter are you using?  `pa11y` simply passes along errors or warnings produced by those reporters.  If you're using HTML_Codesniffer, you can paste your code here to check it: https://squizlabs.github.io/HTML_CodeSniffer/

**Comment by kkoskelin** [comment]
Update: the `align` attribute is mentioned here: https://squizlabs.github.io/HTML_CodeSniffer/Standards/Section508/#prD

**Comment by smustgrave** [comment]
If we don't specify one is that the fallback?

**Comment by josebolos** [comment]
Hi @smustgrave.

Thanks for creating the issue. @kkoskelin is correct, if you don't specify a runner, it will use HTML_CodeSniffer by default, and that's where the rules that pa11y uses come from.
