### ISSUE TITLE
Feature Request: Conditional Actions

### ISSUE THREAD

**Issue by Eireternal** [pa11y/pa11y#567]
We would like to run a set of actions for a site that could contain 2 ways of logging in. Okta or a username/password form. 
Currently pally only accepts one 'actions' param. 

Is it possible to POST and GET two sets of 'actions'? 
If not is it possible to set 'actions' and then set 'inactive actions' as some other param?

That way when we go to edit, we can GET both the data from the current 'actions' set but also toggle a set of 'inactive actions'. This would be that switch between the 2 ways of logging in. Hope that makes sense.

**Comment by josebolos** [comment]
Hi @Eireternal,

Thanks for creating this issue. I'm struggling to understand what the desired behaviour here. Is it not possible to test the page twice, with two different sets of actions, one for each way of logging in?

**Comment by Eireternal** [comment]
Hey yes definitely possible to do so by creating another url task. My boss
asked if we can toggle two sets of actions from the same task. I'm not
completely sure why this is so important but my guess is the people we are
setting this tool up for may have 2 or could be 5 types of login for the
same url. In this case it be much easier to have the ability to toggle
multiple action sets per url and not fill up the dashboard.

**Comment by Eireternal** [comment]
I'm a bit of a noob when it comes to this but I noticed the POST call for example will only accept 'actions' here:
https://github.com/pa11y/pa11y-webservice/blob/master/route/tasks.js

I'm assuming I could just make some changes so that POST and GET will accept for example 'altActions'. Really all I'm looking for is a way to keep the alternate set of actions tied to a task. Then I'll have to add Boolean param like 'activeActions' so POST and GET calls can keep track of which set of actions should be the "real" actions and which should just go along for the ride.

Am I on the right track of thinking?

**Comment by josebolos** [comment]
I'm assuming this is about how things are displayed on pa11y-dashboard?

If that's the case then I get the feeling it's going to be easier to define two separate tasks and hack pa11y-dashboard so they display as one single unit, than to try to modify a task to add two different sets of actions, as that will require in dashboard, webservice, changes in the database, plus probably changes in pa11y itself.

**Comment by Eireternal** [comment]
Ok thanks. Will try my best and see if I can get a working solution. Will
report back when I can.
