### ISSUE TITLE
pa11y --environment doesn't show the version of pa11y itself

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#577]
I ran `pa11y --environment` when using pa11y v6 and I was expecting to see the version of pa11y in the output, but it doesn't show:

```sh

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 127.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm

```

The configuration seems to be correct so this may be related to the fact that this is an alpha version, maybe?

https://github.com/pa11y/pa11y/blob/46b49f6ca99736d4a6bfab4b132d13a64b3eb4cb/bin/pa11y.js#L313

**Comment by aarongoldenthal** [comment]
@josebolos  The issue appears to be that when resolving [`npmPackages`](https://github.com/tabrindle/envinfo/blob/main/src/packages.js#L40), `envinfo` looks in `process.cwd` for the `package.json`, pulls all `dependencies` and `devDependencies`, then searches `node_modules` for the package details (treating globally installed modules separately). So, if running `pa11y` itself, there's no dependency, so no output.  If running `pa11y` in a project where it's a `dependency`, it seems to work:

Windows
```sh

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 13.34 GB / 31.81 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    pa11y: ^6.0.0 => 6.0.0
```

Linux
```sh

  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 23.10 GB / 24.91 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  npmPackages:
    pa11y: ^6.0.0 => 6.0.0
```

The other quirk is that it includes the defined dependency as well as version that satisfies it, but for these purposes the actual versions seems most significant, and `package.json` is already loaded and used elsewhere, so the version can be taken from there.

See https://github.com/pa11y/pa11y/pull/591.

**Comment by josebolos** [comment]
Nice one @aarongoldenthal, thanks for the PR!
