### ISSUE TITLE
Pa11y timeout when waiting or navigating

### ISSUE THREAD

**Issue by chaochungtsai** [pa11y/pa11y#578]
Hi, I am not sure if this is filed correctly. Please let me know if there are things I am missing or can explain better.

I am mainly testing actions scripts in pa11y so I can apply it to our .pa11yci files and run it with Pa11y-CI in Jenkins.

## Expected behaviour
When using wait for element x to become visible, expect pa11y to actually wait until element to become visible;
When using navigate to [url], expect pa11y to navigate to URL
If element does not exist, then I would get error about invalid element.
If URL does not exist then I should get 404 error.

## Actual behaviour
Sometimes wait for element x or navigate to URL will return Timeout error, but it doesn't happen every time.
I think it is more likely to see timeout error after some kind of login action.

For example, same configuration and same URL
result 1:
![image](https://user-images.githubusercontent.com/22780337/119420991-836b9b00-bcb2-11eb-9b6b-1cdc6e9f6e06.png)
Or, result 2:
![image](https://user-images.githubusercontent.com/22780337/119421093-c3328280-bcb2-11eb-9da4-4b9fb42b56d8.png)
Result 3 uses the wait for url:
![image](https://user-images.githubusercontent.com/22780337/119422153-45bc4180-bcb5-11eb-9ebd-0500162eb487.png)

In my case, it does not matter if "wait for element .login-card to be visible" exist or not, because both the "wait for element .login-card to be visible" and "navigate to https://apps.fs.usda.gov/mars/#/incident" will result in timed out error.

## Steps to reproduce
Run
pa11y -c madb.json --debug https://apps.fs.usda.gov/mars/#/incident

Get error

```
 Error: TimeoutError: Pa11y timed out (30000ms)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\ctsai\AppData\Roaming\npm\node_modules\pa11y\node_modules\p-timeout\index.js:27:54)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

madb.json contents:
```
 {
  "chromeLaunchConfig": {
      "ignoreHTTPSErrors": false
   },
   "defaults":{
      "timeout": 120000,
      "standard":"WCAG2AA",
      "viewport":{
         "width":1920,
         "height":1080
      }
   },
   "actions":[
      "navigate to https://apps.fs.usda.gov/smokejumper/",
      "wait for element #userId to be visible",
      "set field #userId to (username)",
      "set field #password to (password)",
      "click element input[type=submit]",
      "screen capture redirect.png",
      "wait for element button#btnMARS.btn.btn-success.mars to be visible",
      "Click element button#btnMARS.btn.btn-success.mars", 
      "screen capture choose.png",
      "wait for url to be https://apps.fs.usda.gov/mars/#/register",
      "wait for element .login-card to be visible",
      "screen capture mars.png",
      "navigate to https://apps.fs.usda.gov/mars/#/incident",
      "screen capture done.png"
   ]
}
```
## Environment:
```
(please run `pa11y --environment` and paste the output here)
```
Pa11y:      5.3.1
Node.js:    10.16.3
npm:        6.9.0
OS:         10.0.18363 (win32)

**Comment by sangitamane** [comment]
Hi @chaochungtsai,  thanks fo using Pa11y!
I had a look at the configuration you shared and the timeout issue. 
1. To run pa11y with custom timeout, use the configuration as described in [readme doc](https://github.com/pa11y/pa11y#timeout-number).
2. Timeout added to `defaults` object is for [Pa11y-CI](https://github.com/pa11y/pa11y-ci#default-configuration)
3. That's the reason why Pa11y timed out in 30000ms which is default set and not with the timeout you desired.

**Comment by sangitamane** [comment]
I hope this helps, do not hesitate to create a new issue if you still face the problem!
