### ISSUE TITLE
Latest `commander` version breaks tests

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#580]
Upgrading the dependencies to the latest versions causes the tests to fail due to breaking changes in `v7.0.0` of `commander`.

We need to follow the migration guide and make the necessary code changes so we can keep pa11y up-to-date.

https://github.com/tj/commander.js/releases/tag/v7.0.0

**Comment by sangitamane** [comment]
closes by [#600](https://github.com/pa11y/pa11y/pull/600)
