### ISSUE TITLE
pa11y using puppeteer@1.19.0 which has dependency ws@6.2.1 with npm vulnerability 1748

### ISSUE THREAD

**Issue by ap-buf** [pa11y/pa11y#588]
│ ├─┬ pa11y@5.3.1
│ │ └─┬ puppeteer@1.19.0
│ │ └── ws@6.2.1 deduped

https://www.npmjs.com/advisories/1748

The latest version of puppeteer (10.0.0) is using ws@7.4.6 and does not have this vulnerability.

Would it be possible to include an updated version of puppeteer in your next release.

**Comment by joeyciechanowicz** [comment]
Just checking and it seems @josebolos upgraded everything recently! https://github.com/pa11y/pa11y/pull/581
