### ISSUE TITLE
Increase default timeout from 30s to 60s

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#590]
The default timeout of 30s seems to be too small for many common uses of pa11y:

* CD/CI environments, specially in the free tiers, have usually fairly low CPU power, which cause tests to be slow and things to take much longer.
* Modern pages with loads of third party content may often show load times longer than 30 seconds on a decently powered CPU.
* Pa11y users with lower income or in places with slow internet connections may be experiencing many more timeouts than other users due to the speed and latency of the network between them and the site being tested.

A cursory review of pa11y configs at projects at Springer Nature show that most of them already set the default timeout to 60 seconds.

I propose to increase the default timeout from the current amount, which is 30 seconds if I'm not mistaken, to (at least) 60 seconds.

I like to be conservative with changes and don't want to mess with people's pipelines too much, so it may be safer to make this change breaking and release it for v7, so I've created a milestone and assigned this issue to it, but we can always change that if we don't agree :shrug:.

**Comment by Bracciata** [comment]
This seems to be merged and should be good to close. Is that correct?

**Comment by sangitamane** [comment]
Yes, thanks!
