### ISSUE TITLE
phantomjs timeout when getting new htmlcodesniffer

### ISSUE THREAD

**Issue by bryanrasmussen** [pa11y/pa11y#61]
trying this
pa11y -c "http://raw.githubusercontent.com/bryanrasmussen/HTML_CodeSniffer/master/HTMLCS.js" www.sundhed.dk
or this
pa11y -c "https://raw.githubusercontent.com/bryanrasmussen/HTML_CodeSniffer/master/HTMLCS.js" www.sundhed.dk

always gives me 

> Loading page...
> Running HTML CodeSniffer...
> Error: PhantomJS timeout

another thing is I want to pass a lot more info from htmlcs, for example the html that triggered the warning, an xpath to the element etc. 

If I want to the above should I just make sure that it comes out in the message.msg, and then that is adequate ( as I looks like from the code) or will I have to do some adaption of pa11y itself? (if so I would like to know how to compile)

**Comment by adelevie** [comment]
:+1: on the ability to get the xpath. Any pointers on where/how this can be done?
