### ISSUE TITLE
Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by fishcharlie** [pa11y/pa11y#619]
## Expected behaviour

It to be able to run successfully.

## Actual behaviour

```
Error: spawn Unknown system error -86
```

## Steps to reproduce

```
npm install -g pa11y
pa11y "https://apple.com"
```

Above is the command I used to generate the error. I'm unsure if there are other steps to reproduce this. I'm **guessing** there is an issue with my configuration or environment specifically?? I'm not sure how to provide steps to reproduce that tho since I don't know what specifically that configuration or environment would be? Maybe the fact that I'm using an Apple Silicon machine?

## Full Command & Output:

```
pa11y "https://apple.com"

Welcome to Pa11y

 > Running Pa11y on URL https://apple.com

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at BrowserRunner.start (/Users/charliefish/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:80:34)
    at ChromeLauncher.launch (/Users/charliefish/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:88:16)
    at async setBrowser (/Users/charliefish/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/lib/pa11y.js:135:19)
    at async runPa11yTest (/Users/charliefish/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/lib/pa11y.js:67:2)
    at async /Users/charliefish/.nvm/versions/node/v16.13.0/lib/node_modules/pa11y/node_modules/p-timeout/index.js:50:13
```

## Environment:

```
pa11y --environment

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 32.56 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  pa11y: 6.1.1
```

**Comment by joeyciechanowicz** [comment]
This appears to be a problem with running puppeteer on M1, `86` is "unknown arch".

Theres a potential short term fix here: https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-787912758

W.r.t fixing pa11y, it's mentioned that version 10 of puppeteer may fix this.

**Comment by josebolos** [comment]
Hi @fishcharlie

Thanks for creating the issue. We plan to update the version of puppeteer that pa11y uses to a more recent version around May, when we will also drop support for Node 12.

Please note that, in the meantime, this issue can also be avoided by just using Rosetta. I expect most users to have Rosetta installed already so we're happy with this workaround until puppeteer can be upgraded.

**Comment by Finesse** [comment]
Run
```bash
softwareupdate --install-rosetta
```
to install Rosetta 2. It translates the x64 executable to ARM which prevents the error.
