### ISSUE TITLE
Feature request - allow users to pass configuration to axe runner

### ISSUE THREAD

**Issue by Dikshita25** [pa11y/pa11y#620]
Seems like pa11y does not have support to pass configuration to axe runner

We had a requirement, wherein i wanted to pass multiple and specific tags to the axe runner.  I did have a look at the code, but seems like the tags of accessibility are by default defined (hard coded). 

It would be great if we could pass the runner config separately to pa11y.  I have seen that there is another issues, suggesting solutions to handle this [#604](https://github.com/pa11y/pa11y/issues/604). 

If there is an existing solution to this, please do let me know and thanks for your time.

**Comment by joeyciechanowicz** [comment]
Really good question. I'll close this in favour of #604, and put my thoughts there.
