### ISSUE TITLE
Add Windows and Macos to the test matrix

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#641]
The [test matrix](https://github.com/pa11y/pa11y/blob/14b4d4ab2a65922d73cff4c66b538bfe0fdb328a/.github/workflows/tests.yml#L24) is currently setup to run the test only on an Ubuntu Linux operating system. This is useful as most of pa11y's usage comes from CI systems, which usually run Linux.

Most developers contributing to pa11y use MacOS, and we've also had a few issues reported in the past on Windows, so I think it's time we add those two OSs to the test matrix and ensure that pa11y works on all of the three major OSs.

A WIP PR is available on #640. Testing is working on all 3 OSs, but the tests on Windows are failing to run at the moment due to the way Jest is set up.

I'm hoping to get this ready for v7 that we'll release as soon as Node 12 is deprecated at the end of this month.

**Comment by danyalaytekin** [comment]
Closing as this has since arrived in `main`!
- #678
