### ISSUE TITLE
Show line numbers of source of error in report

### ISSUE THREAD

**Issue by jsit** [pa11y/pa11y#646]
It would be useful to get line numbers in the output for use in hinting plugins. For instance if an `<img>` with no `alt` is on line `60`, something like `"line": 60` could be returned in the JSON.

```
  System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 17.49 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.22.9 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.npm/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  pa11y: 6.2.3
```

**Comment by joeyciechanowicz** [comment]
What line numbers are you referring to? Source of error? Line numbers on the printed output?

**Comment by jsit** [comment]
@joeyciechanowicz Sorry, yes, I mean line numbers of the source of error.

**Comment by joeyciechanowicz** [comment]
Unfortunately, this isn't possible. You can't get the line number of a DOM
element (which is the error source). due to the browser adding tags itself,
and the DOM not being static. Some more info [here](
https://stackoverflow.com/questions/12048783/how-to-get-the-code-line-number-of-a-dom-element
)
