### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by dejankocic** [pa11y/pa11y#650]
Hello,

Following your instructions I run the installation with 
npm install -g pa11y

The installation crashes with the following error message

ERROR: Failed to set up Chromium r869685! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/.local-chromium' }
npm WARN notsup Unsupported engine for pa11y@6.2.3: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pa11y@6.2.3
npm WARN notsup Unsupported engine for commander@8.0.0: wanted: {"node":">= 12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: commander@8.0.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@9.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@9.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-04T12_09_58_523Z-debug.log

in the log file there is a following entry

2079 verbose notsup Not compatible with your version of node/npm: commander@8.0.0
2079 verbose notsup Required: {"node":">= 12"}
2079 verbose notsup Actual:   {"npm":"6.14.4","node":"10.19.0"}
2080 verbose stack Error: puppeteer@9.1.1 install: `node install.js`
2080 verbose stack Exit status 1
2080 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
2080 verbose stack     at EventEmitter.emit (events.js:198:13)
2080 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2080 verbose stack     at ChildProcess.emit (events.js:198:13)
2080 verbose stack     at maybeClose (internal/child_process.js:982:16)
2080 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2081 verbose pkgid puppeteer@9.1.1
2082 verbose cwd /home/dejan/pa11y-webservice
2083 verbose Linux 5.4.0-113-generic
2084 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "pa11y"

What I could do about this?

Thx,
Dejan

---

## Environment
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

```
(please run `pa11y --environment` and paste the output here)
```

**Comment by josebolos** [comment]
Hi @dejankocic!

The logs you posted show that you're using Node.js v10, but pa11y v6 requires Node.js v12 or v14.

```
npm WARN notsup Not compatible with your version of node/npm: pa11y@6.2.3
npm WARN notsup Unsupported engine for commander@8.0.0: wanted: {"node":">= 12"} (current: {"node":"10.19.0","npm":"6.14.4"})
```

Please try again with a supported Node.js version and feel free to reopen the issue and include new logs if this doesn't fix the problem.
