### ISSUE TITLE
[Feature] - Playwright support

### ISSUE THREAD

**Issue by vitalics** [pa11y/pa11y#656]
Hi pa11y team.

While I see the source code - I see that you [use puppeteer](https://github.com/pa11y/pa11y/blob/master/lib/pa11y.js#L8) to launch the browser.

I would like to ask you enable playwright support.

## High-level API 

``` ts
// filename="example/pw.ts"
import p11y from 'p11y';
import pw from 'playwright'

async function main(){
        // Launch our own browser
		browser = await pw.chromium.launch();
        const context =  await browser.newContext();
		const page =  browser.newPage(),

		// Test http://example.com/ with our shared browser
		const result1 = await pa11y('http://example.com/', {
			browser,
			page
		});

        console.log(result1);

    // close context and browser
}

main();
```

**Comment by josebolos** [comment]
Hi @vitalics!

Thanks for creating this issue. As discussed previously in https://github.com/pa11y/pa11y/issues/534 we're not keen on in migrating away from puppeteer, as it currently covers all our needs. Migrating away from puppeteer would required to rewrite a significant amount of code, and consider that our time would be better spent fixing bugs that rewriting the project for something that would provide no benefit to us.

I hope that this helps.

**Comment by venkatsaivikram** [comment]
<img width="786" height="755" alt="Image" src="https://github.com/user-attachments/assets/a915f5b3-d6e0-4404-b14c-cb63616050fe" />

I had the same scenario, I'm using playwirght and wanted to integrate pa11y with it.. After debugging through pa11y code flow for generating report, got to know that it expects some puppeteer page object methods which are not available in playwright page object.. Luckily the above code works for me, in which the required props are overridden with noop functions . Might not be a standard way, but it does the job. Hope it helps.
