### ISSUE TITLE
CircleCI run differs from expected output. JS not running before pa11y test.

### ISSUE THREAD

**Issue by EvanHerman** [pa11y/pa11y#659]
There are a number of elements on our page that are updated on page load to add certain attributes (aria-label, alt etc). When I run the tests locally, they are passing. When things are running in a CircleCI instance it's looking like the javascript isn't running to inject those attributes, and our tests are failing.

Is there a reason that the JS wouldn't be running before the pa11y tests run in CircleCI but does locally? I've tried adding a wait, but that doesn't seem to help.

## Environment

```
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Memory: 41.28 GB / 68.58 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  pa11y: 6.2.3
```

**Comment by josebolos** [comment]
Hi @EvanHerman!

I'm not familiar with CircleCI but I assume there shouldn't be a difference in how tests are run there. A couple things to consider could be:

* If you're using `pa11y-ci` in CircleCI, try ensuring that `concurrency` is set to `1`. Some environments may only allow for a single Node.js process to run, so any kind of work in parallel may fail in strange ways.
* If any of the changes introduced on page load are visible on the page, you could try using any of the three `wait for` actions. This is the only reliable way to ensure that the page is in the state that you want to test:

* https://github.com/pa11y/pa11y#wait-for-fragmentpathurl
* https://github.com/pa11y/pa11y#wait-for-element-state
* https://github.com/pa11y/pa11y#wait-for-element-event

I hope this helps!
