### ISSUE TITLE
Can we get violations defects for after login pages using pa11y?

### ISSUE THREAD

**Issue by KunalBhatia407** [pa11y/pa11y#661]
Hi,

Can we get violations defects for after login pages using pa11y? I mean can we get all issues for session based pages? If yes, kindly share the process(commands) to run it.

Sincere thanks,
Kunal

**Comment by danyalaytekin** [comment]
Hi @KunalBhatia407, thanks for your question.  It's been a while, but if you're still interested, or for anyone else with the same question, you could create the journey in JS, using a combination of:

1. [Pa11y actions](https://github.com/pa11y/pa11y/blob/main/example/actions/index.js) to perform the login steps
1. [reusing the Puppeteer instance](https://github.com/pa11y/pa11y/blob/main/example/puppeteer/index.js) that has acquired the session

**Comment by danyalaytekin** [comment]
Hopefully it's ok for me to close this now but please follow up if you'd like more help.
