### ISSUE TITLE
Inconsistencies between pa11y and other accessibility tools

### ISSUE THREAD

**Issue by LuciaLux** [pa11y/pa11y#665]
I tried to scan the same site both from your tool and using the service offered by https://mauve.isti.cnr.it/singleValidation.jsp
The result of the 2 reports is not the same and also some that the Mavue tool recognizes as errors, pa11y gives them as a notice. Note that they have the same path but different compliance.
Does this mean less truthfulness?

**Comment by hollsk** [comment]
Hey LuciaLux! Thanks for using Pa11y 😄 

Getting different results from different tools is normal. All rulesets are created by different people, and there's no universally-agreed set of interpretations. You'll usually find that one tool is stricter on a particular rule, but more permissive on another. It just comes down to differences in interpretation of more subjective problems. 

I always recommend that you use more than one automated tool, and never rely on a single ruleset. For this reason, Pa11y includes two separate rules engines, [HTML_Codesniffer](https://squizlabs.github.io/HTML_CodeSniffer/) by Squizlabs and [axe](https://www.deque.com/axe/) by Deque. There are others that haven't been integrated into Pa11y, and they all have value. The UK government published [an audit of different popular rulesets](https://alphagov.github.io/accessibility-tool-audit/) in 2018, and there wasn't really a lot of consistency (do bear in mind that this project was 5 years ago, and all the rulesets have changed in that time, so the numbers may not reflect the current situation).

As to whether one tool is more truthful than other... that sort of depends on how you interpret the rule yourself. You might find yourself agreeing with one tool more than another, but that doesn't necessarily mean it's more accurate, just that it agrees with your own opinions. For some criteria its very easy to say "this is obviously an error", and all tools will agree on it (for example colour contrast problems). For other criteria it's harder to get a clear consensus, and this is probably what you're noticing. You'll need to decide for yourself how much you trust a ruleset - is it open source? How many people have contributed to it? What standards are it based on? 

No easy answers for you, but hopefully this will help you understand why different tools return different results! I'm going to close this ticket now, but feel free to continue asking questions if you need them!
