### ISSUE TITLE
Can I include a config file for a report?

### ISSUE THREAD

**Issue by ttnguyen2** [pa11y/pa11y#669]
I have my pa11y.json file. I want to run a report using the config file : 
pa11y --config pa11y.json --reporter html nature.com > results.html

---

## Expected behaviour
    I was expecting the report will pick up hideElements constraints I set in the pa11y.json file . 
##Steps to produce
Create pa11y.json with {
    "defaults": {
   "hideElements": "#google_ads_top_frame"}
  }
Run the script:  
pa11y --config pa11y.json --reporter html nature.com > results.html
 
## Actual behaviour
 Pa11y report didnt use the pa11y.json config file
## Env
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 15.91 GB / 31.83 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  pa11y: 6.2.3

**Comment by aarongoldenthal** [comment]
Hi @ttnguyen2,

When using pa11y-ci, the config file does have a `defaults` property, with options for all tested URLs. Pa11y, however, is only testing a single URL, so properties are defined at the root level. So, if you change your pa11y.json file to what's below I believe it will resolve your issue.

```json
{
    "hideElements": "#google_ads_top_frame"
}
```

**Comment by ttnguyen2** [comment]
Thank you for confirming and your tip. It works now.
