### ISSUE TITLE
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (869685)

### ISSUE THREAD

**Issue by careyestes** [pa11y/pa11y#674]
## Expected behaviour
From the CLI, the expectation is a successful test of the url provided
`pa11y https://example.com`

## Actual behaviour
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (869685).
    at ChromeLauncher.launch (/usr/local/lib/node_modules/pa11y/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:82:27)

## Steps to reproduce
Run `pa11y https://example.com` from the CLI

## Environment
Mac M1 Ventura

```
(please run `pa11y --environment` and paste the output here)
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 50.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  pa11y: 6.2.3

```

**Comment by zietbukuel** [comment]
I'm having the same exact issue, except that I'm running this on a Linux machine.

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (1) x64 DO-Regular
    Memory: 134.70 MB / 1.94 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.21.3 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.18 - /usr/bin/npm
  pa11y: 6.2.3
```

**Comment by altescape** [comment]
Same problem here too. Adding Chrome path to a config file worked:

**config.json:**
```JSON
{
  "chromeLaunchConfig": {
    "executablePath": "/usr/bin/google-chrome",
    "ignoreHTTPSErrors": false
  }
}
```

**Command:**
```BASH
pa11y --config ./config.json https://example.com
```

**Comment by danyalaytekin** [comment]
Hi @careyestes @zietbukuel @altescape @callandr, thanks for your detailed reports and workarounds here.  We have a candidate PR for version 7 in review:

- #681 

If you're still interested (no pressure!), you could test with Node.js 18 or 20 with:

```sh
npm install -g pa11y/pa11y#version-7
```

I think `7.0.0` could resolve your issues, since it has resolved our Ubuntu build issue, but I can't be sure.

**Comment by danyalaytekin** [comment]
Hi all, I believe this should be fixed now, by `pa11y@7`, but let me know if that isn't true and we can reopen.
