### ISSUE TITLE
Add a "testing multiple local files" example

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#80]
Add a "testing multiple local files" example based on @andrewholgate's code in #75.

**Comment by rowanmanning** [comment]
I think I'm going to close this actually, as it's not come up since. I think adding a `file://` example to the README has already done the trick, and the example I'm adding in #153 could be converted to use local files.

**Comment by jleclanche** [comment]
@rowanmanning Is there actually a way to test on multiple local files? I want to run pa11y as a CI step on built HTML files and right now I have to do `for f in ./**/*.html; do pa11y $f; done` which results in spammy output that includes "Welcome to Pa11y" etc and exits immediately after the first erroring html file.

How can I just give pa11y multiple html files to validate through?
