### ISSUE TITLE
Ability to test multiple URLs in a single invocation of the CLI

### ISSUE THREAD

**Issue by alex** [pa11y/pa11y#91]
pa11y is fantastic, thanks for all the hard work that went into!

Having the ability to provide 2+ URLs on the CLI would be helpful.

**Comment by rowanmanning** [comment]
Thanks :)

I'd like to get this built too, it'd be really useful. It'll require a bit of a rethink on how reporters are loaded but totally achievable.

**Comment by Hywan** [comment]
:+1:

**Comment by Hywan** [comment]
Please, read URL from stdin, this way we can pipe a crawler to pa11y.

**Comment by rowanmanning** [comment]
Hi @alex, we're going to descope this at the moment – it probably won't make it into the main library any time soon.

In the meantime, if you're looking for a multiple URL tester, then 18F are working on a Lambda function and I'm also going to be adding more examples in #153.

We may add this at some point in a later major version, but I'll close until then. Thanks
